### PR TITLE
Cookiecutter fixes

### LINKED ISSUE #3661: Cookiecutter progress bar should not move the button when it shows up

### LINKED ISSUE #3707: Cookiecutter should respect create solution folder option in new project dialog
When using New project dialog with ML templates,, user can check create solution folder option but we ignore it.

Looking at the code it's trying to do something special in that scenario, we just need to not do that.

### PR DESCRIPTION
**Pull request by huguesv**
Fix #3707 Cookiecutter should respect create solution folder option in new project dialog
Fix #3661 Cookiecutter progress bar should not move the button when it shows up

image

(similar fix for the second page also included)

### CODE REVIEW

File: Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs [hunk 1]
```diff
@@ -273,9 +273,9 @@ class CookiecutterViewModel : INotifyPropertyChanged {
             _statusImageVisibility = image.HasValue && !progressVisible ? Visibility.Visible : Visibility.Collapsed;
             _spinningStatusImageVisibility = image.HasValue && progressVisible ? Visibility.Visible : Visibility.Collapsed;
             bool v = (visible ?? !string.IsNullOrEmpty(message));
-            _statusVisibility = v ? Visibility.Visible : Visibility.Collapsed;
-            _statusProgressVisibility = progressVisible ? Visibility.Visible : Visibility.Collapsed;
-            _statusUpdateProgressVisibility = updateProgressVisible ? Visibility.Visible : Visibility.Collapsed;
+            _statusVisibility = v ? Visibility.Visible : Visibility.Hidden;
```
Comment (AlexanderSher) [inline Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs]: Those are fields. WPF won't be notified about updated values.

Comment (huguesv) [reply Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs]: The PropertyChanged notifications are just a few lines below.
