### PR TITLE
Analysis fixes

### LINKED ISSUE #2968: Failed to create entry for file (unobserved exception)
I was browsing some code (adal for python) and got this.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An exception in a task was not observed. See ActivityLog.xml for more details.

System.AggregateException: A Task's exception(s) were not observed either by Waiting on the Task or accessing its Exception property. As a result, the unobserved exception was rethrown by the finalizer thread. ---> System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Failed to create entry for file

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 868

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at System.Threading.Tasks.Task`1.get_Result()

   at Microsoft.PythonTools.Navigation.PythonLibraryManager.<>c__DisplayClass3_0.<OnNewFile>b__0(Task`1 x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\PythonLibraryManager.cs:line 66

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

   --- End of inner exception stack trace ---

---> (Inner Exception #0) System.AggregateException: One or more errors occurred. ---> System.InvalidOperationException: Failed to create entry for file

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 868

   --- End of inner exception stack trace ---

   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)

   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)

   at System.Threading.Tasks.Task`1.get_Result()

   at Microsoft.PythonTools.Navigation.PythonLibraryManager.<>c__DisplayClass3_0.<OnNewFile>b__0(Task`1 x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\PythonLibraryManager.cs:line 66

   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()

   at System.Threading.Tasks.Task.Execute()

---> (Inner Exception #0) System.InvalidOperationException: Failed to create entry for file

   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<AnalyzeFileAsync>d__82.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 868<---

<---



   at Microsoft.PythonTools.PythonToolsPackage.<>c.<.ctor>b__3_0(Object sender, UnobservedTaskExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonToolsPackage.cs:line 202

   at System.Threading.Tasks.TaskScheduler.PublishUnobservedTaskException(Object sender, UnobservedTaskExceptionEventArgs ueea)

   at System.Threading.Tasks.TaskExceptionHolder.Finalize()


---------------------------
Abort   Retry   Ignore   
---------------------------
```

So no one handled this:
```
            if (response == null || response.fileId == -1) {
                Interlocked.Decrement(ref _parsePending);
                // TODO: Get SendRequestAsync to return more useful information
                throw new InvalidOperationException("Failed to create entry for file");
            }
```

### LINKED ISSUE #2976: Failed to get classifier from buffer (from TextViewFilter this time)
I have the latest fixes. I wasn't using multiple views, I just had a project with one file open, one package not opened, and I switched the active interpreter.

Got the activity log error message.

```

System.ArgumentException: Failed to get classifier from buffer at  
Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot  snapshot, ITextBuffer buffer, ITrackingSpan span) in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ReverseExpressionParser.cs:line  53 at Microsoft.PythonTools.Language.TextViewFilter.GetDataTipText(TextSpan[]  pSpan, String& pbstrText) in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\TextViewFilter.cs:line  119 at  
Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromFilter(IQuickInfoSession  session, TextSpan[] dataBufferTextSpan, String& tipText) at  
Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession  session, IList`1 qiContent, ITrackingSpan& applicableToSpan) at  
Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate()  at  
Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()  at  
Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object  sender, MouseHoverEventArgs e) at  
Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()  --- End of stack trace from previous location where exception was thrown --- at  
Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception  exceptionObject)
--



```

### LINKED ISSUE #2978: Unable to resolve package defined inside project
Create new Python application
Add New Item, Python Package
In `package1/__init__.py`:
```
MSG = 'hello'
```
In the startup file:
```
import package1
print(package1.MSG)
```
Close All Windows
Close Solution
Open Solution
Open the startup file only

Result:

The import cannot be resolved, and you can't go to definition on `package1` or `package1.MSG`

image

Workaround:

Open `package1/__init__.py` in the editor, and things will now work as normal.

### LINKED ISSUE #2982: Typing in a text file cause InvalidOperationException
Create new python application
Add new item, text file, requirements.txt
Try typing `requests`

You'll get asserts/unobserved exceptions on every keystrokes.

```
System.AggregateException occurred
  HResult=0x80131500
  Message=One or more errors occurred.
  Source=mscorlib
  StackTrace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at Microsoft.PythonTools.Navigation.PythonLibraryManager.<>c__DisplayClass3_0.<OnNewFile>b__0(Task`1 x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\PythonLibraryManager.cs:line 66
   at System.Threading.Tasks.ContinuationTaskFromResultTask`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

Inner Exception 1:
InvalidOperationException: Failed to create entry for file
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #2976 Failed to get classifier from buffer
Fixes #2978 Unable to resolve package defined inside project
Ensures that analyzer and filename are returned from GetAnalyzer even when the file has not yet been loaded.

Fixes #2968 Failed to create entry for file
Fixes #2982 Typing in a text file causes InvalidOperationException
Uses the shared AnalysisComplete event from the analyzer rather than hooking each file individually.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryManager.cs [hunk 1]
```diff
@@ -41,42 +45,122 @@ internal interface IPythonLibraryManager : ILibraryManager {
...
+                    Project.ProjectAnalyzerChanging -= Project_ProjectAnalyzerChanging;
+                    if (_analyzer != null) {
+                        _analyzer.AnalysisComplete -= Analyzer_AnalysisComplete;
                     }
-                });
+                }
+            }
+
+            private void Project_ProjectAnalyzerChanging(object sender, AnalyzerChangingEventArgs e) {
+                lock (this) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryManager.cs]: >this [](start = 22, length = 4)

I know it's a private class, all usage of it is nearby and it's unlikely that anyone outside the class will try to lock on an AnalysisCompleteHandler object from outside, but I'm still not a fan of lock(this).

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Navigation/PythonLibraryManager.cs]: Yeah, me neither, but it's an inner class instance so seemed better than allocating another new object just for locking the event handlers.
