### PR TITLE
Fixes #1638 Support PEP 530 syntax

### LINKED ISSUE #1638: Support PEP 530 syntax
[PEP 530](https://www.python.org/dev/peps/pep-0530/) adds async generator support, which means `async` can now show up in more places.

Currently we fail to parse this syntax and report valid code as an error.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1638 Support PEP 530 syntax
Adds parser support for "async for" in comprehension syntax
Add classifier support for "async" in comprehensions
Adds tests

### CODE REVIEW

File: Python/Product/Analysis/Parsing/Parser.cs [hunk 1]
```diff
@@ -4288,12 +4288,30 @@ struct Name {
...
         }
 
+        private bool PeekTokenForOrAsyncFor {
+            get {
+                return PeekToken(Tokens.KeywordForToken) ||
+                    (AllowAsyncAwaitSyntax && PeekToken(Tokens.KeywordAsyncToken) && PeekToken2()?.Kind == TokenKind.KeywordFor);
+            }
+        }
+
         // comp_for: 'for target_list 'in' or_test [comp_iter]
```
Comment (huguesv) [inline Python/Product/Analysis/Parsing/Parser.cs]: maybe update the comment to add [async]

**Comment by huguesv** [comment]
👍
