### PR TITLE
Fixes #4271 Failed to install Anaconda

### LINKED ISSUE #4271: Failed to install Anaconda
Anaconda may not install correctly if we do not explicitly wait for any running uninstalls to complete.

Add a helper process that will wait for previous uninstalls to complete and then launch the next one.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4271 Failed to install Anaconda
Adds installer launcher.

### CODE REVIEW

File: Python/Product/AnacondaInstallLauncher/Program.cs [hunk 1]
```diff
@@ -0,0 +1,212 @@
...
+
+        void WaitForProcess(DateTime stopAt, bool requireProcess) {
+            if (!KeepWaiting) {
+                return;
+            }
+
+            var procs = GetProcesses();
+            int retries = 30;
+            while (requireProcess && procs.Length == 0 && retries-- > 0) {
+                Thread.Sleep(1000);
```
Comment (heaths) [inline Python/Product/AnacondaInstallLauncher/Program.cs]: Why force context switching on the CPU every second when you could just wait on the process handle(s) (via `Process.WaitForExit`) like in the original example I provided?

File: Python/Product/AnacondaInstallLauncher/Program.cs [hunk 2]
```diff
@@ -0,0 +1,212 @@
...
+        }
+
+        Process[] GetProcesses() {
+            return Process.GetProcesses()
+                .Where(p => p.ProcessName.StartsWith("Un_") &&
+                    p.MainModule.FileVersionInfo.FileDescription.IndexOf("Anaconda", StringComparison.OrdinalIgnoreCase) >= 0)
+                .ToArray();
+        }
+
+        void WaitForProcess(DateTime stopAt, bool requireProcess) {
```
Comment (heaths) [inline Python/Product/AnacondaInstallLauncher/Program.cs]: Why timeout? If you use the process handle (via `Process.WaitForExit`), this is an intrinsic wait handle (in the underlying native implementation). It will signal when the process terminates. If you merely timeout, the original problem of the race condition between the async uninstaller and sync installer will happen as well.

If you really feel it necessary to timeout (and with how much machines vary in performance, especially under additional workload, I don't recommend it), at least fail method and forego running the installer. Return an exit code so other chainers (like Visual Studio) can tell the user something failed and to repair.

File: Python/Product/AnacondaInstallLauncher/Program.cs (hunk 1 above)
Comment (zooba) [reply Python/Product/AnacondaInstallLauncher/Program.cs]: Because we're also checking the file system, and file system watchers are notoriously unreliable so I'd rather not use one just to avoid looping. This is not going to be the most CPU intensive operation while it's running (Windows Defender takes that prize...)

File: Python/Product/AnacondaInstallLauncher/Program.cs (hunk 2 above)
Comment (zooba) [reply Python/Product/AnacondaInstallLauncher/Program.cs]: Yeah, fair enough. I'll lose the timeout.

File: Python/Product/AnacondaInstallLauncher/Program.cs (hunk 1 above)
Comment (heaths) [reply Python/Product/AnacondaInstallLauncher/Program.cs]: You're not checking the file system in this loop. Waiting on the process handles then checking the file system would be less intensive.

File: Python/Product/AnacondaInstallLauncher/Program.cs [hunk 3]
```diff
@@ -0,0 +1,192 @@
...
+            return p;
+        }
+
+        int DoInstall() {
+            WaitForUninstall(false);
+            if (_cancel) {
+                return ERROR_INSTALL_CANCEL;
+            }
+
+            var p = Run(_installer, string.Format(CultureInfo.InvariantCulture, "/InstallationType=AllUsers /RegisterPython=0 /S /D={0}", _targetDir));
```
Comment (huguesv) [inline Python/Product/AnacondaInstallLauncher/Program.cs]: _targetDir probably needs to be quoted?

Comment (zooba) [reply Python/Product/AnacondaInstallLauncher/Program.cs]: No. Anaconda installer is weird here - it must be last on the command line and it must be unquoted.

File: Python/Product/AnacondaInstallLauncher/Program.cs [hunk 4]
```diff
@@ -0,0 +1,192 @@
...
+            try {
+                WaitForProcess(requireWait);
+            } catch (Exception ex) {
+                Console.Error.WriteLine(ex.ToString());
+            }
+        }
+
+        bool IsDirectoryPresent() {
+            if (!Directory.Exists(_targetDir)) {
+                Console.Error.WriteLine("Target directory is not present");
```
Comment (huguesv) [inline Python/Product/AnacondaInstallLauncher/Program.cs]: Might be useful to print `_targetDir` at the end of all these messages

File: Python/Product/AnacondaInstallLauncher/Program.cs (hunk 3 above)
Comment (huguesv) [reply Python/Product/AnacondaInstallLauncher/Program.cs]: Please put that as a comment

File: Python/Product/AnacondaInstallLauncher/Program.cs (hunk 4 above)
Comment (zooba) [reply Python/Product/AnacondaInstallLauncher/Program.cs]: It'll be followed up immediately by the log message for launching the installer, and it'll be in the log for starting this process too. I don't think it needs repeating much more than that.

File: Python/Product/AnacondaInstallLauncher/Program.cs [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+                Console.Error.WriteLine(ex.ToString());
+                return false;
+            }
+
+            return true;
+        }
+
+        Process[] GetProcesses() {
+            return Process.GetProcesses()
+                .Where(p => p.ProcessName.StartsWith("Un_") &&
```
Comment (huguesv) [inline Python/Product/AnacondaInstallLauncher/Program.cs]: According to the docs at https://msdn.microsoft.com/en-us/library/system.diagnostics.process.processname(v=vs.110).aspx, ProcessName property may throw `InvalidOperationException` if process has exited. Given that we're looking at all processes on the machine, it could happen that a process exits between the call to `GetProcesses` and `ProcessName`.

We print `ProcessName` in `WaitForProcess` as well.

**Comment by MikhailArkhipov** [comment]
LGTM
