### PR TITLE
Improve support for relative imports + bug fixes

### LINKED ISSUE #949: Intellisense is broken in the presence of relative imports
If you type this:

`from . import foo`

PTVS doesn't seem to understand this syntax.  After you write the `.` (note the space) you get an intellisense popup suggesting module names, so as you continue typing `import` it selects `importlib` and you end up with 

`from . importlib foo`

The modules that its suggesting in this intellisense popup are not located in the specified directory either it just seems to be all the modules in the search paths.  So I think PTVS simply has no concept of relative imports.

If you actually go and type out a valid relative import, it _is_ able to resolve it.  So something like

`from ..foo import bar`

if it is a valid module, you will have working intellisense on bar and no squigglies.  The problem seems to be isolated only to the case of typing the import statement.

### LINKED ISSUE #4138: No completion in namespace packages
```
.
├── projecta
│   └── foo
│       ├── bar
│       │   └── __init__.py
│       └── __init__.py
└── projectb
    └── foo
        ├── baz
        │   └── __init__.py
        └── __init__.py
```

test.py:
```
import projectA.foo
import projectA.foo.bar
import projectB.foo
import projectB.foo.baz

projectA.
```
image

Jedi:
image

PyCharm:
image

### LINKED ISSUE #4299: Deleted variables linger in analysis
Declare `p=1`
Observe `p.` gives completion for `int`.
Delete line with `p=1`
Type `p.`

image

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #949
- Adds support for `from . import a, b, c`.
- Fixes issues with `from .a import b,c.`
- Hovering over `abc` in `from x import abc` gives information on the `abc`.

### CODE REVIEW

File: Python/Product/Analysis/ModulePath.cs [hunk 1]
```diff
@@ -664,17 +660,21 @@ out errorParameter
         internal static bool FromBasePathAndName_NoThrow(
             string basePath,
             string moduleName,
+            PythonLanguageVersion? languageVersion,
```
Comment (zooba) [inline Python/Product/Analysis/ModulePath.cs]: I think this makes more sense as a bool that says `requiresInitPyFiles`. That avoids encoding too much version-specific logic right here and moves it out to the caller (especially relevant for when we hit particular cases where the requirement is interesting and the version is unknown/irrelevant - it's much more clear why `true` is selected than `V33`).

File: Python/Product/Analysis/ModuleResolver.cs [hunk 2]
```diff
@@ -0,0 +1,206 @@
...
+        /// such as 'from . import a, b, c' or 'from .a import b, c'
+        /// </summary>
+        /// <param name="entry">Project entry</param>
+        /// <param name="node">Import statement node</param>
+        /// <returns>Names of modules</returns>
+        internal static IEnumerable<string> ResolveRelativeFromImport(IPythonProjectEntry entry, FromImportStatement node)
+            => ResolveRelativeFromImport(entry.ModuleName, entry.FilePath, node);
+
+        /// <summary>
+        /// Resolves modules listed in the relative import statetement
```
Comment (zooba) [inline Python/Product/Analysis/ModuleResolver.cs]: "statement"

File: Python/Product/Analysis/ModuleResolver.cs [hunk 3]
```diff
@@ -0,0 +1,206 @@
...
+        /// </summary>
+        /// <param name="importingFromModuleName">Name of the importing module</param>
+        /// <param name="importingFromFilePath">Disk path to the importing module</param>
+        /// <param name="node">Import statement node</param>
+        /// <returns></returns>
+        internal static IEnumerable<string> ResolveRelativeFromImport(string importingFromModuleName, string importingFromFilePath, FromImportStatement node) {
+            var root = node.Root.MakeString();
+
+            if (!string.IsNullOrEmpty(root) && root.StartsWith(".")) {
+                var prefix = root.All(c => c == '.') ? root : $"{root}.";
```
Comment (zooba) [inline Python/Product/Analysis/ModuleResolver.cs]: `$` (culture-sensitive formatting) should not be used in this context - use `"{0}.".FormatInvariant(root)` instead

File: Python/Product/Analysis/ModuleResolver.cs [hunk 4]
```diff
@@ -0,0 +1,206 @@
...
+        private static string GetModuleFullName(string originatingModule, string relativePath) {
+            // Check if it is indeed relative
+            if (string.IsNullOrEmpty(relativePath) || relativePath[0] != '.') {
+                return relativePath;
+            }
+
+            var up = relativePath.TakeWhile(ch => ch == '.').Count();
+            var bits = originatingModule.Split('.');
+            if (up > bits.Length) {
+                return relativePath; // too far up
```
Comment (zooba) [inline Python/Product/Analysis/ModuleResolver.cs]: We should probably return `null` here to indicate that there's nothing to import

File: Python/Product/Analysis/ModuleResolver.cs [hunk 5]
```diff
@@ -0,0 +1,206 @@
...
+        /// </summary>
+        /// <param name="entry">Project entry</param>
+        /// <param name="node">Import statement node</param>
+        /// <returns>Names of modules</returns>
+        internal static IEnumerable<string> GetModuleNamesFromImport(IPythonProjectEntry entry, FromImportStatement node)
+            => GetModuleNamesFromImport(entry.ModuleName, entry.FilePath, node);
+
+        /// <summary>
+        /// Extracts actual module names from the 'from import' statetement
+        /// such as [a, b, c] from 'from . import a, b, c' or [a] from 'from .a import b, c'
```
Comment (zooba) [inline Python/Product/Analysis/ModuleResolver.cs]: These seem like inconsistent results. Given the first example, I'd expect `a.b, a.c` from the second, and it's not clear how this relates to the module it's being imported from (really, I'd expect `importingFromModuleName.a, ...` in the results)

File: Python/Product/Analysis/ProjectEntry.cs [hunk 6]
```diff
@@ -56,8 +56,11 @@ IAnalysisCookie cookie
             DocumentUri = documentUri ?? MakeDocumentUri(filePath);
             FilePath = filePath;
             Cookie = cookie;
+
             MyScope = new ModuleInfo(ModuleName, this, state.Interpreter.CreateModuleContext());
             _unit = new AnalysisUnit(null, MyScope.Scope);
+            Analysis = new ModuleAnalysis(_unit, ((ModuleScope)_unit.Scope));
```
Comment (zooba) [inline Python/Product/Analysis/ProjectEntry.cs]: Is this why you're ending up with the unit with null Ast? Aren't we checking that `Analysis` isn't null everywhere already?

File: Python/Product/Analysis/PythonAnalyzer.cs [hunk 7]
```diff
@@ -344,133 +344,14 @@ public partial class PythonAnalyzer : IGroupableAnalysisProject, IDisposable {
...
-                    var adjacentModuleName = string.Join(".", prefix.Take(prefix.Length - 1)) + "." + relativeModuleName;
-                    yield return adjacentModuleName;
-                }
-            }
-
-            // Without absolute_import, we treat the name as complete last.
-            if (!absoluteImports) {
-                yield return relativeModuleName;
+            var unresolved = importFrom.GetModuleInfo().GetAllUnresolvedModules();
+            if(unresolved.Count == 0) {
```
Comment (zooba) [inline Python/Product/Analysis/PythonAnalyzer.cs]: Minor spacing issues all over the place - suggest Ctrl+K, Ctrl+D everywhere before merging (and check that it hasn't broken anything when you do that).

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 8]
```diff
@@ -6804,16 +6805,18 @@ class Y:
...
-                new { Code="from .deg import A", Index=9, Expected="abc.deg", Base="abc" },
-                new { Code="from .hij import A", Index=9, Expected="abc.deg.hij", Base="abc.deg" },
-                new { Code="from ..hij import A", Index=10, Expected="abc.hij", Base="abc.deg" },
-                new { Code="from ..hij import A", Index=10, Expected="abc.deg.hij", Base="abc.deg.HIJ" },
+                new { Code="from .deg import A", Index=9, Expected="deg.A", Base="abc" },
+                new { Code="from .hij import A", Index=9, Expected="abc.hij.A", Base="abc.deg" },
+                new { Code="from ..hij import A", Index=10, Expected="hij.A", Base="abc.deg" },
+                new { Code="from ..hij import A", Index=10, Expected="abc.hij.A", Base="abc.deg.HIJ" },
+                new { Code="from .. import deg", Index=10, Expected="deg", Base="abc.deg" },
+                new { Code="from . import A", Index=10, Expected="abc.A", Base="abc.deg" },
```
Comment (zooba) [inline Python/Tests/Analysis/AnalysisTest.cs]: These tests are all incorrect now - you're dropping too many levels when processing the leading `.`.

I suggest creating these packages and testing everything to prove to yourself that Python treats `.` as "current package" in all cases. Use `print(__name__)` to see the order they get imported in.

**Comment by zooba** [comment]
And just to plant the idea - please squash merge this PR. There are a lot of commits here, and they don't all seem to be related

File: Python/Product/Analysis/AnalysisUnit.cs [hunk 9]
```diff
@@ -164,30 +164,26 @@ internal AnalysisUnit(ScopeStatement ast, InterpreterScope scope)
         internal virtual void AnalyzeWorker(DDG ddg, CancellationToken cancel) {
             DeclaringModule.Scope.ClearLinkedVariables();
 
+            // Remove stale variables
+            var toRemove = DeclaringModule.Scope.AllVariables
+                .Where(v => !v.Value.VariableStillExists && !v.Value.IsAssigned).ToList();
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/AnalysisUnit.cs]: After the walk stale variable receives types and `VariableStillExists` becomes true again. So attempt here is to remember what was dead before the walk. However, I can try and chase why it receives types and prevent it there.

File: Python/Product/Analysis/Analyzer/DDG.cs [hunk 10]
```diff
@@ -343,60 +345,76 @@ internal class DDG : PythonWalker {
                     }
                 } else {
                     userMod.Imported(_unit);
-                    fullImpName[fullImpName.Length - 1] = impName;
-                    AssignImportedMember(nameNode, userMod, fullImpName, newName ?? impName);
+                    var modName = node.Root.MakeString();
+                    if (modRef.Name != modName) {
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/Analyzer/DDG.cs]: I'll double check. The issue was with `from .a import x.y` where bits were not empty.

File: Python/Product/Analysis/Analyzer/DDG.cs [hunk 11]
```diff
@@ -343,60 +345,76 @@ internal class DDG : PythonWalker {
...
+                            resolved(moduleRef, remainingParts);
+                         } else {
+                            resolved(moduleRef, null);
                         }
-                        return true;
-                    } else {
-                        break;
+                        continue;
                     }
+                    unresolved(name);
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/Analyzer/DDG.cs]: OK, makes sense

File: Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs [hunk 12]
```diff
@@ -453,7 +453,9 @@ TryImportModuleContext context
                 return TryImportModuleResult.ModuleNotFound;
             }
 
-            Debug.Assert(!name.EndsWithOrdinal("."), $"{name} should not end with '.'");
+            if(name.EndsWithOrdinal(".")) { // Incomplete construct
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/Interpreter/Ast/AstPythonInterpreterFactory.cs]: Let me see if I can repro this on partial construct and check where is it coming from.

File: Python/Product/Analysis/LanguageServer/Server.cs [hunk 13]
```diff
@@ -119,10 +120,14 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
 
         #region Client message handling
         public override async Task<InitializeResult> Initialize(InitializeParams @params) {
+            //while (!System.Diagnostics.Debugger.IsAttached) {
+            //    System.Threading.Thread.Sleep(1000);
+            //}
+
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/LanguageServer/Server.cs]: OK. Comes useful occasionally.

File: Python/Product/Analysis/LanguageServer/Server.cs [hunk 14]
```diff
@@ -474,6 +479,8 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
                 _analyzer.AddModuleAlias(first, a);
             }
 
+            AddParentModules(first, path);
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/LanguageServer/Server.cs]: Yes, I can add comments. The issue and project structure is here https://github.com/Microsoft/PTVS/issues/4138. Folders up the tree don't have `__init__.py` and we miss them.

File: Python/Product/Analysis/LanguageServer/Server.cs [hunk 15]
```diff
@@ -495,6 +502,45 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
 
             return Task.FromResult(item);
         }
+        private void AddParentModules(string module, string path) {
+            if (ModulePath.PythonVersionRequiresInitPyFiles(_analyzer.LanguageVersion) ||
+                string.IsNullOrEmpty(_rootDir)) {
+                return;
+            }
+
+            var dir = Path.GetDirectoryName(path);
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/LanguageServer/Server.cs]: Do we care if path is not valid? I.e. is there a case path with invalid characters or form is useful still?

File: Python/Product/Analysis/LanguageServer/Server.cs [hunk 16]
```diff
@@ -495,6 +502,45 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
...
+                        _analyzer.Modules.TryImport(parentModName, out parentModRef);
+
+                        if (_analyzer.Modules.TryImport(module, out var modRef)) {
+                            parentModRef.AddReference(modRef.AnalysisModule as ModuleInfo);
+                            modRef.AddReference(parentModRef.AnalysisModule as ModuleInfo);
+
+                            entry.GetModuleInfo().AddModuleReference(modRef);
+
+                            var varName = module.Substring(parentModName.Length + 1);
+                            var v = entry.Analysis.Scope.AddVariable(varName, new LocatedVariableDef(entry, new EncodedLocation()));
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/LanguageServer/Server.cs]: OK. I thought it might be useful to know if the variable is actually fake

File: Python/Product/Analysis/ModulePath.cs (hunk 1 above)
Comment (MikhailArkhipov) [reply Python/Product/Analysis/ModulePath.cs]: OK

File: Python/Product/Analysis/LanguageServer/Server.cs (hunk 16 above)
[the remark this answers is not in the document]
Comment (zooba) [reply Python/Product/Analysis/LanguageServer/Server.cs]: We probably need a new property on VariableDef (or a new subclass) to tell if it's fake. `EphemeralVariableDef` might be the right one for this, but I think we also exclude those from results in certain places so perhaps not...

File: Python/Product/Analysis/LanguageServer/Server.cs (hunk 15 above)
[the remark this answers is not in the document]
Comment (zooba) [reply Python/Product/Analysis/LanguageServer/Server.cs]: We care because it raises an exception that you aren't handling :) `GetParent` won't raise until we try and use the path for actual I/O, where we'll be handling those exceptions anyway.

File: Python/Product/Analysis/LanguageServer/Server.cs (hunk 14 above)
[the remark this answers is not in the document]
Comment (zooba) [reply Python/Product/Analysis/LanguageServer/Server.cs]: Namespace packages should be resolved downwards from our search paths. We can't just resolve them upwards or we'll never know where to stop generating package names.

We can assume the root of the workspace is a search path (and we should already have that information available). Otherwise, the IDE should provide any other search paths explicitly.

File: Python/Product/Analysis/Analyzer/DDG.cs [hunk 17]
```diff
@@ -343,60 +345,76 @@ internal class DDG : PythonWalker {
...
+
+                ModuleReference moduleRef = null;
                 foreach (var part in ModulePath.GetParents(name, includeFullName: true)) {
                     if (ProjectState.Modules.TryImport(part, out var mref)) {
+                        // First part is module
                         moduleRef = mref;
                         if (part.Length < name.Length) {
                             moduleRef.Module?.Imported(_unit);
+                        } else {
+                            resolved(moduleRef, null);
```
[the remark this answers is not in the document]
Comment (zooba) [reply Python/Product/Analysis/Analyzer/DDG.cs]: `resolved` doesn't resolve it, it assigns it. Python will only ever import one module, so we should resolve the best single module using the available information and assign that (e.g. we have Python runtime version, search paths, ability to read the disk/open ZIP files, etc.)

**Comment by zooba** [comment]
Added a few replies, hope they aren't too hard to find in github's UI. Will take another full look tomorrow (between meetings...)

File: Python/Product/Analysis/ModulePath.cs [hunk 18]
```diff
@@ -664,17 +659,21 @@ out errorParameter
...
             out ModulePath modulePath
         ) {
-            return FromBasePathAndName_NoThrow(basePath, moduleName, null, null, out modulePath, out _, out _, out _);
+            var isPackage = languageVersion.HasValue && PythonVersionRequiresInitPyFiles(languageVersion.Value) ? (Func<string, bool>)null : s => true;
```
Comment (zooba) [inline Python/Product/Analysis/ModulePath.cs]: For least surprise, we should assume that `__init__.py` files are required if we don't know the language version. (That's the recommended way to create packages, and it works in all versions, whereas implicit namespace packages only work in recent versions and are only recommended for certain cases.)

File: Python/Product/Analysis/ModuleResolver.cs [hunk 19]
```diff
@@ -0,0 +1,208 @@
...
+
+                var names = node.Names.Where(n => !string.IsNullOrEmpty(n.Name)).Select(n => n.Name);
+                if (!names.Any()) {
+                    return Enumerable.Empty<string>();
+                }
+
+                var resolved = names.SelectMany(n => ResolvePotentialModuleNames(
+                        importingFromModuleName, importingFromFilePath,
+                        "{0}{1}".FormatInvariant(prefix, n), node.ForceAbsolute)).ToArray();
+                if (resolved.Length == 1 && resolved[0].Length > 2 && resolved[0].EndsWithOrdinal(".*")) {
```
Comment (zooba) [inline Python/Product/Analysis/ModuleResolver.cs]: Let's check for `import *` first, and then `ResolvePotentialModuleNames` can be more strict about only returning actual importable names (i.e. `my-module.name` is not importable, so it isn't a potential module name, so we could filter it out in that function - this would probably also help deal with that case where we're passing `..a.` as a "valid" name to `ImportModule`).

File: Python/Product/Analysis/ModuleResolver.cs [hunk 20]
```diff
@@ -0,0 +1,208 @@
...
+            if (up > bits.Length) {
+                return relativePath; // too far up
+            }
+
+            var root = string.Join(".", bits.Take(bits.Length - up));
+            var subPath = relativePath.Trim('.');
+
+            return string.IsNullOrEmpty(root)
+                ? subPath
+                : string.IsNullOrEmpty(subPath) ? root : $"{root}.{subPath}";
```
Comment (zooba) [inline Python/Product/Analysis/ModuleResolver.cs]: Use concatentation or `FormatInvariant` here

File: Python/Product/Analysis/PythonAnalyzer.cs [hunk 21]
```diff
@@ -356,133 +356,14 @@ public partial class PythonAnalyzer : IGroupableAnalysisProject, IDisposable {
...
-                if (prefix.Length > 1) {
-                    var adjacentModuleName = string.Join(".", prefix.Take(prefix.Length - 1)) + "." + relativeModuleName;
-                    yield return adjacentModuleName;
-                }
-            }
-
-            // Without absolute_import, we treat the name as complete last.
-            if (!absoluteImports) {
-                yield return relativeModuleName;
+            var unresolved = importFrom.GetModuleInfo().GetAllUnresolvedModules();
```
Comment (zooba) [inline Python/Product/Analysis/PythonAnalyzer.cs]: `GetModuleInfo()` may return `null`

File: Python/Product/Analysis/Values/FunctionInfo.cs [hunk 22]
```diff
@@ -115,9 +115,11 @@ internal class FunctionInfo : AnalysisValue, IReferenceableContainer, IHasRichDe
                     calledUnit.Enqueue();
                 }
 
-                res.Split(v => v.IsResolvable(), out _, out var nonLazy);
-                res = DoCall(node, unit, calledUnit, callArgs);
-                res = res.Union(nonLazy);
+                if (calledUnit != null) {
```
Comment (zooba) [inline Python/Product/Analysis/Values/FunctionInfo.cs]: If we don't have a specific called unit here, we should get res from `_analysisUnit.ReturnValue.Types` (which should have the union of all possible return types for this function).

Comment (zooba) [reply Python/Product/Analysis/Values/FunctionInfo.cs]: It's probably easiest to make `DoCall` handle a null calledUnit. We can also assert `calledUnit != null || callingUnit.ForEval` in there, since we should never end up in a situation where we are still analyzing but get a null `calledUnit`.

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs [hunk 23]
```diff
@@ -993,9 +993,11 @@ class ImportStatementWalker : PythonWalker {
...
 
             public override bool Walk(FromImportStatement node) {
-                var name = node.Root.MakeString();
-                if (!_analyzer.IsModuleResolved(_entry, name, node.ForceAbsolute)) {
-                    Imports.Add(MakeUnresolvedImport(name, node.Root));
+                var names = ModuleResolver.GetModuleNamesFromImport(_entry, node);
+                foreach (var n in names) {
+                    if (!_analyzer.IsModuleResolved(_entry, n, node.ForceAbsolute)) {
+                        Imports.Add(MakeUnresolvedImport(n, node.Root));
+                    }
```
Comment (zooba) [inline Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: We should only add the unresolved import if none of the names are resolved. Otherwise we will warn everywhere that we generate multiple names for the same module, even when the "obvious" one is there.

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 24]
```diff
@@ -6807,16 +6808,18 @@ class Y:
...
             }) {
                 var entry = ProcessTextV3(item.Code);
-                var walker = new ImportedModuleNameWalker(item.Base, item.Index);
+                var walker = new ImportedModuleNameWalker(item.Base, string.Empty, item.Index);
                 entry.Modules[entry.DefaultModule].Tree.Walk(walker);
 
-                Assert.AreEqual(item.Expected, walker.ImportedName);
+                Assert.AreEqual(item.Expected, walker.ImportedModules.First());
```
Comment (zooba) [inline Python/Tests/Analysis/AnalysisTest.cs]: We should validate the rest of the suggested names too.

Comment (MikhailArkhipov) [reply Python/Tests/Analysis/AnalysisTest.cs]: I added PEP328 test

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs (hunk 23 above)
Comment (MikhailArkhipov) [reply Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: This is to handle `from . import a, b, c` where only `a` is actually resolved. However, it can be limited to `.` case since in other cases it may not be necessary.

File: Python/Product/Analysis/Values/FunctionInfo.cs (hunk 22 above)
Comment (MikhailArkhipov) [reply Python/Product/Analysis/Values/FunctionInfo.cs]: I got null ref here since condition above does not guarantee it to be non-null (i.e. .ForEval case)

File: Python/Product/Analysis/Analyzer/DDG.cs (hunk 17 above)
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/Analyzer/DDG.cs]: Fixed

File: Python/Product/Analysis/Values/FunctionInfo.cs (hunk 22 above)
Comment (MikhailArkhipov) [reply Python/Product/Analysis/Values/FunctionInfo.cs]: Perhaps it is better to add `|| calledUnit == null` to the `if` above

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs (hunk 23 above)
Comment (MikhailArkhipov) [reply Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: So I guess we can add all names if import is from `.` or similar and keep old approach for other cases?

Comment (MikhailArkhipov) [reply Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: Actually, implementation of `IsModuleResolved` has changed - it no longer does TryImport so it won't report 'unresolved' entries. It only reports those that were not found at all and reported via 'unresolved' in TryImportModules. So here it only adds those names that appears in `GetModuleInfo()?.GetAllUnresolvedModules()`

File: Python/Product/Analysis/ProjectEntry.cs (hunk 6 above)
Comment (zooba) [reply Python/Product/Analysis/ProjectEntry.cs]: Right, but that `_unit` would normally never have ended up in `Analysis`, which means `FindScope` would not have been called on it. The change here is what causes that, so I'm wondering why we want this change if it breaks things and we're checking for null `Analysis` already?

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs (hunk 23 above)
Comment (zooba) [reply Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: In any case, this is going to change fairly soon to report via diagnostics rather than being a request from VS.

File: Python/Tests/Analysis/AnalysisTest.cs (hunk 8 above)
Comment (zooba) [reply Python/Tests/Analysis/AnalysisTest.cs]: Ah, you're right. I was assuming (and testing) in the `__init__.py` files in the package, but those will always include `__init__` as the last part of the module name and so the logic still checks out.

Thanks for fixing my error here!

File: Python/Product/Analysis/AnalysisUnit.cs [hunk 25]
```diff
@@ -162,30 +162,28 @@ internal AnalysisUnit(ScopeStatement ast, InterpreterScope scope)
         }
 
         internal virtual void AnalyzeWorker(DDG ddg, CancellationToken cancel) {
+            DeclaringModule.Scope.ClearLinkedVariables();
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/AnalysisUnit.cs]: Looks like merge issue, took it out

File: Python/Product/Analysis/AnalysisUnit.cs [hunk 26]
```diff
@@ -162,30 +162,28 @@ internal AnalysisUnit(ScopeStatement ast, InterpreterScope scope)
...
-            List<KeyValuePair<string, VariableDef>> toRemove = null;
-
             foreach (var variableInfo in DeclaringModule.Scope.AllVariables) {
                 variableInfo.Value.ClearOldValues(ProjectEntry);
-                if (variableInfo.Value._dependencies.Count == 0 &&
-                    !variableInfo.Value.HasTypes) {
-                    if (toRemove == null) {
-                        toRemove = new List<KeyValuePair<string, VariableDef>>();
-                    }
+                if (variableInfo.Value._dependencies.Count == 0 && !variableInfo.Value.HasTypes) {
```
[the remark this answers is not in the document]
Comment (MikhailArkhipov) [reply Python/Product/Analysis/AnalysisUnit.cs]: OK

File: Python/Product/Analysis/ProjectEntry.cs (hunk 6 above)
Comment (MikhailArkhipov) [reply Python/Product/Analysis/ProjectEntry.cs]: This was for #4138 which we took out.

**Comment by zooba** [comment]
@MikhailArkhipov Remember to squash merge, but I'd like to get this in before building today
