### PR TITLE
Prevent ArgumentNullException unexpected error in CPythonCondaPackageManagerProvider

### LINKED ISSUE #4163: ArgumentNullException from CPythonCondaPackageManagerProvider.GetPackageManagers
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.8.18116.3

System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.PythonTools.Interpreter.CPythonCondaPackageManagerProvider.<GetPackageManagers>d__3.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__17`2.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.GetPackageManagers(IPythonInterpreterFactory factory)
   at Microsoft.PythonTools.Project.PythonProjectNode.ProcessRequirementsTxt(IntPtr variantIn, IntPtr variantOut, UInt32 commandExecOpt)
   at Microsoft.PythonTools.Project.PythonProjectNode.ExecCommandIndependentOfSelection(Guid cmdGroup, UInt32 cmdId, UInt32 cmdExecOpt, IntPtr vaIn, IntPtr vaOut, CommandOrigin commandOrigin, Boolean& handled)
   at Microsoft.VisualStudioTools.Project.ProjectNode.InternalExecCommand(Guid cmdGroup, UInt32 cmdId, UInt32 cmdExecOpt, IntPtr vaIn, IntPtr vaOut, CommandOrigin commandOrigin)
   at Microsoft.VisualStudioTools.Project.ProjectNode.Exec(Guid& guidCmdGroup, UInt32 nCmdId, UInt32 nCmdExecOpt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.VisualStudioTools.Project.Automation.OAProject.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.ProjectWizards.InstallRequirementsWizard.InstallProjectRequirements(Project project, String requirementsTxt)
   at Microsoft.PythonTools.ProjectWizards.InstallRequirementsWizard.ProjectFinishedGenerating(Project project)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
```

We should `yield break` if `factory.Configuration.PrefixPath` is `null`.
It's possible for it to be `null` in the case of `NotFoundInterpreterFactory`.

                if (!Directory.Exists(Path.Combine(factory.Configuration.PrefixPath, "conda-meta"))) {
                    yield break;
                }

### PR DESCRIPTION
**Pull request by huguesv**
Fix #4163

### CODE REVIEW

File: Python/Product/VSInterpreters/PackageManager/CPythonCondaPackageManagerProvider.cs [hunk 1]
```diff
@@ -38,7 +38,8 @@ sealed class CPythonCondaPackageManagerProvider : IPackageManagerProvider {
 
         public IEnumerable<IPackageManager> GetPackageManagers(IPythonInterpreterFactory factory) {
             if (ExperimentalOptions.UseCondaPackageManager) {
-                if (!Directory.Exists(Path.Combine(factory.Configuration.PrefixPath, "conda-meta"))) {
+                if (string.IsNullOrEmpty(factory.Configuration.PrefixPath) ||
```
Comment (AlexanderSher) [inline Python/Product/VSInterpreters/PackageManager/CPythonCondaPackageManagerProvider.cs]: You can extract `factory.Configuration.PrefixPath` into variable - it is used in several places below.

Comment (huguesv) [reply Python/Product/VSInterpreters/PackageManager/CPythonCondaPackageManagerProvider.cs]: sure
