### PR TITLE
fixes #62 Crash collapsing region block

### LINKED ISSUE #62: Crash collapsing #region block
Keep getting this crash when collapsing a region block:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.ArgumentOutOfRangeException
Stack:
   at Microsoft.VisualStudio.Text.SnapshotSpan..ctor(Microsoft.VisualStudio.Text.SnapshotPoint, Int32)
   at Microsoft.VisualStudio.Text.Editor.Implementation.CollapsedAdornmentAutomationAdapter.GetNameCore()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.Automation.Peers.AutomationPeer.UpdateSubtree()
   at System.Windows.ContextLayoutManager.fireAutomationEvents()
   at System.Windows.ContextLayoutManager.UpdateLayout()
   at System.Windows.ContextLayoutManager.UpdateLayoutCallback(System.Object)
   at System.Windows.Media.MediaContext+InvokeOnRenderCallback.DoWork()
   at System.Windows.Media.MediaContext.FireInvokeOnRenderCallbacks()
   at System.Windows.Media.MediaContext.RenderMessageHandlerCore(System.Object)
   at System.Windows.Media.MediaContext.RenderMessageHandler(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### PR DESCRIPTION
**Pull request by crwilcox**
We spoke with the VS Team and it seems splitting collapsed regions
between \r\n can be a bit fragile. Code has been added to handle this
and our test cases have been edited to account for the adjustment.

### CODE REVIEW

**Comment by int19h** [comment]
:+1:

File: Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs [hunk 1]
```diff
@@ -199,6 +199,14 @@ internal class OutliningTagger : ITagger<IOutliningRegionTag> {
                 int cnt = 0;
                 var text = snapshot.GetText(start, length);
 
+                // The VS Provider is fragile to us splitting in between \r\n.  
+                // Check here that we haven't done that and correct the error.
+                if (text[0] == '\n' && start >= 1 && snapshot.GetText(start - 1, 1) == "\r") {
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: But how did we get here in the first place? We must have an off-by-one error somewhere (as shown when you change a file to \n only and now regions are off by one line)

Comment (crwilcox) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: So the issue is that I advance by one extra to account for ':' in class so it was visible.

1) do this
2) fix an issue with class defs where the ':' is not included on the first line.

This is kind of a patchwork job though so I will fix the root issue. I will remove our offset and fix the class issue.  Update coming.

File: Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs [hunk 2]
```diff
@@ -323,7 +322,7 @@ class OutliningWalker : PythonWalker {
             }
 
             public override bool Walk(ClassDefinition node) {
-                AddTagIfNecessary(node, node.HeaderIndex, node.Decorators);
+                AddTagIfNecessary(node, node.HeaderIndex + 1, node.Decorators);
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: Is HeaderIndex inconsistent between ClassDef and FunctionDef? Or does FunctionDef already add 1?

Comment (crwilcox) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: Yes.  FunctionDef it works fine.   For ClassDef, Headerindex points to the end of the class def and not the ':'  so if we collapse we also collapse the ':' into the '...' that displays for the collapsed region.  There is definitely a non zero chance the header index is set incorrectly on classdef and I am compensating here.  If you want I could make a bug to chase that down and remove this + 1.

Comment (zooba) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: I'll merge this fix, but go ahead and make that issue. It's probably too risky to mess with the AST at this stage, but after 2.2 it'll be fine.
