### PR TITLE
Fixes #1953 Tests are not shown on VS 2017

### LINKED ISSUE #1953: Tests are not shown on VS 2017
Opening the Azure SDK for Python project, after migration, analysis, several open/close of VS, still does not see my tests.

Microsoft Visual Studio Enterprise 2017 RC
Version 15.0.26006.2 D15REL
Microsoft .NET Framework
Version 4.6.01586

Installed Version: Enterprise

Visual Basic 2017 RC   00369-50000-00000-AA399
Microsoft Visual Basic 2017 RC

Visual C# 2017 RC   00369-50000-00000-AA399
Microsoft Visual C# 2017 RC

Application Insights Tools for Visual Studio Package   8.4.01118.2
Application Insights Tools for Visual Studio

ASP.NET and Web Tools 2016   15.0.21206.0
ASP.NET and Web Tools 2016

ASP.NET Web Frameworks and Tools 2013   5.2.41123.0
For additional information, visit https://www.asp.net/

Azure App Service Tools v2.9.6   15.0.21130.0
Azure App Service Tools v2.9.6

Common Azure Tools   1.8
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

JavaScript Language Service   2.0
JavaScript Language Service

Microsoft Azure Tools   2.9
Microsoft Azure Tools for Microsoft Visual Studio vNext - v2.9.41121.2

NuGet Package Manager   4.0.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

Python Tools for Visual Studio   3.0.16334.1
Python Tools for Visual Studio provides IntelliSense, projects, templates, Interactive windows, and other support for Python developers.

Python Tools for Visual Studio - Cookiecutter Integration   3.0.16334.1
Provides cookiecutter integration.

Python Tools for Visual Studio - Django Integration   3.0.16334.1
Provides templates and integration for the Django web framework.

Python Tools for Visual Studio - Profiling Support   3.0.16334.1
Profiling support for Python projects.

SQL Server Data Tools   15.1.61124.0
Microsoft SQL Server Data Tools

TypeScript   2.1.3.0
TypeScript tools for Visual Studio

### LINKED ISSUE #2278: EnsureCodeSyncedAsync fails
Error from MSBuild log. Not sure why it showed up in an MSBuild log, but it dit.

```
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.PythonTools.Intellisense.BufferParser.GetLastSentSnapshot(ITextBuffer buffer) in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 148
   at Microsoft.PythonTools.Intellisense.BufferParser.<EnsureCodeSyncedAsync>d__36.MoveNext() in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\BufferParser.cs:line 292
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Intellisense.AnalysisEntry.<EnsureCodeSyncedAsync>d__42.MoveNext() in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\AnalysisEntry.cs:line 250
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<ExtractMethodAsync>d__148.MoveNext() in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 1906
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.PythonTools.Intellisense.ExtractMethodSuggestedActionSourceProvider.ExtractMethodSuggestedActionSource.SuggestedAction.<GetPreviewAsync>d__17.MoveNext() in D:\PTVS\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ExtractMethodSuggestedActionSourceProvider.cs:line 163
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbSession.<GetPreviewAsync>d__37.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.<>c__DisplayClass17_0.<<InitializeNonFlavored>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.<GetOrCreatePreviewAsync>d__42.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.<InitializeNonFlavored>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulbMenuItem.<Initialize>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Language.Intellisense.Implementation.LightBulb.<OnMenuItemGotKeyboardFocus>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1953 Tests are not shown on VS 2017
Move initial project scan to UI thread
Moves UIThreadBase related extensions to VSCommon
Avoids blocking analysis complete event until the editor is opened

Fixes #2278 Crash in EnsureCodeSyncedAsync
Handles attempts to get info about a buffer that does not belong to the parser.

Also removes some unused extension methods

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs [hunk 1]
```diff
@@ -493,17 +493,22 @@ out _analysisProcess
...
+                entry.GetBufferParserAsync().ContinueWith(t => {
+                    if (t.IsCanceled) {
+                        // Silence if we cancelled, else the t.Result below
+                        // will re-raise any exceptions for us.
+                        return;
+                    }
+
                     foreach (var version in analysisComplete.versions) {
-                        bufferParser.Analyzed(version.bufferId, version.version);
+                        t.Result.Analyzed(version.bufferId, version.version);
```
Comment (int19h) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: Should this be `GetAwaiter().GetResult()` to unwrap the exception?

File: Python/Product/TestAdapter/TestContainerDiscoverer.cs [hunk 2]
```diff
@@ -47,11 +49,8 @@ private TestContainerDiscoverer([Import(typeof(SVsServiceProvider))]IServiceProv
                     operationState) { }
 
         internal bool IsProjectKnown(IVsProject project) {
-            var pyProj = project as IPythonProjectProvider;
-            if (pyProj != null) {
-                return _projectInfo.ContainsKey(pyProj.Project);
-            }
-            return false;
+            var pyProj = PythonProject.FromObject(project);
+            return pyProj == null ? false : _projectInfo.ContainsKey(pyProj);
```
Comment (int19h) [inline Python/Product/TestAdapter/TestContainerDiscoverer.cs]: `pyProj != null && _projectInfo.ContainsKey(pyProj)`

**Comment by int19h** [comment]
👍
