### PR TITLE
Don't report unhandled error when REPL scripts directory is not found.

### LINKED ISSUE #4239: System.IO.DirectoryNotFoundException: Visual Studio 2017 ---> System.ArgumentException: Path was invalid
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.7.18116.1

System.IO.DirectoryNotFoundException: Visual Studio 2017 ---> System.ArgumentException: Path was invalid
Parameter name: root ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at System.Uri..ctor(String uriString, UriKind uriKind)
   at Microsoft.PythonTools.Infrastructure.PathUtils.MakeUri(String path, Boolean isDirectory, UriKind kind, String throwParameterName)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception exceptionObject)
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Infrastructure.PathUtils.MakeUri(String path, Boolean isDirectory, UriKind kind, String throwParameterName)
   at Microsoft.PythonTools.Infrastructure.PathUtils.GetAbsoluteDirectoryPath(String root, String relativePath)
   at Microsoft.PythonTools.Repl.PythonCommonInteractiveEvaluator.GetScriptsPath(IServiceProvider provider, String displayName, InterpreterConfiguration config, Boolean onlyIfExists)
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Repl.PythonCommonInteractiveEvaluator.GetScriptsPath(IServiceProvider provider, String displayName, InterpreterConfiguration config, Boolean onlyIfExists)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.<>c__DisplayClass9_0.<GetScriptPath>b__0()
   at Microsoft.VisualStudioTools.UIThread.<>c__DisplayClass12_0`1.<<Invoke>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTask`1.CompleteOnCurrentThread()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod, JoinableTaskCreationOptions creationOptions)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory.Run[T](Func`1 asyncMethod)
   at Microsoft.VisualStudioTools.UIThread.Invoke[T](Func`1 func)
   at Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.GetScriptPath(EnvironmentView view)
```

### PR DESCRIPTION
**Pull request by huguesv**
Fix #4239

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs [hunk 1]
```diff
@@ -161,6 +161,8 @@ sealed class InterpreterListToolWindow : ToolWindowPane {
                     view.Factory.Configuration,
                     false
                 ));
+            } catch (DirectoryNotFoundException) {
```
Comment (MikhailArkhipov) [inline Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs]: Do we care if directory is there but is empty?

Comment (huguesv) [reply Python/Product/PythonTools/PythonTools/InterpreterList/InterpreterListToolWindow.cs]: That's fine. The way this is used is we enumerate all *.py files in that folder, and execute them in alphabetical order when the REPL starts. If there's no files in the folder, we have nothing to execute.
