### PR TITLE
Fixes #3306 System.InvalidOperationException: uninitialized token cache

### LINKED ISSUE #3306: System.InvalidOperationException: uninitialized token cache
I created a new python application, and got this activity log error after the new project was loaded.

```

System.InvalidOperationException: uninitialized token cache at  
Microsoft.PythonTools.TokenCache.get_Map() in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\TokenCache.cs:line  181 at 
Microsoft.PythonTools.TokenCache.set_Item(Int32 line, LineTokenization  value) in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\TokenCache.cs:line  234 at  
Microsoft.PythonTools.Editor.PythonTextBufferInfo.GetLineTokenization(ITextSnapshotLine  line, Tokenizer& tokenizer) in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line  648 at  Microsoft.PythonTools.Editor.PythonTextBufferInfo.<GetTrackingTokens>d__74.MoveNext()  in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Editor\PythonTextBufferInfo.cs:line  479 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext() at  System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext() at  
System.Collections.Generic.List`1..ctor(IEnumerable`1 collection) at  
System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) at  Microsoft.PythonTools.PythonClassifier.GetClassificationSpans(SnapshotSpan span)  in  C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\PythonClassifier.cs:line  72 
at  Microsoft.VisualStudio.Text.Classification.Implementation.ClassifierTagger.<GetTags>d__5.MoveNext()  
at  Microsoft.VisualStudio.Text.Tagging.Implementation.TagAggregator`1.<GetTagsForBuffer>d__39.MoveNext()  --- End of stack trace from previous location where exception was thrown --- at 
 Microsoft.VisualStudio.Telemetry.WindowsErrorReporting.WatsonReport.GetClrWatsonExceptionInfo(Exception  exceptionObject)
--

```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #3306 System.InvalidOperationException: uninitialized token cache
Switches to more conservative locking strategy.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs [hunk 1]
```diff
@@ -631,46 +633,52 @@ sealed class PythonTextBufferInfo {
...
                     }
-                    _tokenCache[start] = lineTok = TokenizeLine(tokenizer, line.Snapshot.GetLineFromLineNumber(start), state);
                 }
             }
 
             return lineTok;
         }
 
-        private void ApplyChangeToTokenCache(ref Tokenizer tokenizer, SnapshotSpan span) {
+        private static void ApplyChangeToTokenCache(TokenCache cache, ref Tokenizer tokenizer, Func<Tokenizer> makeTokenizer, SnapshotSpan span) {
```
Comment (int19h) [inline Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: Not sure I follow the reason for the change - how does making it `static` and passing the instance members it was previously accessing as arguments changes matters, given that it's done under the lock either way?

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: It doesn't, but I feel it makes it a little more obvious that it should be already locked on entry to the function. Maybe it's just me?
