### PR TITLE
Fixes #3010 Crash collecting output from pip

### LINKED ISSUE #3010: Crash collecting output from pip
We have seen this crash occurring:

```
mscorlib.ni!System.Text.StringBuilder.ExpandByABlock in stringbuilder.cs
at mscorlib.ni!System.Text.StringBuilder.Append in stringbuilder.cs
at mscorlib.ni!System.Text.StringBuilder.AppendHelper in stringbuilder.cs
at mscorlib.ni!System.Text.StringBuilder.Append in stringbuilder.cs
at mscorlib.ni!System.String.Join in string.cs
at Microsoft.PythonTools.VSInterpreters!Microsoft.PythonTools.Interpreter.PipPackageManager
at mscorlib.ni!System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess in TaskAwaiter.cs
at mscorlib.ni!System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification in TaskAwaiter.cs
at Microsoft.PythonTools.VSInterpreters!Microsoft.PythonTools.Interpreter.PipPackageManager
at mscorlib.ni!System.Runtime.CompilerServices.AsyncMethodBuilderCore in AsyncMethodBuilder.cs
at mscorlib.ni!System.Threading.QueueUserWorkItemCallback.WaitCallback_Context in threadpool.cs
at mscorlib.ni!System.Threading.ExecutionContext.RunInternal in executioncontext.cs
at mscorlib.ni!System.Threading.ExecutionContext.Run in executioncontext.cs
at mscorlib.ni!System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem in threadpool.cs
at mscorlib.ni!System.Threading.ThreadPoolWorkQueue.Dispatch in threadpool.cs
at mscorlib.ni!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback in threadpool.cs
???
KERNELBASE!RaiseException in xcpt.c
at clr!RaiseTheExceptionInternalOnly in excep.cpp
at clr!UnwindAndContinueRethrowHelperAfterCatch in excep.cpp
at clr!JIT_New in jithelpers.cpp
at Microsoft.PythonTools.Analysis!Microsoft.PythonTools.Analysis.Analyzer.AnalyzerStatusUpdaterImplementation.ReadAllStatuses in AnalyzerStatusUpdater.cs
at Microsoft.PythonTools.Analysis!Microsoft.PythonTools.Analysis.Analyzer.AnalyzerStatusUpdaterImplementation.ThreadProc in AnalyzerStatusUpdater.cs
at mscorlib.ni!System.Threading.ThreadHelper.ThreadStart_Context in thread.cs
at mscorlib.ni!System.Threading.ExecutionContext.RunInternal in executioncontext.cs
at mscorlib.ni!System.Threading.ExecutionContext.Run in executioncontext.cs
at mscorlib.ni!System.Threading.ExecutionContext.Run in executioncontext.cs
at mscorlib.ni!System.Threading.ThreadHelper.ThreadStart in thread.cs
at clr!CallDescrWorkerInternal in asmhelpers.asm
at clr!CallDescrWorkerWithHandler in callhelpers.cpp
at clr!MethodDescCallSite::CallTargetWorker in callhelpers.cpp
at clr!ThreadNative::KickOffThread_Worker in comsynchronizable.cpp
at clr!ManagedThreadBase_DispatchInner in threads.cpp
at clr!ManagedThreadBase_DispatchMiddle in threads.cpp
at clr!ManagedThreadBase_DispatchOuter in threads.cpp
at clr!ManagedThreadBase_FullTransitionWithAD in threads.cpp
at clr!ThreadNative::KickOffThread in comsynchronizable.cpp
at clr!Thread::intermediateThreadProc in threads.cpp
at kernel32!BaseThreadInitThunk in thread.c
at ntdll!__RtlUserThreadStart in rtlstrt.c
at ntdll!_RtlUserThreadStart in rtlstrt.c
```

Hard to tell exactly what the cause is, but a few places in `PipPackageManager` use `string.Join` to collect many lines of output into a single string. It's entirely possible that for very large output this could get us into an OOM. Might be worth looking at processing the output by lines rather than joining it.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #3010 Crash collecting output from pip
Uses a reader subclass to avoid concatenating large JSON files in memory.

Tests are still coming, but I was so pleased that this worked first time I figured I'd get the PR out so someone can tell me what I missed :)

### CODE REVIEW

File: Python/Product/VSInterpreters/PipPackageManager.cs [hunk 1]
```diff
@@ -458,17 +459,18 @@ CancellationToken cancellationToken
                         try {
                             if ((await proc) == 0) {
                                 if (_pipListHasFormatOption) {
-                                    var json = string.Join(Environment.NewLine, proc.StandardOutputLines);
                                     try {
-                                        var data = JArray.Parse(json);
+                                        var data = JToken.ReadFrom(new JsonTextReader(new StringListReader(proc.StandardOutputLines)));
```
Comment (int19h) [inline Python/Product/VSInterpreters/PipPackageManager.cs]: I wonder if it would be better to change `ProcessOutput` to store the data as a single chunk in the first place (e.g. as `MemoryStream`? so that it can be fed directly to anything that expects a stream or a reader), and reimplement `StandardOutputLines` as lazy iterator over that.

Comment (zooba) [reply Python/Product/VSInterpreters/PipPackageManager.cs]: I think the storing it as the single chunk is the problem. A list of strings can be relocated by the GC, while a chunk approaching GB is going to be hard to allocate (I don't have sufficient info from the crash data, but my guess is that it's a failed large allocation rather than a leak, since it was in the `string.Join`).

If it's still a problem here, we can probably create an adapter between the `Redirector` and `JsonTextReader`, but since it's a push vs. pull model adapter it's going to be much more complicated.

**Comment by huguesv** [comment]
`pip list --format=json` for anaconda 3 (with 157 packages) gives me output that 6640 characters. That's not much, you would need a lot of packages for this to be significant.

Something else had to eat up all the memory and this just happened to be the thing that made it go OOM.

Or maybe there's a bug that causes this code to be executed continuously, like when we were reading code snippets on idle.

**Comment by zooba** [comment]
I agree, it's likely the users were all nearly out of memory already. But since we're being asked to fix the crash by the VS team, and it's easy enough to avoid the triggering allocation, I see no reason not to do it.

Even if the code is running continuously, there's nothing that keeps the memory around that we can derive from the info. We're fixing the only possible bug that exists here.

File: Python/Product/VSInterpreters/StringListReader.cs [hunk 2]
```diff
@@ -0,0 +1,97 @@
...
+            }
+            return i;
+        }
+
+        public override int Read(char[] buffer, int index, int count) {
+            if (_current == null) {
+                return 0;
+            }
+            var i = _current.Read(buffer, index, count);
+            if (i == 0 && Next()) {
```
Comment (huguesv) [inline Python/Product/VSInterpreters/StringListReader.cs]: If the requested count requires reading from 2 lines, this won't do it. I've seen some stream implementations behaving this way (not filling the requested count, even though there was more data available), and that was unexpected.
Remarks at https://msdn.microsoft.com/en-us/library/97e90x91(v=vs.110).aspx seem to imply that it should always fill the requested count, except when reached EOF.

Comment (zooba) [reply Python/Product/VSInterpreters/StringListReader.cs]: I've always understood it to mean "read again", but it looks like `ReadBlock` is intended to have the semantics you describe. I'll update that one

File: Python/Product/VSInterpreters/StringListReader.cs [hunk 3]
```diff
@@ -0,0 +1,155 @@
...
+        public override int Peek() {
+            if (_peekBuffer >= 0) {
+                return _peekBuffer;
+            }
+            _peekBuffer = Read();
+            return _peekBuffer;
+        }
+
+        public override string ReadLine() {
+            if (_peekBuffer == 0) {
```
Comment (int19h) [inline Python/Product/VSInterpreters/StringListReader.cs]: What's the special significance of 0? I can't see any place that sets `_peekBuffer` to that value.

Comment (zooba) [reply Python/Product/VSInterpreters/StringListReader.cs]: If we read a null byte. Things are going to get weird if we prefix a string with `\0`

Comment (zooba) [reply Python/Product/VSInterpreters/StringListReader.cs]: Actually, now I think about it, that doesn't matter. I spent too long in C last week...
