### PR TITLE
fix for Tooltips in package manager search results slows down VS, bec…

### LINKED ISSUE #5518: Tooltips in package manager search results slows down VS, becomes unusable
Open package manager UI
Type pytest in search bar
Hover the mouse over the results

Result: at some point, everything becomes so slow, it is no longer usable.

### PR DESCRIPTION
**Pull request by bschnurr**
…omes unusable fix #5518

circular triggering when p.Description was null.
package.description was first  null

then retriggered
then package.description was set to empty.string
then hit the first if again.

### CODE REVIEW

File: Python/Product/EnvironmentsList/PipPackageView.cs [hunk 1]
```diff
@@ -45,17 +45,18 @@ internal sealed class PipPackageView : INotifyPropertyChanged {
...
                         OnPropertyChanged("UpgradeVersion");
                     }
-                    if (p.Description != _package.Description) {
+                    
+                    if (!String.IsNullOrEmpty(p.Description) && p.Description != _package.Description) {
                         _package.Description = p.Description;
                         OnPropertyChanged("Description");
-                    } else if (string.IsNullOrEmpty(p.Description)) {
+                    }
+                    else if (_package.Description == null) {
```
Comment (bschnurr) [inline Python/Product/EnvironmentsList/PipPackageView.cs]: check if valid and different first

else if set to empty string
