### PR TITLE
Fixes #2949 Unexpected error after closing split view

### LINKED ISSUE #2949: Unexpected error after closing split view
This is with the latest PR https://github.com/Microsoft/PTVS/pull/2945

Open a file with some code in it.
Window->Split
Window->Remove split

Move the mouse around, and you'll get assert/unexpected error.

```
Build: 3.0.1000.00

System.ArgumentException: Failed to get classifier from buffer
   at Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot snapshot, ITextBuffer buffer, ITrackingSpan span) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ReverseExpressionParser.cs:line 53
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.GetApplicableExpression(AnalysisEntry entry, SnapshotPoint point) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2447
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.<GetQuickInfoAsync>d__165.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 2339
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.PythonTools.Intellisense.VsProjectAnalyzer.WaitForRequest[T](Task`1 request, String requestName, T defaultValue, Int32 timeoutScale) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ProjectAnalyzer.cs:line 128
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<>c__DisplayClass18_0.<TextViewMouseHoverWorker>b__0() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 127
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TextViewMouseHoverWorker>d__18.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 127
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.PythonTools.Infrastructure.VSTaskExtensions.<HandleAllExceptions>d__5.MoveNext() in C:\Projects\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\VSTaskExtensions.cs:line 179
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #2949 Unexpected error after closing split view
Correctly counts references to buffers so they are not released too soon.
Also fixes a double-free and an incorrect assertion.

### CODE REVIEW

**Comment by zooba** [comment]
Looks like there's still a similar issue on repl windows, probably due to still using the disconnect/connect pattern to update analysis info. I'll fix it.

**Comment by huguesv** [comment]
👍 to current changes

File: Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs [hunk 1]
```diff
@@ -201,11 +202,12 @@ string windowId
...
-            var buffer = eval?.CurrentWindow?.CurrentLanguageBuffer;
-            if (view != null && buffer != null) {
+            var buffer = PythonTextBufferInfo.TryGetForBuffer(eval?.CurrentWindow?.CurrentLanguageBuffer);
+            var pyEval = eval as IPythonInteractiveIntellisense;
+            if (view != null && buffer != null && pyEval != null) {
                 var controller = IntellisenseControllerProvider.GetOrCreateController(_serviceProvider, _serviceProvider.GetComponentModel(), view);
-                controller.DisconnectSubjectBuffer(buffer);
-                controller.ConnectSubjectBuffer(buffer);
+                var entry = pyEval.Analyzer.GetAnalysisEntryFromPath(pyEval.AnalysisFilename);
+                Debug.Assert(entry == buffer.TrySetAnalysisEntry(entry, buffer.AnalysisEntry));
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs]: Do you want TrySetAnalysisEntry to run in release builds?
https://stackoverflow.com/questions/13383651/will-the-expression-provided-to-debug-assert-be-evaluated-in-a-release-build

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs]: Um... yes... my bad

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Repl/SelectableReplEvaluator.cs]: In fact, that whole function should be simplified, because I moved the Intellisense handling into the Initialize call. I missed this when I went looking for dead code (though I'll make sure it's actually dead...)

**Comment by huguesv** [comment]
👍
