### PR TITLE
Issue #1699: Removes old reference analysis and replaces search paths with on-demand AST scans.

### LINKED ISSUE #1699: C++ project references cause VS to crash
From event log:

```
Application: devenv.exe
Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Runtime.InteropServices.COMException
   at EnvDTE.Project.get_Properties()
   at Microsoft.VisualStudioTools.Project.ProjectReferenceNode.get_AssemblyName()
   at Microsoft.PythonTools.Project.PythonProjectReferenceNode+<AddAnalyzedAssembly>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
   at Microsoft.PythonTools.Infrastructure.TaskExtensions+<DoNotWait>d__0.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore+<>c.<ThrowAsync>b__6_0(System.Object)
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector.TryExecute()
   at Microsoft.VisualStudio.Threading.JoinableTaskFactory+SingleExecuteProtector+<>c.<.cctor>b__20_0(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.DispatcherOperation.InvokeImpl()
   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Windows.Threading.DispatcherOperation.Invoke()
   at System.Windows.Threading.Dispatcher.ProcessQueue()
   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1699: Removes old reference analysis and replaces search paths with on-demand AST scans.

This does a few changes that aren't really as dramatic as they sound:
* removes WebPI and direct .pyd file references (project references and assembly references are okay)
* makes project references implicitly add a search path to the project
* switches to on-demand scraping of pyd files when they appear in a search path
* adds fast AST analysis for .py files referenced in a search path
 * this is triggered when an `import` can only be resolved via a search path
* migrates most of AnalysisTest over to a new `PythonAnalysis` helper class, that simplifies code and will make it possible to automatically test against multiple Python versions (that part isn't done yet)
* makes all `IPythonInterpreter` implementations be disposable

I still need to validate a build against VS 15, so there may be a few more changes coming, but considering we currently crash there this is definitely an improvement.

### CODE REVIEW

**Comment by zooba** [comment]
@DinoV is added to the review. #Closed

**Comment by zooba** [comment]
@huguesv is added to the review. #Closed

File: Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs [hunk 1]
```diff
@@ -0,0 +1,260 @@
...
+
+            if (m != null && node.Names != null) {
+                try {
+                    for (int i = 0; i < node.Names.Count; ++i) {
+                        var n = node.AsNames?[i] ?? node.Names[i];
+                        if (n != null) {
+                            m[n.Name] = new AstPythonConstant(
+                                _interpreter.GetBuiltinType(BuiltinTypeId.Module),
+                                GetLoc(n)
+                            );
```
Comment (zooba) [inline Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs]: Agreed. This was a lazy copy-paste from above. Ideally I'd like to be able to resolve these to class vs. function vs. constant from the referenced module (or at least submodules), since *many* libraries I looked at do relative imports for their public members, but it's not essential right now.

---
In reply to: [83938907](https://github.com/Microsoft/PTVS/pull/1729#discussion_r83938907) [](ancestors = 83938907)

File: Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs [hunk 2]
```diff
@@ -0,0 +1,260 @@
...
+            if (node == null || node.StartIndex >= node.EndIndex) {
+                return null;
+            }
+
+            var start = node.GetStart(_ast);
+            var end = node.GetEnd(_ast);
+            return new LocationInfo(_filePath, start.Line, start.Column, end.Line, end.Column);
+        }
+
+        private IMember GetValueFromExpression(Expression expr, Dictionary<string, IMember> scope) {
```
Comment (DinoV) [inline Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs]: >GetValueFromExpression [](start = 24, length = 22)

It seems like this should walk the list of scopes and find the values in parent scopes as well, but should skip any scopes which are class definitions

File: Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs [hunk 3]
```diff
@@ -0,0 +1,260 @@
...
+                            );
+                        }
+                    }
+                } catch (IndexOutOfRangeException) {
+                }
+            }
+            return false;
+        }
+
+        public override bool Walk(FunctionDefinition node) {
```
Comment (DinoV) [inline Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs]: >public override bool Walk(FunctionDefinition node) { [](start = 8, length = 52)

If you did 2 passes here you'd get significantly better results as you could collect the functions / classes first and then get any forward references, e.g:

def f():
    return g

def g():
    ...

File: Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs [hunk 4]
```diff
@@ -117,115 +77,206 @@ class CPythonInterpreter : IPythonInterpreter, IPythonInterpreterWithProjectRefe
...
-                    }
-                    if (removed && _typeDb != null) {
-                        _typeDb.UnloadExtensionModule(Path.GetFileNameWithoutExtension(reference.Name));
-                        RaiseModulesChanged(null);
-                    }
-                    break;
+        private IPythonModule LoadModuleFromZipFile(string zipFile, string moduleName) {
+            using (var stream = new FileStream(zipFile, FileMode.Open, FileAccess.Read))
+            using (var zip = new ZipArchive(stream, ZipArchiveMode.Read, true)) {
+                return null;
```
Comment (zooba) [inline Python/Product/Analysis/Interpreter/Default/CPythonInterpreter.cs]: >null [](start = 23, length = 4)

Umm... TODO ;)

File: Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs (hunk 2 above)
Comment (zooba) [inline Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs]: I remember planning to do that... not sure why I didn't. As it happens, the only relevant scopes are the top level and the current class, since we don't go into functions at all. I doubt there are all that many cases where a module-level variable is cloned into a class variable, but it's easy enough to check the module scope here as well.

---
In reply to: [83940069](https://github.com/Microsoft/PTVS/pull/1729#discussion_r83940069) [](ancestors = 83940069)

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs [hunk 5]
```diff
@@ -2249,169 +2283,208 @@ class AddDirectoryAnalysis : IAnalyzable {
...
-
-        internal void StopAnalyzingDirectory(string directory) {
-            if (_pyAnalyzer == null) {
-                // We aren't able to analyze code.
-                return;
-            }
-
-            _pyAnalyzer.RemoveAnalysisDirectory(directory);
-        }
+        //public void AnalyzeZipArchive(string zipFileName) {
```
Comment (DinoV) [inline Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: >AnalyzeZipArchive [](start = 22, length = 17)

We're losing zip archive support?

File: Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs (hunk 3 above)
Comment (zooba) [inline Python/Product/Analysis/Interpreter/Ast/AstAnalysisWalker.cs]: We don't walk into functions though. Any forward references we may encounter would cause SyntaxError at compile time. (When we come to handling annotations it'll be more interesting, as those will require a second pass, but this level of analysis isn't even going to try and determine return values from the body.)

---
In reply to: [83940287](https://github.com/Microsoft/PTVS/pull/1729#discussion_r83940287) [](ancestors = 83940287)

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs (hunk 5 above)
Comment (zooba) [inline Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: It's moving :) There's a "return null" in CPythonInterpreter.cs that I'm currently turning into actual support...

---
In reply to: [83941145](https://github.com/Microsoft/PTVS/pull/1729#discussion_r83941145) [](ancestors = 83941145)
