### PR TITLE
Fixes #802 VS crash with IronPython

### LINKED ISSUE #802: VS crash with IronPython and Dev 2015-08-21
VS 2013 Desktop Express, IronPython 2.7.5, PTVS Dev 2015-08-21 VS 2013

I spoke too soon :( I just got a hang while rebuilding my solution which is a mix of one IronPython project and three Windows Forms C# projects.  

PTVS Dev 2015-08-21 VS 2013 is definitely more stable than PTVS 2.2. I haven't yet encountered a crash or "Exception caused by an extension" message while editing the IronPython code which used to happen quite often in 2.2. I often got the crash below while rebuilding my solution in 2.2 and this is the first since installing Dev 2015-08-21 so somewhere, hiding in a dark murky corner there must be one or more unchecked casts that got overlooked when the rest were fixed!

Microsoft Visual Studio Express 2013 for Windows Desktop has stopped working.
Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	WDExpress.exe
  Problem Signature 02:	12.0.40629.0
  Problem Signature 03:	5590c29f
  Problem Signature 04:	Microsoft.PythonTools.IronPython.Interpreter
  Problem Signature 05:	2.2.30821.1
  Problem Signature 06:	55d7b607
  Problem Signature 07:	21a
  Problem Signature 08:	0
  Problem Signature 09:	System.InvalidCastException
  OS Version:	6.1.7601.2.1.0.768.3
  Locale ID:	2057
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

### PR DESCRIPTION
**Pull request by zooba**
Fixes #802 VS crash with IronPython
Captures the remote interpreter proxy along with the object handle, and stops trying to call into the remote interpreter when we know it's been disposed.

### CODE REVIEW

File: Python/Product/IronPython/Interpreter/RemoteInterpreterProxy.cs [hunk 1]
```diff
@@ -29,9 +29,14 @@ class RemoteInterpreterProxy : MarshalByRefObject {
         public RemoteInterpreterProxy() {
             AppDomain.CurrentDomain.AssemblyResolve += new ResolveEventHandler(CurrentDomain_AssemblyResolve);
             AppDomain.CurrentDomain.TypeResolve += new ResolveEventHandler(CurrentDomain_AssemblyResolve);
+            AppDomain.CurrentDomain.DomainUnload += CurrentDomain_Unload;
             _remoteInterpreter = new RemoteInterpreter();
         }
 
+        private void CurrentDomain_Unload(object sender, EventArgs e) {
+            throw new NotImplementedException();
```
Comment (DinoV) [inline Python/Product/IronPython/Interpreter/RemoteInterpreterProxy.cs]: What's this doing?

Comment (zooba) [inline Python/Product/IronPython/Interpreter/RemoteInterpreterProxy.cs]: Nothing... should have been deleted
