### PR TITLE
Fixes #590 NullReferenceException reinitializing modules

### LINKED ISSUE #590: NullReferenceException reinitializing modules
Seems to occur when a builtin module is removed between generating the names in `GetModuleNames()` and getting the module in `ImportModule()`.

```
First-chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Analysis.ModuleTable.ImportChildren(IPythonModule interpreterModule)
   at Microsoft.PythonTools.Analysis.ModuleTable.ReInit()
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.<ReloadModulesAsync>d__60.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #590 NullReferenceException reinitializing modules
Fixes handling where ReInit() encounters a module that is listed in module names but cannot be imported.
Adds test.

### CODE REVIEW

File: Python/Product/Analysis/ModuleTable.cs [hunk 1]
```diff
@@ -159,7 +159,12 @@ class ModuleTable : IEnumerable<KeyValuePair<string, ModuleLoadState>> {
 
                 var builtinModule = moduleRef.Module as BuiltinModule;
                 if (builtinModule != null) {
-                    if (!newNames.Contains(name)) {
+                    IPythonModule newModule = null;
+                    if (newNames.Contains(name)) {
+                        newModule = _interpreter.ImportModule(name);
+                    }
+
+                    if (newModule == null) {
```
Comment (zooba) [inline Python/Product/Analysis/ModuleTable.cs]: This section is the fix. Most of the rest of the changes are to allow testing `ModuleTable` without setting up a full analyzer.
