### PR TITLE
Fix for NRE in AnalyzeBufferAsync

### LINKED ISSUE #4224: NullReferenceException in Microsoft.PythonTools.Intellisense.IntellisenseController.AnalyzeBufferAsync
From Watson report. Internal bug 616461.

### PR DESCRIPTION
**Pull request by karthiknadig**
Fixes #4224

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs [hunk 1]
```diff
@@ -183,7 +183,7 @@ internal sealed class IntellisenseController : IIntellisenseController, IOleComm
                 isTemporaryFile = true;
                 analyzer = await services.Site.FindAnalyzerAsync(textView);
                 if (analyzer == null) {
-                    analyzer = await services.Python.GetSharedAnalyzerAsync();
+                    analyzer = await services.Python?.GetSharedAnalyzerAsync();
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/IntellisenseController.cs]: await null will also cause a NullReferenceException. I checked:
```
    class Program {
        static async Task Main(string[] args) { await MyHelper?.DoAsync(); }
        static Helper MyHelper => null;
    }
    class Helper { public async Task DoAsync() => await Task.Delay(1); }
```
