### PR TITLE
Fixes #454 NullReferenceException in CreateOrAddVirtualEnvironment

### LINKED ISSUE #454: NullReferenceException in CreateOrAddVirtualEnvironment
Can't tell exactly where it is, though presumably it's after the await.

Wild guess says we're cleaning up and `_interpreters` is null.

```
First-chance exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.PythonTools.Project.PythonProjectNode.<CreateOrAddVirtualEnvironment>d__148.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentOperation.<Run>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Project.AddVirtualEnvironmentView.<Create>d__105.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #454 NullReferenceException in CreateOrAddVirtualEnvironment
Improves (adds) null handling for the _interpreters variable, which is set to null when disposing.

### CODE REVIEW

**Comment by int19h** [comment]
:+1:

File: Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs [hunk 1]
```diff
@@ -1364,12 +1364,19 @@ private static T FindImmediateChild<T>(HierarchyNode parent)
...
 
-                factory = _interpreters.GetInterpreterFactories().FirstOrDefault(
-                    // Description is a localized string, hence CCIC
-                    f => description.Equals(f.Description, StringComparison.CurrentCultureIgnoreCase)
-                ) ?? service.Interpreters.FirstOrDefault(
-                    f => description.Equals(f.Description, StringComparison.CurrentCultureIgnoreCase)
-                );
+                var interpreters = _interpreters;
+                if (interpreters != null) {
+                    factory = _interpreters.GetInterpreterFactories().FirstOrDefault(
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs]: should this use `interpreters`?
