### PR TITLE
Fixes serialization issue with ptvsd system info

### LINKED ISSUE #3987: Check version deserialization fails with error
```
 4> [DebugAdapter] <--   R (ptvsd_systemInfo-2): {"type": "response", "seq": 3, "request_seq": 2, "success": true, "command": "ptvsd_systemInfo", "message": "", "body": {"ptvsd": {"version": "4.0.0a5"}, "python": {"version": [3, 6, 3, "final", 0], "implementation": {"name": "cpython", "version": [3, 6, 3, "final", 0], "description": "CPython"}}, "platform": {"name": "win32"}, "process": {"pid": 13724, "executable": "C:\\Program Files (x86)\\Microsoft Visual Studio\\Shared\\Python36_64\\python.exe", "bitness": 64}, "user": {"name": "kanadig"}}}
 4> Stopping due to fatal error: JsonReaderException: Error reading string. Unexpected token: StartArray. Path 'python.version'.
 4> ERROR: Debug Adapter did not respond to initial requests.
 4> ERROR: Protocol error

JsonReaderException: Error reading string. Unexpected token: StartArray. Path 'python.version'.

Newtonsoft.Json.JsonReader.ReadAsString()
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadForType(JsonReader reader, JsonContract contract, Boolean hasConverter)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
Newtonsoft.Json.Linq.JToken.ToObject[T](JsonSerializer jsonSerializer)
Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.PendingRequestWithResponse`2.InvokeCompletionFunc(Object args, JObject responseBody, JsonSerializer serializer)
CallSite.Target(Closure , CallSite , IPendingRequest , Object , Object , JsonSerializer )
System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid4[T0,T1,T2,T3](CallSite site, T0 arg0, T1 arg1, T2 arg2, T3 arg3)
CallSite.Target(Closure , CallSite , IPendingRequest , Object , Object , JsonSerializer )
Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingResponse(String msg)
Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.HandleIncomingMessage(String msg)
Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ProcessMessageBody()
Microsoft.VisualStudio.Shared.VSCodeDebugProtocol.Protocol.DebugProtocol.ReaderThreadProc()

 4> ERROR: Error reading string. Unexpected token: StartArray. Path 'python.version'.
 4> ERROR: Exception while reporting error.

ComponentException: Exception of type 'Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.AD7.Definition.ComponentException' was thrown.

Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.AD7.Implementation.EngineCallback.Send(IAD7DebugEvent eventObject, IDebugThread2 thread)
Microsoft.VisualStudio.Debugger.VSCodeDebuggerHost.AD7.Implementation.EngineCallback.OnError(String errorMessage)

HResult: 0x80010108
```

This is because we expect the version info to be a string insted we receive an array in older versions.

### PR DESCRIPTION
**Pull request by karthiknadig**
Fixes #3987

### CODE REVIEW

File: Python/Product/Debugger/PtvsdVersionHelper.cs [hunk 1]
```diff
@@ -51,18 +51,23 @@ internal class PtvsdVersionHelper {
...
                 }
             }
         }
+
+        public static void VerifyPtvsdVersionError(PtvsdVersionArguments args, ProtocolException ex) {
+            ShowPtvsdVersionMessage(Strings.InstalledPtvsdOutdatedMessage.FormatUI("unknown", PtvsdVersion.Version));
+        }
+
+        private static void ShowPtvsdVersionMessage(string message) {
+            MessageBox.Show(
```
Comment (huguesv) [inline Python/Product/Debugger/PtvsdVersionHelper.cs]: You no longer need to switch to main thread to avoid UI freezing?

File: Python/Product/Debugger/PtvsdVersionHelper.cs [hunk 2]
```diff
@@ -71,8 +76,12 @@ internal class PtvsdDebuggerVersion {
     }
 
     internal class PythonVersionInfo {
+        /// <summary>
```
Comment (huguesv) [inline Python/Product/Debugger/PtvsdVersionHelper.cs]: Normally you can omit any field that you are not interested in, and json deserialization will just skip them (as a bonus, it ends up being faster). If you plan on using them later, then feel free to keep them.

File: Python/Product/Debugger/PtvsdVersionHelper.cs (hunk 1 above)
Comment (karthiknadig) [reply Python/Product/Debugger/PtvsdVersionHelper.cs]: Nope, message box does not require that. Explicitly switching to UI thread was blocking the message box from getting displayed in cases where there was pending operation going on while we were attempting to show the message box.

File: Python/Product/Debugger/PtvsdVersionHelper.cs (hunk 2 above)
Comment (karthiknadig) [reply Python/Product/Debugger/PtvsdVersionHelper.cs]: We actually plan on using this data to show process and interpreter info in 'Attach to Process' UI.
