### PR TITLE
Fixes #1603 Race condition in PythonNavigateToItemProvider

### LINKED ISSUE #1603: Race condition in PythonNavigateToItemProvider
I am using Visual Studio 2015 Community with Update 3 and Python Tools in version 2.2.4 and I still have this error when I type `ĆTRL+,`

```
Unhandled exception in Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.StartSearch (D:\PTVS\PTVS22\Python\Product\PythonTools\PythonTools\Navigation\NavigateTo\PythonNavigateToItemProvider.cs:162)
System.ObjectDisposedException: The CancellationTokenSource has been disposed.
   at System.Threading.CancellationTokenSource.ThrowObjectDisposedException()
   at Microsoft.PythonTools.Navigation.NavigateTo.PythonNavigateToItemProvider.<>c__DisplayClass6_0.<StartSearch>b__0()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__5.MoveNext()
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1603 Race condition in PythonNavigateToItemProvider
Makes StartSearch more robust to races in the cancellation token.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs [hunk 1]
```diff
@@ -163,34 +163,48 @@ out projectType
...
-                    searchCts.Token
+                    token
                 );
             } catch (OperationCanceledException) {
             } catch (Exception ex) when (!ex.IsCriticalException()) {
                 ex.ReportUnhandledException(_serviceProvider, GetType());
             } finally {
                 callback.Done();
+                if (searchCts != null) {
+                    Interlocked.CompareExchange(ref _searchCts, null, searchCts);
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs]: If we replace `_searchCts` with `null`, then it won't get disposed at the next `StartSearch` or this class' `Dispose`.

File: Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs [hunk 2]
```diff
@@ -163,34 +163,48 @@ out projectType
...
+                    oldCts?.Cancel();
+                    oldCts?.Dispose();
+                } catch (ObjectDisposedException) {
+                }
+
+                CancellationToken token;
+                try {
+                    token = searchCts.Token;
+                } catch (ObjectDisposedException) {
+                    // highly unlikely race, but easy enouh to protect against
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs]: enouh -> enough

File: Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs (hunk 1 above)
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Navigation/NavigateTo/PythonNavigateToItemProvider.cs]: It doesn't need to, because it will only be replaced if it is our current one, and only when we've stopped paying attention to it. But this is the right place to dispose `searchCts`.

**Comment by huguesv** [comment]
👍
