### PR TITLE
Fixes #4526 Assert while/after creating a virtual env

### LINKED ISSUE #4526: Assert while/after creating a virtual env
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------


   at Microsoft.PythonTools.Analysis.Deque`1.AssertContext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Deque.cs:line 39
   at Microsoft.PythonTools.Analysis.Deque`1.Append(T x) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Deque.cs:line 50
   at Microsoft.PythonTools.Analysis.AnalysisUnit.Enqueue() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\AnalysisUnit.cs:line 130
   at Microsoft.PythonTools.Analysis.DependentData`1.EnqueueDependents(IVersioned assigner, IProjectEntry declaringScope) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\VariableDef.cs:line 75
   at Microsoft.PythonTools.Analysis.Values.ModuleInfo.EnsureModuleVariables(PythonAnalyzer state) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\Values\ModuleInfo.cs:line 79
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.<ReloadModulesAsync>d__66.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\PythonAnalyzer.cs:line 188
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.PythonTools.Analysis.PythonAnalyzer.ReloadModulesAsync()
   at Microsoft.PythonTools.Analysis.LanguageServer.Server.ReloadModulesQueueItem.<Analyze>b__5_0() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Analysis\LanguageServer\Server.cs:line 55
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.Tasks.Task.ExecutionContextCallback(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()
 
---------------------------
Abort   Retry   Ignore   
---------------------------
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4526 Assert while/after creating a virtual env
Ensures module reload occurs on analysis thread
Prevent exceptions when attempting to enqueue operations after the analyzer is closed

### CODE REVIEW

File: Python/Product/Analysis/LanguageServer/Server.cs [hunk 1]
```diff
@@ -52,9 +52,8 @@ private sealed class ReloadModulesQueueItem : IAnalyzable {
                 }
 
                 var currentTcs = Interlocked.Exchange(ref _tcs, new TaskCompletionSource<bool>());
-                var task = Task.Run(() => _analyzer.ReloadModulesAsync(), cancel);
                 try {
-                    task.WaitAndUnwrapExceptions();
+                    _analyzer.ReloadModulesAsync().WaitAndUnwrapExceptions();
```
Comment (zooba) [inline Python/Product/Analysis/LanguageServer/Server.cs]: The docs for `ReloadModulesAsync` explicitly say it needs to be run on the analyzer thread. The only async operation within this function (currently) is run on a separate thread, so there shouldn't be any risk of deadlock here.

File: Python/Product/Analysis/PythonAnalyzer.cs [hunk 2]
```diff
@@ -179,7 +179,7 @@ public partial class PythonAnalyzer : IGroupableAnalysisProject, IDisposable {
                 _interpreterFactory.NotifyImportNamesChanged();
                 _modules.ReInit();
 
-                await LoadKnownTypesAsync().ConfigureAwait(false);
+                await LoadKnownTypesAsync();
```
Comment (zooba) [inline Python/Product/Analysis/PythonAnalyzer.cs]: Any situation where we have no sync context, we also shouldn't have any loaded modules (below), so there won't be an issue. If there are loaded modules, they may be enqueued, which means we have an analysis queue and synchronization context available, so any call that isn't within that context is invalid and needs to be fixed.
