### PR TITLE
Fix #4236: Crash in multi line string

### LINKED ISSUE #4236: Crash in multi line string
Type
```
print('''

.\''')
```

and press CTRL+SPACE after `\`

Result:
```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
An unhandled exception is about to terminate the process:

Specified argument was out of the range of valid values.

Parameter name: span

System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

Parameter name: span

   at Microsoft.VisualStudio.Text.Implementation.TrackingSpan..ctor(ITextVersion version, Span span, SpanTrackingMode trackingMode)

   at Microsoft.VisualStudio.Text.Implementation.TextVersion.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode, TrackingFidelityMode trackingFidelity)

   at Microsoft.VisualStudio.Text.Implementation.BaseSnapshot.CreateTrackingSpan(Span span, SpanTrackingMode trackingMode)

   at Microsoft.PythonTools.Extensions.GetApplicableSpan(ITextSnapshot snapshot, Int32 position, Boolean completeWord) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 170

   at Microsoft.PythonTools.Extensions.GetApplicableSpan(ITextSnapshot snapshot, ITrackingPoint point, Boolean completeWord) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 129

   at Microsoft.PythonTools.Extensions.GetApplicableSpan(IIntellisenseSession session, ITextBuffer buffer) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 116

   at Microsoft.PythonTools.Intellisense.CompletionSource.AugmentCompletionSession(ICompletionSession session, IList`1 completionSets) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\CompletionSource.cs:line 70

   at Microsoft.VisualStudio.Language.Intellisense.Implementation.CompletionSession.Start()

   at Microsoft.PythonTools.Intellisense.IntellisenseController.<TriggerCompletionSession>d__43.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\IntellisenseController.cs:line 967

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

   at Microsoft.PythonTools.Infrastructure.TaskExtensions.<DoNotWaitImpl>d__1.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\Common\Infrastructure\TaskExtensions.cs:line 35

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)

   at Microsoft.VisualStudioTools.CommonPackage.<>c.<.ctor>b__9_0(Object sender, UnhandledExceptionEventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\CommonPackage.cs:line 67

   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.<>c.<ThrowAsync>b__6_0(Object state)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.DispatcherOperation.InvokeImpl()

   at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state)

   at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Windows.Threading.DispatcherOperation.Invoke()

   at System.Windows.Threading.Dispatcher.ProcessQueue()

   at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)

   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)

   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)

   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)

   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

### PR DESCRIPTION
**Pull request by AlexanderSher**
File system completions in string literals can't be moved to the server analysis without changes in tokenizer cause AST node doesn't have information if string is raw and if it is not it has no mapping from the caret index into string. Since feature isn't heavily used and has its own issues, @alexandersher and @zooba agreed that it is safer right now to remove this completion rather than make changes in tokenizer.

### CODE REVIEW

**Comment by AlexanderSher** [comment]
Also some dead code is removed

File: Python/Product/PythonTools/PythonTools/DiagnosticsProvider.cs [hunk 1]
```diff
@@ -69,7 +69,7 @@ internal sealed class DiagnosticsProvider {
 
         private static readonly Regex InterestingApplicationLogEntries = new Regex(
             @"^Application: (devenv\.exe|.+?Python.+?\.exe|ipy(64)?\.exe)",
-            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant
+            RegexOptions.IgnoreCase | RegexOptions.CultureInvariant | RegexOptions.Compiled
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/DiagnosticsProvider.cs]: There's no benefit to compiling this regex - it isn't used nearly enough. We deliberately default to not using `Compiled` unless it can be proven to be worthwhile.

File: Python/Product/PythonTools/PythonTools/Extensions.cs [hunk 2]
```diff
@@ -198,6 +200,26 @@ static class Extensions {
             return null;
         }
 
+        internal static Span? GetStringContentSpan(string text, int globalStart = 0) {
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Extensions.cs]: Is this unused now? If it's going to stick around, there are some issue to fix.

File: Python/Product/PythonTools/PythonTools/Extensions.cs [hunk 3]
```diff
@@ -165,7 +167,7 @@ static class Extensions {
                 if (lastToken.ClassificationType.IsOfType(PredefinedClassificationTypeNames.String)) {
                     // Handle "'contents of strin|g"
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Extensions.cs]: We don't need to handle this anymore, right?

File: Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs [hunk 4]
```diff
@@ -36,45 +33,140 @@ namespace Microsoft.PythonTools.Intellisense {
     /// Provides various completion services after the text around the current location has been
     /// processed. The completion services are specific to the current context
     /// </summary>
-    class CompletionAnalysis {
+    internal class CompletionAnalysis {
+        internal const long TooMuchTime = 50;
+        private static Stopwatch _stopwatch = MakeStopWatch();
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs]: `readonly`

File: Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs [hunk 5]
```diff
@@ -36,45 +33,140 @@ namespace Microsoft.PythonTools.Intellisense {
...
+        private readonly ITrackingPoint _point;
+        private readonly CompletionOptions _options;
+        private ITrackingSpan _span;
 
         internal static CompletionAnalysis EmptyCompletionContext = new CompletionAnalysis(null, null, null, null, null, null);
 
-        internal CompletionAnalysis(PythonEditorServices services, ICompletionSession session, ITextView view, ITrackingSpan span, ITextBuffer textBuffer, CompletionOptions options) {
+        internal CompletionAnalysis(PythonEditorServices services, ICompletionSession session, ITextView view, ITextSnapshot snapshot, ITrackingPoint point, CompletionOptions options) {
             _session = session;
             _view = view;
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Intellisense/CompletionAnalysis.cs]: `?? throw new ArgumentNullException…`

File: Python/Product/PythonTools/PythonTools/DiagnosticsProvider.cs (hunk 1 above)
Comment (AlexanderSher) [reply Python/Product/PythonTools/PythonTools/DiagnosticsProvider.cs]: There was a benefit while collecting full log. I haven't measured it but it was visually noticeable.
