### PR TITLE
Fixes #4115: Completions dropdown shouldn't appear after def and class

### LINKED ISSUE #4115: Completions dropdown shouldn't appear after def and class
Regression in 15.8 branch

New Python application
Type: `def ` or `class `
Result: after typing the space, completions drop down appears.

Example: type `def he(` and you'll get `def help()` instead of `def he()`, so you're forced to dismiss with ESC to get what you want.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4115: Completions dropdown shouldn't appear after def and class
Fixes handling of incomplete def and class statements
Fixes default commit of overrides
Fixes references to import names

### CODE REVIEW

File: Python/Product/Analysis/LanguageServer/Structures.cs [hunk 1]
```diff
@@ -657,6 +657,10 @@ public struct CompletionList {
         /// The expression that members are being displayed for.
         /// </summary>
         public string _expr;
+        /// <summary>
+        /// When true, completions should commit by default.
```
Comment (AlexanderSher) [inline Python/Product/Analysis/LanguageServer/Structures.cs]: What does `null` mean?

Comment (zooba) [reply Python/Product/Analysis/LanguageServer/Structures.cs]: Up to the IDE in that case - this is kind-of an option in VS, but in some cases we want to force it to false (e.g. override completions).

I'll clarify the docs and make it null most of the time.
