### PR TITLE
Project system cut and paste fixes

### LINKED ISSUE #3225: Error cut & pasting folder within project
Affected tests:
DragDropCopyCutPaste.MoveFolderWithContents
DragDropCopyCutPaste.CutFolderAndfile (same error, slightly different steps)
NewDragDropCopyCutPaste.MoveExcludedFolderKeyboard(same error, slightly different steps)

Create new project
Add folders and an empty text file such that you have this hierarchy:

```
- A\
  - B\
    - File.txt
- C\
```

Select B, Ctrl-X
Select C, Ctrl-V

You'll get 2 identical asserts followed by an error message.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
<null>



   at Microsoft.VisualStudioTools.Project.ProjectNode.ProjectReferenceFileAdder.FileAddition.DoAddition(Nullable`1& overwrite) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.CopyPaste.cs:line 1273

   at Microsoft.VisualStudioTools.Project.ProjectNode.ProjectReferenceFileAdder.FolderAddition.DoAddition(Nullable`1& overwrite) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.CopyPaste.cs:line 802

   at Microsoft.VisualStudioTools.Project.ProjectNode.ProjectReferenceFileAdder.AddFiles() in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.CopyPaste.cs:line 512

   at Microsoft.VisualStudioTools.Project.ProjectNode.AddFilesFromProjectReferences(HierarchyNode targetNode, String[] projectReferences, Boolean mouseDropping, DropEffect dropEffect) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.CopyPaste.cs:line 1840

   at Microsoft.VisualStudioTools.Project.ProjectNode.ProcessSelectionDataObject(IDataObject dataObject, HierarchyNode targetNode, Boolean drop, DropEffect dropEffect) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.CopyPaste.cs:line 1625

   at Microsoft.VisualStudioTools.Project.ProjectNode.PasteFromClipboard(HierarchyNode targetNode) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.CopyPaste.cs:line 1515

   at Microsoft.VisualStudioTools.Project.HierarchyNode.ExecCommandOnNode(Guid cmdGroup, UInt32 cmd, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\HierarchyNode.cs:line 1490

   at Microsoft.VisualStudioTools.Project.CommonFolderNode.ExecCommandOnNode(Guid cmdGroup, UInt32 cmd, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\CommonFolderNode.cs:line 120

   at Microsoft.PythonTools.Project.PythonFolderNode.ExecCommandOnNode(Guid cmdGroup, UInt32 cmd, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Project\PythonFolderNode.cs:line 56

   at Microsoft.VisualStudioTools.Project.ProjectNode.InternalExecCommand(Guid cmdGroup, UInt32 cmdId, UInt32 cmdExecOpt, IntPtr vaIn, IntPtr vaOut, CommandOrigin commandOrigin) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.IOleCommandTarget.cs:line 210

   at Microsoft.VisualStudioTools.Project.ProjectNode.ExecCommand(UInt32 itemId, Guid& guidCmdGroup, UInt32 nCmdId, UInt32 nCmdExecOpt, IntPtr pvain, IntPtr p) in C:\Projects\GitHub\huguesv\PTVS\Common\Product\SharedProject\ProjectNode.cs:line 5824

   at Microsoft.VisualStudio.Shell.Interop.IVsUIHierarchy.ExecCommand(UInt32 itemid, Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

   at Microsoft.Internal.VisualStudio.PlatformUI.HierarchyUtilities.<>c__DisplayClass35_0.<ExecHierParentChain>b__1()

   at Microsoft.VisualStudio.ErrorHandler.CallWithCOMConvention(Func`1 method, Boolean reportError, Boolean setShellErrorInfo)

   at Microsoft.Internal.VisualStudio.PlatformUI.HierarchyUtilities.ExecHierParentChain(IVsHierarchyItemManager manager, IVsUIHierarchy lpUIHCmd, IVsUIHierarchy lpUIHCurrent, UInt32 itemidCurrent, Guid& pguidCmdGroupRef, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

   at Microsoft.VisualStudio.PlatformUI.PivotNavigatorCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

   at Microsoft.VisualStudio.PlatformUI.SolutionNavigatorCommandTarget.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

   at Microsoft.VisualStudio.Shell.WindowPane.Microsoft.VisualStudio.OLE.Interop.IOleCommandTarget.Exec(Guid& guidGroup, UInt32 nCmdId, UInt32 nCmdExcept, IntPtr pIn, IntPtr vOut)

   at Microsoft.VisualStudio.Platform.WindowManagement.DocumentObjectSite.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)

   at Microsoft.VisualStudio.Platform.WindowManagement.WindowFrame.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)


---------------------------
Abort   Retry   Ignore   
---------------------------
```

```
---------------------------
Microsoft Visual Studio
---------------------------
Could not find a part of the path 'c:\users\huvalo\source\repos\PythonApplication37\PythonApplication37\A\B\'.
---------------------------
OK   
---------------------------
```

### PR DESCRIPTION
**Pull request by huguesv**
Fix #3225 

Also fixes cut/paste from Python to C#, where the file wasn't deleted in source Python project after paste was done.

Adjustments to the long file name tests where msbuild was refusing to load the project due to the project file path being too long (so I've made it slightly shorter and increased the length of the files within the project to get the same result).

Both sets of drag & drop tests are all passing.

### CODE REVIEW

File: Common/Product/SharedProject/ProjectNode.CopyPaste.cs [hunk 1]
```diff
@@ -786,45 +799,51 @@ class FolderAddition : Addition {
...
+                                // copying or moving an existing excluded folder, new folder
+                                // is excluded too.
+                                ErrorHandler.ThrowOnFailure(newNode.ExcludeFromProjectWithRefresh());
+                            } else if (sourceFolder.Parent.IsNonMemberItem) {
+                                // We've moved an included folder to a show all files folder,
+                                //     add the parent to the project   
+                                ErrorHandler.ThrowOnFailure(sourceFolder.Parent.IncludeInProjectWithRefresh(false));
+                            }
+
+                            if (DropEffect == DropEffect.Move) {
```
Comment (zooba) [inline Common/Product/SharedProject/ProjectNode.CopyPaste.cs]: How can we ever get here? The nested if conditions are `(sourceFolder == null || DropEffect != Move) && sourceFolder != null && DropEffect == Move`

Comment (huguesv) [reply Common/Product/SharedProject/ProjectNode.CopyPaste.cs]: Yeah you're right, it's not needed.
