### PR TITLE
Fixes #4247 Crash when saving diagnostics to file

### LINKED ISSUE #4274: Crash when saving diagnostics to file
From https://developercommunity.visualstudio.com/content/problem/259468/vs-1572-experimental-python-debugger-absolutely-no.html?childToView=261660#comment-261660

Crash caused VS to restart when choosing to save diagnostics log to file.

```
Application: devenv.exeFramework Version: v4.0.30319Description: The process was terminated due to an unhandled exception.Exception Info: System.NullReferenceException at 
Microsoft.PythonTools.Options.PythonDiagnosticsOptionsPage.SaveToFile(Boolean) at 
Microsoft.PythonTools.Options.PythonDiagnosticsOptionsControl._saveToFile_Click(System.Object, System.EventArgs) at System.Windows.Forms.Control.OnClick(System.EventArgs) at 
System.Windows.Forms.Button.OnClick(System.EventArgs) at 
System.Windows.Forms.Button.OnMouseUp(System.Windows.Forms.MouseEventArgs) at 
System.Windows.Forms.Control.WmMouseUp(System.Windows.Forms.Message ByRef, System.Windows.Forms.MouseButtons, Int32) at 
System.Windows.Forms.Control.WndProc(System.Windows.Forms.Message ByRef) at 
System.Windows.Forms.ButtonBase.WndProc(System.Windows.Forms.Message ByRef) at 
System.Windows.Forms.Button.WndProc(System.Windows.Forms.Message ByRef) at 
System.Windows.Forms.Control+ControlNativeWindow.OnMessage(System.Windows.Forms.Message ByRef) at 
System.Windows.Forms.Control+ControlNativeWindow.WndProc(System.Windows.Forms.Message ByRef) at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr, Int32, IntPtr, IntPtr) at 
Microsoft.VisualStudio.Shell.Interop.IVsUIDataSource.Invoke(System.String, System.Object, System.Object ByRef) at Microsoft.Internal.VisualStudio.PlatformUI.DataSource.Invoke(System.String, System.Object, System.Object ByRef) at Microsoft.VisualStudio.PlatformUI.VsCommand.Execute(System.Object) at 
MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(System.Windows.Input.ICommandSource, Boolean) at System.Windows.Controls.MenuItem.InvokeClickAfterRender(System.Object) at 
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at 
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at System.Windows.Threading.DispatcherOperation.InvokeImpl() at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object) at 
MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(System.Object) at 
System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at 
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean) at 
System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object) at 
MS.Internal.CulturePreservingExecutionContext.Run(MS.Internal.CulturePreservingExecutionContext, System.Threading.ContextCallback, System.Object) at 
System.Windows.Threading.DispatcherOperation.Invoke() at 
System.Windows.Threading.Dispatcher.ProcessQueue() at 
System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at 
MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef) at 
MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object) at 
System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32) at 
System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate) at 
System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32) at 
MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #4274 Crash when saving diagnostics to file
Ensures no null-reference errors can emerge from SaveToFile.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Options/PythonDiagnosticsOptionsPage.cs [hunk 1]
```diff
@@ -78,13 +78,20 @@ public class PythonDiagnosticsOptionsPage : PythonDialogPage {
...
                     Environment.GetFolderPath(Environment.SpecialFolder.MyDocuments),
                     Strings.DiagnosticsWindow_DefaultFileName.FormatUI(DateTime.Now)
-                )
+                );
+            } catch (Exception ex) when (!ex.IsCriticalException()) {
+                Debug.Fail(ex.ToUnhandledExceptionMessage(GetType()));
+            }
+
+            var path = Site.BrowseForFileSave(
+                _window?.Handle ?? IntPtr.Zero,
```
Comment (AlexanderSher) [inline Python/Product/PythonTools/PythonTools/Options/PythonDiagnosticsOptionsPage.cs]: `_window` can't be null, cause `SaveToFile` is added to `_window.SaveToFile` and this is the only way it can be called.

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Options/PythonDiagnosticsOptionsPage.cs]: Then this won't ever trigger, and no harm done.
