### PR TITLE
Show a message box with details in case of ptvsd ImportError

### LINKED ISSUE #3852: Debugging without ptvsd installed error message is confusing
1. For a windows app, they see this message box (nothing in output window like the message suggest)
```
---------------------------
Microsoft Visual Studio
---------------------------
Failed to launch debug adapter.  Additional information may be available in the output window.



Cannot process request because the process (8080) has exited.
---------------------------
OK   
---------------------------
```

2. For a console app, they see this in the console but the console automatically disappears after 5 secs
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\ptvsd_launcher.py", line 76, in <module>
    import ptvsd
ModuleNotFoundError: No module named 'ptvsd'

Internal error detected. Please copy the above traceback and report at
https://go.microsoft.com/fwlink/?LinkId=293415

Press Enter to close. . .

```

1) is pretty bad because they get no clue as to what is wrong.
2) is okay, but they only get 5 secs to read it (I guess they can F5 again until they've read it all)

We could give them some more info in both cases (please pip install ptvsd --pre in your Python environment in order to use the experimental debugger)

Later when it's bundled this may not be worth keeping, so not sure if it's 'too late' to do anything now.

### PR DESCRIPTION
**Pull request by karthiknadig**
Fixes #3852

### CODE REVIEW

**Comment by huguesv** [comment]
This code is common to both regular and experimental debugger, right? `pip install ptvsd --pre` won't help them if this ever happens with non-experimental debugger (that can happen in broken virtual environment like https://github.com/Microsoft/PTVS/issues/3687).

**Comment by zooba** [comment]
Really not thrilled about requiring `ctypes` right at the start, either. We should import that as late as possible and have a fallback.

Better yet, some back-channel to VS would be better and then display the message box from there. Can we get to the exit code?

File: Python/Product/Debugger/DebugAdapterProcess.cs [hunk 1]
```diff
@@ -178,6 +179,24 @@ sealed class DebugAdapterProcess :
...
+                // 126 : ERROR_MOD_NOT_FOUND
+                // This error code is returned only for the experimental debugger. MessageBox must be
+                // bound to the VS Main window otherwise it can be hidden behind the main window and the 
+                // user may not see it.
+                MessageBox.Show(
+                    new VSWin32Window(Process.GetCurrentProcess().MainWindowHandle),
+                    Strings.ImportPtvsdFailedMessage,
+                    Strings.ImportPtvsdFailedTitle,
+                    MessageBoxButtons.OK,
+                    MessageBoxIcon.Error);
```
Comment (zooba) [inline Python/Product/Debugger/DebugAdapterProcess.cs]: I'm okay with using a plain message box right now, as we intend to remove the need for it fairly soon (though we'll leave it here in case someone runs into a corrupt install).

A permanent error like this would be better as a TaskDialog that can trigger the action (in this case, install `--pre ptvsd` into the current environment).

File: Python/Product/Debugger/DebugAdapterProcess.cs [hunk 2]
```diff
@@ -178,6 +179,24 @@ sealed class DebugAdapterProcess :
             if (_stream != null) {
                 _stream.Dispose();
             }
+
+            if (_process.ExitCode == 126) {
```
Comment (huguesv) [inline Python/Product/Debugger/DebugAdapterProcess.cs]: What if debugging started successfully but the user's program exited with code 126? Can you do this only if debuggee didn't connect back?

Comment (karthiknadig) [reply Python/Product/Debugger/DebugAdapterProcess.cs]: sure i can restrict it.
