### PR TITLE
Bunch of minor fixes

### LINKED ISSUE #3551: Possible defects in the source code
Hi.
We've checked your project with [AppChecker static analyzer](https://npo-echelon.ru/en/solutions/appchecker.php) and found a several  possible defects:

1) [ModuleId.cs](https://github.com/Microsoft/PTVS/blob/ebfc4ca8bab234d453f15ee426af3b208f3c143c/Common/Product/SharedProject/Navigation/ModuleId.cs#L51-L52)
```
ModuleId other = obj as ModuleId;
if (null == obj) {
```
Most likely it's necessary to check 'other' variable to null:
```
ModuleId other = obj as ModuleId;
if (other == obj) {
```

2) [ExtractLambdasFromXaml.cs](https://github.com/Microsoft/PTVS/blob/ebfc4ca8bab234d453f15ee426af3b208f3c143c/Common/Tools/BuildTasks/ExtractLambdasFromXaml.cs#L257)

`if (typeAttributesConverter != null || typeAttributesConverter.CanConvertTo(typeof(string))) {`
if 'typeAttributesConverter' will be null, then method CanConvertTo will be invocated.
Probably, it should be:

`if (typeAttributesConverter != null && typeAttributesConverter.CanConvertTo(typeof(string))) {`

3) [IterableInfo.cs](https://github.com/Microsoft/PTVS/blob/6d10f259bcb3a3282cabfa8f616986aba13f27fd/Python/Product/Analysis/Values/IterableInfo.cs#L197)

`                if (si != null && !_node.Equals(_node)) {
`
_node is comared with itself.

Hope it was useful.

### PR DESCRIPTION
**Pull request by karthiknadig**
#3551

### CODE REVIEW

File: Python/Product/Analysis/Values/IterableInfo.cs [hunk 1]
```diff
@@ -178,7 +178,7 @@ public IterableValue(VariableDef[] indexTypes, BuiltinClassInfo seqType, Node no
         internal override bool UnionEquals(AnalysisValue ns, int strength) {
             if (strength < MergeStrength.IgnoreIterableNode) {
                 var si = ns as IterableValue;
-                if (si != null && !_node.Equals(_node)) {
```
Comment (huguesv) [inline Python/Product/Analysis/Values/IterableInfo.cs]: There's a chance that this obvious fix may unexpected side effects. Please run all tests in AnalysisTests project. We can compare failures (if any) with a branch without this fix.

**Comment by huguesv** [comment]
Please add link to the bug number in description (for future reference and also it will close it automatically)
