### PR TITLE
Bug fixes

### LINKED ISSUE #110: Fix ClassDef header index
The header index for ClassDef is inconsistent with FunctionDef.  It should point to the ':' and should be one more forward than it is.

Once Fixed fix the region collapsing to not need a + 1

Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs  
AddTagIfNecessary(node, node.HeaderIndex + 1, node.Decorators);

### PR DESCRIPTION
**Pull request by DinoV**
#110 Fix ClassDef header index
	Set header to always be the start of the :, always use the header index when generating the outlining tags
#923 Return annotation does not receive any syntax highlighting
	Just need to walk the retur annotation in FunctionDefinition
#1119 Cannot rename a file the same name that a missing file in Solution Explorer
	Make Remove return a bool so we can detect when it fails, check for open document, prompt to close/save,
	and remove the old item if we successfully remove the hierarchy node and the file doesn't get saved
#1195 Intellisense error with class method
	Need to write out that function is class method in saved analysis, and get rid of hacky static descriptor support
#56 Set next statement warning prompt regarding moving to a different function
	We weren’t saving the frame in the constructor, so when we’d go to compare the memory addresses we’d end up comparing by line #
#206 Copy paste item to another project's subfolder doesn't include file in project
	We were going to the current Python project, not consulting the source hierarchy, to check if we were a non-member item
#337 Cannot handle generalised unpacking
	Flush out generalized unpacking support at the parsing level, and add unit tests
#1210 Per-user interpreter not found when per-machine one exists
	Favor per-user interpreters over per-machine

### CODE REVIEW

File: Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs [hunk 1]
```diff
@@ -230,77 +221,90 @@ class CPythonInterpreterFactoryProvider : IPythonInterpreterFactoryProvider {
...
+                        RegisterInterpreters(machineFactories, registeredPaths, false, python64, ProcessorArchitecture.Amd64);
+                    }
+                }
+            }
+
+            // Then update our cached state with the lock held.
+            lock (this) {
+                var uniqueIds = userFactories.Select(x => x.Key)
+                       .Concat(machineFactories.Select(x => x.Key))
+                       .Distinct();
```
Comment (zooba) [inline Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs]: Put into a set to avoid multiple evaluations/breakage (if we later change userFactories or machineFactories in the first for loop)

You could also use `.Keys` instead of the `.Select`, right? And `.Union()` instead of `.Select().Distinct()`. Or maybe I'm missing something there.

File: Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs [hunk 2]
```diff
@@ -230,77 +221,90 @@ class CPythonInterpreterFactoryProvider : IPythonInterpreterFactoryProvider {
...
+
+                foreach (var id in uniqueIds) {
+                    InterpreterInformation newInfo;
+                    // User factories with the same ID take precedence over machine factories
```
Comment (zooba) [inline Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs]: We talked at one point about showing both and labelling them differently (though probably only if both exist). Something we want to try? Or save it for later?

File: Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs [hunk 3]
```diff
@@ -103,7 +103,7 @@ internal class OutliningTagger : ITagger<IOutliningRegionTag> {
 
                 var tags = await entry.Analyzer.GetOutliningTagsAsync(snapshot);
                 if (tags != null) {
-                    _tags = tags.Concat(ProcessRegionTags(snapshot)).ToArray();
+                    _tags = tags.Concat(ProcessRegionTags(_buffer.CurrentSnapshot)).ToArray();
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: Why would we want to use a different snapshot here?

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs [hunk 4]
```diff
@@ -1862,7 +1865,7 @@ class ExprWalker : PythonWalker {
                 }
 
                 yield return OutliningTaggerProvider.OutliningTagger.GetTagSpan(
-                    currentSnapshot,
+                    translator.TextBuffer.CurrentSnapshot,
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: I don't really like the idea of this potentially changing while enumerating... why do we want to make this change?

File: Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs (hunk 2 above)
Comment (DinoV) [inline Python/Product/VSInterpreters/CPythonInterpreterFactoryProvider.cs]: The difficultly there is actually with the IDs themselves...  If we want to do that we need to have that show up in the interpreter ID, so that we'd end up with something like:
Global|PythonCore|3.5|x86|User
 or
Global|PythonCore|3.5|x86|Machine

Or something along those lines.  My current thinking is that will cause more trouble in cross machine scenarios then it's worth enabling users to have both a per-user and per-machine install.

File: Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs (hunk 3 above)
Comment (DinoV) [inline Python/Product/PythonTools/PythonTools/OutliningTaggerProvider.cs]: The issue here is that the buffer may have been modified during the await call.  So we capture the current snapshot which holds the earliest possible version we need to translate from.  But then we need to apply the changes to the current version, not the earliest possible version.

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs (hunk 4 above)
Comment (DinoV) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: Yeah, I'll hoist that to a local at the start of the function, the important thing is that we get the current snapshot when we entered this function
