### PR TITLE
make sure we are on the UIThread before calling GetPythonToolsServer()

### LINKED ISSUE #6227: CondaLocatorProvider calling GetPythonToolsService from non UI thread
**Describe the bug**
[A clear and concise description of the bug]

**Steps to Reproduce**
1. create a new conda environment	
2. using the package manager to install a package. ie. ipykenerl
3.

**Expected behavior**
[A clear and concise description of your expectation]

**Additional context and screenshots**
[Add any other information such as screenshots, error message, or stack trace]
image

**Sample Code**
```
XXX
```

**Configuration information (If you are providing a diagnostics file (see below), skip this section)**
VS Version: [Can be found under "Help->About Microsoft Visual Studio"]
PTVS version: [Can be found under "Help->About Microsoft Visual Studio->Installed products"]
Python version:
Debugger Type (if applicable): [New debugger or legacy debugger?]

**Diagnostics file**
The diagnostics file contains information such as the Python version, environments, loaded assemblies, configuration options, etc. This file makes it easier for us to reproduce and fix bugs, so we would really appreciate it if you could provide it to us. This file can be generated by going to Tools->Options->Python->Diagnostics.
You can attach the file to this issue or email it to us at ptvshelp@microsoft.com. If you email it, please add a link to this issue.
```
XXX
```

### PR DESCRIPTION
**Pull request by bschnurr**
fix #6227

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Environments/UserSpecifiedCondaLocator.cs [hunk 1]
```diff
@@ -40,7 +41,9 @@ sealed class UserSpecifiedCondaLocator : ICondaLocator {
 
         public string CondaExecutablePath {
             get {
-                return _site?.GetPythonToolsService()?.CondaOptions.CustomCondaExecutablePath;
+                return _site.GetUIThread().Invoke(() =>
```
Comment (bschnurr) [inline Python/Product/PythonTools/PythonTools/Environments/UserSpecifiedCondaLocator.cs:44]: i forgot the "?"
