### PR TITLE
Fixes #1502 Invalid cross-thread calls

### LINKED ISSUE #1502: Invalid cross thread call when start debugging
I used the debug repl during my previous debug session,  When I hit F5 the next time, I got this assert.

```
---------------------------
Assertion Failed: Abort=Quit, Retry=Debug, Ignore=Continue
---------------------------
Invalid cross-thread call



   at Microsoft.VisualStudioTools.VsExtensions.MustBeCalledFromUIThread(UIThreadBase self, String message) in C:\Projects\huguesv\PTVS\Common\Product\SharedProject\VsExtensions.cs:line 109

   at Microsoft.PythonTools.Extensions.GetPythonToolsService(IServiceProvider serviceProvider) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 655

   at Microsoft.PythonTools.Repl.PythonInteractiveEvaluator.set_CurrentWindow(IInteractiveWindow value) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonInteractiveEvaluator.cs:line 231

   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.AttachProcess(PythonProcess process, IThreadIdMapper threadIdMapper) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonDebugReplEvaluator.cs:line 405

   at Microsoft.PythonTools.Repl.PythonDebugReplEvaluator.OnEngineAttached(Object sender, AD7EngineEventArgs e) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Repl\PythonDebugReplEvaluator.cs:line 374

   at Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.SendLoadComplete(AD7Thread thread) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7Engine.cs:line 401

   at Microsoft.PythonTools.Debugger.DebugEngine.AD7Engine.OnProcessLoaded(Object sender, ThreadEventArgs e) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\DebugEngine\AD7Engine.cs:line 1356

   at Microsoft.PythonTools.Debugger.PythonProcess.HandleProcessLoad(Stream stream) in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 830

   at Microsoft.PythonTools.Debugger.PythonProcess.DebugEventThread() in C:\Projects\huguesv\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 458

   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)

   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)

   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)

   at System.Threading.ThreadHelper.ThreadStart()


---------------------------
Abort   Retry   Ignore   
---------------------------

```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1502 Invalid cross-thread calls
Adds UI thread marshalling.
Also fixes null reference exception opening debug REPL
Fixes potential analysis crash due to invalid version number

### CODE REVIEW

File: Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs [hunk 1]
```diff
@@ -281,10 +281,14 @@ sealed class OutOfProcProjectAnalyzer : IDisposable {
...
-                ReloadTask = _pyAnalyzer.ReloadModulesAsync()/*.HandleAllExceptions(_serviceProvider, GetType())*/;
-                ReloadTask.ContinueWith(_ => ReloadTask = null);
-                interpreter.ModuleNamesChanged += OnModulesChanged;
+                try {
+                    _pyAnalyzer = PythonAnalyzer.Create(factory, interpreter);
+                    ReloadTask = _pyAnalyzer.ReloadModulesAsync()/*.HandleAllExceptions(_serviceProvider, GetType())*/;
+                    ReloadTask.ContinueWith(_ => ReloadTask = null);
+                    interpreter.ModuleNamesChanged += OnModulesChanged;
+                } catch (InvalidOperationException ex) {
+                    error = ex.ToString();
```
Comment (huguesv) [inline Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: Is that meant to be removed (you don't do anything with `error` after this block)?

Comment (huguesv) [inline Python/Product/Analyzer/Intellisense/OutOfProcProjectAnalyzer.cs]: oops, forget that, I had to expand to see it 2 lines below.

**Comment by huguesv** [comment]
👍
