### PR TITLE
Output the error when git is not installed or not on the PATH

### LINKED ISSUE #6872: Cannot use Cookiecutter to load template.
**Describe the bug**

image

**Steps to Reproduce**

1. Open Cookiecutter Explorer.
2. Load the following template: https://github.com/brettcannon/python-azure-web-app-cookiecutter 

**Expected behavior**

The Template loaded successfully.

**Additional context and screenshots**

Error cloning the repository.
BTW, load the template from the "Recommended" section, you can repro it.

**Output info**
```
----- Cloning template 'https://github.com/brettcannon/python-azure-web-app-cookiecutter' -----
The system cannot find the file specified
A task was canceled.
----- Failed to clone template 'https://github.com/brettcannon/python-azure-web-app-cookiecutter' -----
```

### PR DESCRIPTION
**Pull request by StellaHuang95**
fixes #6872 

Print out the error when user fails to clone Cookiecutter templates because git is not installed or not on the PATH.

Here's what happens after the fix:

When git is installed and on the PATH:
Animation2 - with git

When it's not installed or on the PATH:
Animation2 - without git

### CODE REVIEW

File: Python/Product/Cookiecutter/Model/GitClient.cs [hunk 1]
```diff
@@ -52,6 +52,9 @@ class GitClient : IGitClient {
             }
 
             var arguments = new string[] { "clone", repoUrl };
+            if (!ExistsOnPath(_gitExeFilePath)) {
+                throw new FileNotFoundException();
```
Comment (AdamYoblick) [inline Python/Product/Cookiecutter/Model/GitClient.cs]: As Pavel mentioned offline, it would be better to run `git verion` to make sure git can actually run. No need to check the path.

Also, I believe VS now comes with git built in, so using assuming git.exe is on the path no longer seems necessary, we can just use the one that comes with VS. But if you don't want to make that change, I'm fine with just trying to run git.

File: Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs [hunk 2]
```diff
@@ -843,6 +843,9 @@ class CookiecutterViewModel : INotifyPropertyChanged {
                     CloningStatus = OperationStatus.Failed;
 
                     _outputWindow.WriteErrorLine(ex.Message);
+                    if (ex.GetType().Name == "FileNotFoundException") {
```
Comment (AdamYoblick) [inline Python/Product/Cookiecutter/ViewModel/CookiecutterViewModel.cs]: No need to do this extra work. Just throw an exception and include the error string within it, like this: `throw new Exception(Strings.GitNotFoundError)`. Then like 845 will print the error message you need and you can get rid of this entire code block you added.

**Review by AdamYoblick — APPROVED** [review]

File: Python/Product/Cookiecutter/Model/GitClient.cs [hunk 3]
```diff
@@ -82,6 +91,29 @@ class GitClient : IGitClient {
             }
         }
 
+        public bool canRunGit(string exe) {
```
Comment (AdamYoblick) [inline Python/Product/Cookiecutter/Model/GitClient.cs:94]: Methods should be in PascalCase. Please rename to `CanRunGit`.

Comment (AdamYoblick) [reply Python/Product/Cookiecutter/Model/GitClient.cs:94]: Also there's probably no need for this method to be `public`. Please make it `private`. It can also be `static` because it doesn't interact with any instance members.

File: Python/Product/Cookiecutter/Model/GitClient.cs [hunk 4]
```diff
@@ -52,8 +53,13 @@ class GitClient : IGitClient {
...
             var arguments = new string[] { "clone", repoUrl };
-            if (!ExistsOnPath(_gitExeFilePath)) {
-                throw new FileNotFoundException();
+            try {
+                // check if it's actually git
+                if(!canRunGit(_gitExeFilePath)) {
+                    throw new GitRunException(Strings.GitFailedToRunError);
+                }
+            } catch (Exception) {
+                throw new GitRunException(Strings.GitFailedToRunError);
```
Comment (int19h) [inline Python/Product/Cookiecutter/Model/GitClient.cs:62]: This should include the original exception as the inner exception for the one that it throws. This way, if it escapes and gets reported in a log, the full context is available.

File: Python/Product/Cookiecutter/Model/GitClient.cs [hunk 5]
```diff
@@ -83,25 +89,31 @@ class GitClient : IGitClient {
...
-            if (File.Exists(fileName)) {
-                return Path.GetFullPath(fileName);
-            }
-            var values = Environment.GetEnvironmentVariable("PATH");
-            foreach (var path in values.Split(Path.PathSeparator)) {
-                var fullPath = Path.Combine(path, fileName);
-                if (File.Exists(fullPath))
-                    return fullPath;
+        public bool canRunGit(string exe) {
+            var process = new Process {
```
Comment (int19h) [inline Python/Product/Cookiecutter/Model/GitClient.cs:95]: `Process` is disposable, so this needs a `using` variable declaration or block to ensure cleanup.

**Review by int19h — APPROVED** [review]
