### PR TITLE
Prevent crash when the root scripts path or the environment name have invalid path characters.

### LINKED ISSUE #4294: Configuring IronPython
[Window Title]
devenv.exe

[Main Instruction]
发生意外错误

[Content]
请按 Ctrl+C 复制此对话框的内容并向我们的问题跟踪程序报告此错误。

[^] 隐藏详细信息(D)  [关闭(C)]

[Expanded Information]
```
Build: 15.7.18131.1

System.ArgumentException: 路径中具有非法字符。
   在 System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPathLength, Boolean expandShortPaths)
   在 System.IO.Path.GetFullPathInternal(String path)
   在 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   在 System.IO.Directory.CreateDirectory(String path)
   在 Microsoft.PythonTools.InterpreterList.InterpreterListToolWindow.EnsureScriptDirectory(String path)
```

### PR DESCRIPTION
**Pull request by huguesv**
Fix #4294

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs [hunk 1]
```diff
@@ -401,6 +404,10 @@ internal abstract class PythonCommonInteractiveEvaluator :
 
             string candidate;
             if (!string.IsNullOrEmpty(displayName)) {
+                foreach (var c in Path.GetInvalidFileNameChars()) {
+                    displayName = displayName.Replace(c, '_');
```
Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs]: Is this better than simply removing the characters?

Comment (huguesv) [reply Python/Product/PythonTools/PythonTools/Repl/PythonCommonInteractiveEvaluator.cs]: I feel it's more readable.
