### PR TITLE
Issue 1616

### LINKED ISSUE #1616: PEP 526 syntax support
[PEP 526](https://www.python.org/dev/peps/pep-0526/) adds syntax support for variable annotations.

We need to handle this syntax to avoid the parser breaking on user's code.

Supporting type annotations is still covered by #82 - this issue is just for the broken parser.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1616
Adds support for PEP 526 and PEP 498 syntax parsing and round-trip. Analysis is not yet implemented.

### CODE REVIEW

File: Python/Product/Analysis/Parsing/Parser.cs [hunk 1]
```diff
@@ -864,6 +954,15 @@ struct Name {
         private Statement ParseExprStmt() {
             Expression ret = ParseTestListAsExpr();
 
+            if (PeekToken(TokenKind.Colon) && _langVersion >= PythonLanguageVersion.V36) {
+                ret = ParseNameAnnotation(ret);
+                if (!PeekToken(TokenKind.Assign)) {
```
Comment (DinoV) [inline Python/Product/Analysis/Parsing/Parser.cs]: The else should be handled here as well, otherwise you can do "foo: int = 2 = 3" which doesn't appear to be legal

File: Python/Tests/TestData/Grammar/VarAnnotation.py [hunk 2]
```diff
@@ -0,0 +1,10 @@
+fob : oar
+fob : oar = 1
+
+class C:
+    fob : oar
+    fob : oar = 1
```
Comment (DinoV) [inline Python/Tests/TestData/Grammar/VarAnnotation.py]: Member expressions: C.fob : int = 1
Indicies: x[0] : int

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 3]
```diff
@@ -4301,6 +4317,34 @@ class C:
         }
 
         [TestMethod, Priority(0)]
+        public void AnnotatedAssign() {
```
Comment (DinoV) [inline Python/Tests/Analysis/AnalysisTest.cs]: "Annotating a local variable will cause the interpreter to treat it as a local, even if it was never assigned to. Annotations for local variables will not be evaluated"
x = 1
def f():
    x: int

Type of inner x should be unknown (I suspect we fail this)

File: Python/Product/Analysis/Parsing/Ast/ExpressionWithAnnotation.cs [hunk 4]
```diff
@@ -0,0 +1,64 @@
...
+        public Expression Annotation => _annotation;
+
+        public override string NodeName => "annotated expression";
+
+        internal override string CheckAssign() => null;
+        internal override string CheckAugmentedAssign() => "cannot assign to " + NodeName;
+        internal override string CheckDelete() => "cannot delete " + NodeName;
+
+        public override void Walk(PythonWalker walker) {
+            _expression.Walk(walker);
```
Comment (DinoV) [inline Python/Product/Analysis/Parsing/Ast/ExpressionWithAnnotation.cs]: if(walker.Walk(this)) {
}
walker.PostWalk(this);

PythonWalker also needs to be updated with an overload for this

File: Python/Tests/TestData/Grammar/VarAnnotation.py (hunk 2 above)
Comment (DinoV) [inline Python/Tests/TestData/Grammar/VarAnnotation.py]: Member expressions: C.fob : int = 1
Indicies: x[0] : int

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 5]
```diff
@@ -4301,6 +4317,34 @@ class C:
...
+
+    def func(self):
+        self.abc : int = 42
+
+a = C()
+a.func()
+fob1 = a.abc
+fob2 = a.y
+fob3 = x
+";
```
Comment (DinoV) [inline Python/Tests/Analysis/AnalysisTest.cs]: def f(val):
    print(val)

x: f(42)

val should be known to be an int
----
def f(val):
    print(val)

class C:
    y : f(42)

val should be known to be an int
---

def f(val):
    print(val)

def g():
    x : f(42)

val should have no type

File: Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs [hunk 6]
```diff
@@ -446,6 +446,10 @@ internal class ExpressionEvaluator {
         }
 
         internal void AssignTo(Node assignStmt, Expression left, IAnalysisSet values) {
+            if (left is ExpressionWithAnnotation) {
+                left = ((ExpressionWithAnnotation)left).Expression;
+            }
+
             if (left is NameExpression) {
                 var l = (NameExpression)left;
```
Comment (DinoV) [inline Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs]: You probably need to handle ExpressionWithAnnotation for walking somewhere in here, and evaluate the annotation if we're in a class or module scope (but not a local scope).

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 7]
```diff
@@ -2128,6 +2128,22 @@ public VariableLocation(int startLine, int startCol, VariableType type, string f
             AssertUtil.ContainsExactly(entry.GetTypeIdsByIndex("oar2", text.IndexOf("oar2 =")), BuiltinTypeId.Unicode);
         }
 
+        [TestMethod, Priority(0)]
+        public void StringFormattingV36() {
+            var text = @"
+y = f'abc {42}'
+ry = rf'abc {42}'
+yr = fr'abc {42}'
+fadd = f'abc{42}' + f'{42}'
```
Comment (DinoV) [inline Python/Tests/Analysis/AnalysisTest.cs]:
```
def f(val):
    print(val)
f'abc {f(42)}'
```

val should be 42 (if you're not going to actually implement this you could leave it commented out)

File: Python/Tests/Analysis/ParserTests.cs [hunk 8]
```diff
@@ -2653,6 +2669,40 @@ public class ParserTests {
             }
         }
 
+        [TestMethod, Priority(0)]
```
Comment (DinoV) [inline Python/Tests/Analysis/ParserTests.cs]: Formatted string test, plus errors:
f'x={x'
f'x={!x}'

File: Python/Product/Analysis/Parsing/Parser.cs (hunk 1 above)
Comment (zooba) [inline Python/Product/Analysis/Parsing/Parser.cs]: Actually needs to be further below, but point taken.

File: Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs (hunk 6 above)
Comment (zooba) [inline Python/Product/Analysis/Analyzer/ExpressionEvaluator.cs]: We actually never evaluate the LHS of an assignment statement... I wonder how much will break if I enable that...

File: Python/Tests/Analysis/ParserTests.cs (hunk 8 above)
Comment (zooba) [inline Python/Tests/Analysis/ParserTests.cs]: Currently we don't parse the content at all - we simply ignore the prefix and treat it like a regular string. (This is actually how Python handles it as well, which is suboptimal, but not trivial to solve right now...)
