### PR TITLE
Fixes #2727 Editors opened by LSL are not associated with the project

### LINKED ISSUE #2727: Editors opened by LSL are not associated with the project
When you open a solution with lightweight solution load enabled, existing editor windows are opened before our project loads. As a result, we do not associate these windows with the project and they will have incorrect settings (language version, search paths, etc.)

We should search for any open windows on project load and reassociate them with our project automatically.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #2727 Editors opened by LSL are not associated with the project
Updates open editors on project reanalysis to ensure they are associated with the correct project
Ensures squiggles are cleared.
Prevents overlapping asynchronous requests to out-of-proc analyzer.
Prevents unnecessary notifications after disconnecting a buffer parser
Some minor code cleaning.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs [hunk 1]
```diff
@@ -2264,9 +2341,19 @@ class ExprWalker : PythonWalker {
                 fileId = analysis.Entry.FileId,
             };
 
-            var resp = await analysis.Entry.Analyzer.SendRequestAsync(req, timeout: timeout).ConfigureAwait(false);
-
-            return resp?.expression;
+            return analysis.Entry.Analyzer.EnsureSingleRequest(
+                typeof(AP.ExpressionForDataTipRequest),
+                req.expr,
+                t => t == req.expr,
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: Shouldn't it also compare the location? What if it's 2 different request for tooltips for the same expression, but in different locations which would produce different results?

Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: Yeah, it probably should. That's very unlikely to happen in reality (VS only supports one data tip at a time), but I could see it coming up in the test suite.

**Comment by zooba** [comment]
@huguesv Fixed the key you commented on. If there's nothing else that concerns you, please hit merge whenever you like.
