### PR TITLE
Fix #576, #995, and a couple of other small fixes

### LINKED ISSUE #576: IronPython .NET constructors and Intellisense failure
IronPython 2.7.5, PTVS 2.2RC and VS 2013 Desktop

To inherit from a C# class and call a specific base class constructor the IronPython docs say

```
.NET constructors can be overloaded.
 To call a specific base type constructor overload, you need to define a
 __new__  method (not __init__) and call __new__ on the .NET base type.
```

Assuming CSharpTest has multiple constructors and I want to call a specific one this, as recommended, works but gives no Intellisense on c

```
class Child (CSharpTest):
    def __new__(cls):
        instance = CSharpTest.__new__(cls, "one", "two")
        return instance

c = Child()
``` 
  
But if I call the C# constructor directly it also works and I get Intellisense on c.

```
class Child (CSharpTest):
    def __new__(cls):
        instance = CSharpTest("one", "two")
        return instance

c = Child()
``` 
 
It looks like Intellisense can’t track through __new__ to see what the resulting type is. I don't know if this is an IronPython documentation failure (why bother going through  __new__ if calling the constructor directly works) or something that Intellisense doesn't, or can't, do.

Sorry about the formatting  of__ new__ in the last paragraph. It should be double underscore+ "new"+double underscore but I can't see how to override the markdown without putting the text in a code block :(

### PR DESCRIPTION
**Pull request by DinoV**

### CODE REVIEW

File: Python/Product/Analysis/Analyzer/InterpreterScope.cs [hunk 1]
```diff
@@ -290,8 +290,11 @@ public InterpreterScope(AnalysisValue av, InterpreterScope outerScope)
             _nodeScopes.Clear();
         }
 
-        public virtual IAnalysisSet AddNodeValue(Node node, IAnalysisSet variable) {
-            return _nodeValues[node] = variable;
+        public virtual IAnalysisSet AddNodeValue(Node node, NodeValueKind kind, IAnalysisSet variable) {
+            NodeValue next;
+            _nodeValues.TryGetValue(node, out next);
+            _nodeValues[node] = new NodeValue(kind, variable, next);
```
Comment (zooba) [inline Python/Product/Analysis/Analyzer/InterpreterScope.cs]: I assume we "never" end up with many entries in here for the same kind, but can we assert that? Could become a memory issue, and certainly could affect Get performance if we end up with 1000s of one kind at the start.

Also, is adding the bottleneck, or is getting? I'd have thought getting, so it may be better to just use a regular list than invent a linked list.

File: Python/Product/Analysis/Values/FunctionInfo.cs [hunk 2]
```diff
@@ -499,23 +499,25 @@ private class StringArrayComparer : IEqualityComparer<string[]> {
             varRef.AddTypes(unit, value);
         }
 
-        public override IAnalysisSet GetMember(Node node, AnalysisUnit unit, string name) {
-            // Must unconditionally call the base implementation of GetMember
-            var ignored = base.GetMember(node, unit, name);
```
Comment (zooba) [inline Python/Product/Analysis/Values/FunctionInfo.cs]: Make sure we haven't lost references as a result of removing this.

File: Python/Product/Analysis/Values/InstanceInfo.cs [hunk 3]
```diff
@@ -149,9 +149,6 @@ internal class InstanceInfo : AnalysisValue, IReferenceableContainer {
         }
 
         public override IAnalysisSet GetMember(Node node, AnalysisUnit unit, string name) {
-            // Must unconditionally call the base implementation of GetMember
-            var ignored = base.GetMember(node, unit, name);
```
Comment (zooba) [inline Python/Product/Analysis/Values/InstanceInfo.cs]: Make sure we haven't lost references as a result of doing this.

File: Python/Product/Analysis/Values/PartialFunctionInfo.cs [hunk 4]
```diff
@@ -102,8 +102,7 @@ class PartialFunctionInfo : AnalysisValue {
         }
 
         public override IAnalysisSet GetMember(Node node, AnalysisUnit unit, string name) {
-            // Must unconditionally call the base implementation of GetMember
-            var res = base.GetMember(node, unit, name);
```
Comment (zooba) [inline Python/Product/Analysis/Values/PartialFunctionInfo.cs]: Make sure we haven't lost references.

File: Python/Product/Analysis/Values/SuperInfo.cs [hunk 5]
```diff
@@ -80,9 +80,6 @@ internal class SuperInfo : AnalysisValue {
         }
 
         public override IAnalysisSet GetMember(Node node, AnalysisUnit unit, string name) {
-            // Must unconditionally call the base implementation of GetMember
-            var ignored = base.GetMember(node, unit, name);
```
Comment (zooba) [inline Python/Product/Analysis/Values/SuperInfo.cs]: Make sure we haven't lost references.

File: Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs [hunk 6]
```diff
@@ -126,7 +126,8 @@ class IronPythonInterpreter :
         }
 
 #if DEBUG
-        class AssertListenerInitializer {
+        [Serializable]
+        class AssertListenerInitializer : MarshalByRefObject {
```
Comment (zooba) [inline Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs]: Probably shouldn't be both serializable and MarshalByRef. Why change it?

File: Python/Templates/IronPython/ProjectTemplates/Python/ConsoleProject/ConsoleProject.pyproj [hunk 7]
```diff
@@ -24,7 +24,7 @@
     <None Include="$safeprojectname$.py" />
   </ItemGroup>
   <ItemGroup>
-    <InterpreterReference Include="{80659ab7-4d53-4e0c-8588-a766116cbd46}\2.7" />
+    <InterpreterReference Include="IronPython|2.7 32-bit" />
```
Comment (zooba) [inline Python/Templates/IronPython/ProjectTemplates/Python/ConsoleProject/ConsoleProject.pyproj]: Can we use "-32" as the suffix for 32-bit rather than having a space in there? It _should_ be fine, but I've learned to be wary of spaces in identifiers.

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 8]
```diff
@@ -3761,6 +3761,141 @@ class fob(dict):
...
+
+a = setdict()
+a[42] = 100
+b = a[42]
+
+pass
+";
+            var entry = ProcessText(text);
+            var items = entry.GetTypesByIndex("b", text.IndexOf("pass"));
+            Assert.IsTrue(items.Count() == 0);
```
Comment (zooba) [inline Python/Tests/Analysis/AnalysisTest.cs]: `AssertUtil.ContainsExactly(items)` here has the nice side-effect of showing what is in the collection when it does contain something.

File: Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs (hunk 6 above)
Comment (zooba) [inline Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs]: Misread the diff - I thought this was previously MarshalByRef.

The important thing to ensure here is that the listener is added within the appdomain. My understanding was that Serializable will achieve that (as the listener should be MarshalByRef), but marshalling the initializer will just add the listener in the original appdomain again.

File: Python/Product/Analysis/Analyzer/InterpreterScope.cs (hunk 1 above)
Comment (DinoV) [inline Python/Product/Analysis/Analyzer/InterpreterScope.cs]: Correct, at most we'll currently end up with 2.  That open happens when we have a subclass of dict.  In NTVS I did something similar but that still had a Dictionary<TKey, TValue> for storing these so the kind was encoded in a struct with the node.  Because this has switched to AnalysisDictionary (presumably to fix a thread safety issue at some point) I didn't want to allocate a reference on all of the gets.  But we're bounded here by the number of NodeValueKind's, and even then the kinds would need to be started being used across many nodes to collide.

File: Python/Product/Analysis/Values/FunctionInfo.cs (hunk 2 above)
Comment (DinoV) [inline Python/Product/Analysis/Values/FunctionInfo.cs]: The base class implementation doesn't do anything anymore, so at some point these comments just became stale.

File: Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs (hunk 6 above)
Comment (DinoV) [inline Python/Product/IronPython/Interpreter/IronPythonInterpreter.cs]: I'll just make it serializable, I'm not sure how this ever worked, I just ran into the exception while debugging something else.

File: Python/Product/Analysis/Analyzer/InterpreterScope.cs (hunk 1 above)
Comment (zooba) [inline Python/Product/Analysis/Analyzer/InterpreterScope.cs]: I'm more worried about hitting a case where we incorrectly keep adding a node value against the same node with the same type, without checking whether it already exists (possibly some time in the future when someone else calls this). Maybe making it a GetOrAddNodeValue() function would address that?

File: Python/Tests/Analysis/AnalysisTest.cs [hunk 9]
```diff
@@ -3860,7 +3860,7 @@ class setdict(dict):
 ";
             var entry = ProcessText(text);
             var items = entry.GetTypesByIndex("b", text.IndexOf("pass"));
-            Assert.IsTrue(items.Count() == 0);
+            AssertUtil.ContainsExactly(items);
```
Comment (zooba) [inline Python/Tests/Analysis/AnalysisTest.cs]: Same applies a few more times further down.

File: Python/Product/Analysis/Analyzer/InterpreterScope.cs (hunk 1 above)
Comment (DinoV) [inline Python/Product/Analysis/Analyzer/InterpreterScope.cs]: That's actually the pattern here...  There's a GetOrMakeNodeValue which everyone uses.  AddNodeValue exists solely for consumption by GetOrMakeNodeValue.  Unfortunately we can't quite get the visibility right on this because derived scopes (comprehension, and is instance) override this and forward it to the real scope.  But if we declare it as protected we can't dispatch to the outer scope one on the base type.

Comment (zooba) [inline Python/Product/Analysis/Analyzer/InterpreterScope.cs]: So is a debug assertion going to help ensure we stick to that pattern?
