### PR TITLE
Fix duplicate test discovery again 

### LINKED ISSUE #3992: Too many test discoveries
Open test explorer.
Create new python application project.
Add new item, python unit test.
Wait for test discovery to settle down.
Add a new test (type it in manually)
```
    def test_123456789012345678901234567890(self):
        pass
```

If you type quickly enough, you'll notice test discovery only triggers once you are done writing the test method.

However, if you look at the output window (tests pane), you'll see that this triggers about 40 discoveries! That's about the number of characters typed past `def test`.

The worst thing about this is that you have to wait for all the discoveries to be finished before  Run Test command becomes available. This takes several seconds.

```
[4/3/2018 2:38:15 PM Informational] ------ Load Playlist started ------
[4/3/2018 2:38:15 PM Informational] ========== Load Playlist finished (0:00:00) ==========
[4/3/2018 2:38:25 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:25 PM Informational] ========== Discover test finished: 1 found (0:00:00.7410897) ==========
[4/3/2018 2:38:28 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:29 PM Informational] ========== Discover test finished: 1 found (0:00:00.8517383) ==========
[4/3/2018 2:38:41 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:42 PM Informational] ========== Discover test finished: 2 found (0:00:00.748115) ==========
[4/3/2018 2:38:42 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:42 PM Informational] ========== Discover test finished: 2 found (0:00:00.6697155) ==========
[4/3/2018 2:38:42 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:43 PM Informational] ========== Discover test finished: 2 found (0:00:00.6557678) ==========
[4/3/2018 2:38:43 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:44 PM Informational] ========== Discover test finished: 2 found (0:00:00.7070301) ==========
[4/3/2018 2:38:44 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:44 PM Informational] ========== Discover test finished: 2 found (0:00:00.6423277) ==========
[4/3/2018 2:38:45 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:46 PM Informational] ========== Discover test finished: 2 found (0:00:01.217691) ==========
[4/3/2018 2:38:46 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:47 PM Informational] ========== Discover test finished: 2 found (0:00:00.7137796) ==========
[4/3/2018 2:38:47 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:47 PM Informational] ========== Discover test finished: 2 found (0:00:00.7170312) ==========
[4/3/2018 2:38:47 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:48 PM Informational] ========== Discover test finished: 2 found (0:00:00.8259164) ==========
[4/3/2018 2:38:48 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:49 PM Informational] ========== Discover test finished: 2 found (0:00:00.5703357) ==========
[4/3/2018 2:38:49 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:50 PM Informational] ========== Discover test finished: 2 found (0:00:00.7590932) ==========
[4/3/2018 2:38:50 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:50 PM Informational] ========== Discover test finished: 2 found (0:00:00.6411297) ==========
[4/3/2018 2:38:50 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:51 PM Informational] ========== Discover test finished: 2 found (0:00:00.6373501) ==========
[4/3/2018 2:38:51 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:52 PM Informational] ========== Discover test finished: 2 found (0:00:00.7151682) ==========
[4/3/2018 2:38:52 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:53 PM Informational] ========== Discover test finished: 2 found (0:00:00.6865521) ==========
[4/3/2018 2:38:53 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:53 PM Informational] ========== Discover test finished: 2 found (0:00:00.6352225) ==========
[4/3/2018 2:38:53 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:54 PM Informational] ========== Discover test finished: 2 found (0:00:00.6082206) ==========
[4/3/2018 2:38:54 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:55 PM Informational] ========== Discover test finished: 2 found (0:00:00.6658105) ==========
[4/3/2018 2:38:55 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:55 PM Informational] ========== Discover test finished: 2 found (0:00:00.573785) ==========
[4/3/2018 2:38:55 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:56 PM Informational] ========== Discover test finished: 2 found (0:00:00.7749914) ==========
[4/3/2018 2:38:56 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:57 PM Informational] ========== Discover test finished: 2 found (0:00:00.6973196) ==========
[4/3/2018 2:38:57 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:58 PM Informational] ========== Discover test finished: 2 found (0:00:01.0140674) ==========
[4/3/2018 2:38:58 PM Informational] ------ Discover test started ------
[4/3/2018 2:38:59 PM Informational] ========== Discover test finished: 2 found (0:00:01.0781487) ==========
[4/3/2018 2:38:59 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:00 PM Informational] ========== Discover test finished: 2 found (0:00:00.6553737) ==========
[4/3/2018 2:39:00 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:01 PM Informational] ========== Discover test finished: 2 found (0:00:00.7240872) ==========
[4/3/2018 2:39:01 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:01 PM Informational] ========== Discover test finished: 2 found (0:00:00.6215982) ==========
[4/3/2018 2:39:01 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:02 PM Informational] ========== Discover test finished: 2 found (0:00:00.6401284) ==========
[4/3/2018 2:39:02 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:03 PM Informational] ========== Discover test finished: 2 found (0:00:00.6550697) ==========
[4/3/2018 2:39:03 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:03 PM Informational] ========== Discover test finished: 2 found (0:00:00.5926676) ==========
[4/3/2018 2:39:03 PM Informational] ------ Discover test started ------
[4/3/2018 2:39:04 PM Informational] ========== Discover test finished: 2 found (0:00:00.9964458) ==========
```

### PR DESCRIPTION
**Pull request by huguesv**
Previous fix (https://github.com/Microsoft/PTVS/pull/3979) was breaking the pending/submit mechanism.

Fix #3992 Too many test discoveries

### CODE REVIEW

File: Python/Product/TestAdapter/TestContainerDiscoverer.cs [hunk 1]
```diff
@@ -267,7 +265,7 @@ await PendOrSubmitRequests(e.Path)
                 var testCaseData = await analyzer.SendExtensionCommandAsync(
                     TestAnalyzer.Name,
                     TestAnalyzer.GetTestCasesCommand,
-                    string.Join(";", paths)
+                    string.Join(";", paths.Distinct())
```
Comment (AlexanderSher) [inline Python/Product/TestAdapter/TestContainerDiscoverer.cs]: You may want to specify equality comparer
