### PR TITLE
Fixes #1599: Error trying to update 2+ python libs

### LINKED ISSUE #1599: Error trying update 2+ python libs in VS15 Preview 4, Python Environments.
Upgrade method asked for rights elevation first time but becomes silent for next library. First library is  updated successfully and second one failed.

[Window Title]
Python Tools for Visual Studio

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Закрыть]

[Expanded Information]
```
System.Net.Sockets.SocketException (0x80004005): Сделана попытка доступа к сокету методом, запрещенным правами доступа
   at System.Net.Sockets.Socket.DoBind(EndPoint endPointSnapshot, SocketAddress socketAddress)
   at System.Net.Sockets.Socket.Bind(EndPoint localEP)
   at System.Net.Sockets.TcpListener.Start(Int32 backlog)
   at Microsoft.PythonTools.Infrastructure.ProcessOutput.RunElevated(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.Infrastructure.ProcessOutput.Run(String filename, IEnumerable`1 arguments, String workingDirectory, IEnumerable`1 env, Boolean visible, Redirector redirector, Boolean quoteArgs, Boolean elevate, Encoding outputEncoding, Encoding errorEncoding)
   at Microsoft.PythonTools.EnvironmentsList.PipExtensionProvider.<InstallPackage>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.EnvironmentsList.PipExtension.<UpgradePackage_Executed>d__10.MoveNext()
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1599: Error trying to update 2+ python libs
Prevent race condition between choosing a port number and listening on it.

### CODE REVIEW

File: Python/Product/Common/Infrastructure/ProcessOutput.cs [hunk 1]
```diff
@@ -330,8 +326,37 @@ select connection.LocalEndPoint.Port
...
+                try {
+                    listener.Start();
+                } catch (SocketException) {
+                    if (retries == 0) {
+                        throw;
+                    }
+                    continue;
+                }
+                try {
+                    clientTask = listener.AcceptTcpClientAsync();
```
Comment (huguesv) [inline Python/Product/Common/Infrastructure/ProcessOutput.cs]: are you going to get a SocketException here?  wouldn't that happen only once you've awaited the result?

Comment (zooba) [inline Python/Product/Common/Infrastructure/ProcessOutput.cs]: I believe it could occur on the initial call (which is synchronous and returns a completed task object if it's ready) or after awaiting - because this is a wrapper around an old-style async function (Begin/EndAccept) it looks like the exception may fall out.

But your point is well taken - we should be protecting the `t.Result` below too.

**Comment by huguesv** [comment]
👍
