### PR TITLE
Fix some ReplWindowSendUITests

### LINKED ISSUE #5939: LSC: ReplWindowSendUITests fail with Invalid cross-thread call
They all fail the same way.

I'm not sure if that is the only/one problem, but there is a call:
```
var pythonWorkspaceProvider = site.GetComponentModel().GetService<IPythonWorkspaceContextProvider>();
```

from `PythonLanguageClient` ctor, and that should not be there. It should get passed in, don't call GetService from a ctor.

```
Test Name:	SendToInteractiveSelection
Test Outcome:	Failed
Result Message:	
Test method ReplWindowUITestsRunner.ReplWindowSendUITests.SendToInteractiveSelection threw exception: 
TestRunnerInterop.TestFailedException: AssertFailedException: Assert.Fail failed. Invalid cross-thread call from thread 41
Result StandardOutput:	
Creating temp directory for test at C:\Projects\GitHub\huguesv\PTVS\Python\TestResults\Deploy_huvalo 2019-12-13 13_41_04\Out\Temp\u5kcfjmy.x1g\
Copying C:\Projects\GitHub\huguesv\PTVS\Python\Tests\TestData\SendToInteractive.sln to C:\Projects\GitHub\huguesv\PTVS\Python\TestResults\Deploy_huvalo 2019-12-13 13_41_04\Out\Temp\u5kcfjmy.x1g\SendToInteractive.sln
Copying C:\Projects\GitHub\huguesv\PTVS\Python\Tests\TestData\SendToInteractive to C:\Projects\GitHub\huguesv\PTVS\Python\TestResults\Deploy_huvalo 2019-12-13 13_41_04\Out\Temp\u5kcfjmy.x1g\SendToInteractive
Closing 
Opening C:\Projects\GitHub\huguesv\PTVS\Python\TestResults\Deploy_huvalo 2019-12-13 13_41_04\Out\Temp\u5kcfjmy.x1g\SendToInteractive.sln
   Expected   Actual
(Lines in reverse order)
 * >>>        >>>
 *-READY      
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive 
Executing command Python.SendSelectionToInteractive 
Successfully executed command Python.SendSelectionToInteractive
Result StandardError:	
at Microsoft.VisualStudioTools.UIThreadExtensions.MustBeCalledFromUIThread(Microsoft.VisualStudioTools.UIThreadBase self, System.String message) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 182
    Debug.Fail(
 at Microsoft.PythonTools.Extensions.GetPythonToolsService(System.IServiceProvider serviceProvider) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 535
    uiThread?.MustBeCalledFromUIThread();
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient..ctor(System.IServiceProvider site, System.String contentTypeName, Microsoft.VisualStudio.Workspace.VSIntegration.Contracts.IVsFolderWorkspaceService workspaceService, Microsoft.PythonTools.Interpreter.IInterpreterOptionsService optionsService, Microsoft.PythonTools.Interpreter.IInterpreterRegistryService registryService, Microsoft.VisualStudio.LanguageServer.Client.ILanguageClientBroker broker, Microsoft.PythonTools.Project.PythonProjectNode project, Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow replWindow) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\LanguageServerClient\PythonLanguageClient.cs:line 111
    MiddleLayer = new PythonLanguageClientMiddleLayer(site.GetPythonToolsService(), site.GetComponentModel().GetService<PythonSnippetManager>(), null);
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient+<EnsureLanguageClientAsync>d__15.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\LanguageServerClient\PythonLanguageClient.cs:line 224
    client = new PythonLanguageClient(site, contentTypeName, workspaceService, optionsService, registryService, broker, project, replWindow);
 at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(TStateMachine& stateMachine) in <unknown>:line 0
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient.EnsureLanguageClientAsync(System.IServiceProvider site, Microsoft.VisualStudio.Workspace.VSIntegration.Contracts.IVsFolderWorkspaceService workspaceService, Microsoft.PythonTools.Interpreter.IInterpreterOptionsService optionsService, Microsoft.PythonTools.Interpreter.IInterpreterRegistryService registryService, Microsoft.VisualStudio.LanguageServer.Client.ILanguageClientBroker broker, System.String contentTypeName, Microsoft.PythonTools.Project.PythonProjectNode project, Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow replWindow) in <unknown>:line 0
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient.OnDefaultInterpreterChanged(System.Object sender, System.EventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\LanguageServerClient\PythonLanguageClient.cs:line 474
    EnsureLanguageClientAsync(
 at System.EventHandler.Invoke(System.Object sender, System.EventArgs e) in <unknown>:line 0
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.EndSuppressDefaultInterpreterChangeEvent() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSInterpreters\Interpreter\InterpreterOptionsService.cs:line 248
    _defaultInterpreterChanged?.Invoke(this, EventArgs.Empty);
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.SetDefaultInterpreter(System.String id, Microsoft.PythonTools.Interpreter.IPythonInterpreterFactory factory) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSInterpreters\Interpreter\InterpreterOptionsService.cs:line 191
    EndSuppressDefaultInterpreterChangeEvent();
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.set_DefaultInterpreter(Microsoft.PythonTools.Interpreter.IPythonInterpreterFactory value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSInterpreters\Interpreter\InterpreterOptionsService.cs:line 237
    SetDefaultInterpreter(null, newDefault);
 at TestUtilities.UI.DefaultInterpreterSetter..ctor(Microsoft.PythonTools.Interpreter.IPythonInterpreterFactory factory, System.IServiceProvider site) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Utilities.Python\DefaultInterpreterSetter.cs:line 38
    interpreterService.DefaultInterpreter = factory;
 at TestUtilities.UI.Python.PythonVisualStudioApp.SelectDefaultInterpreter(TestUtilities.PythonVersion python) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Utilities.Python\PythonVisualStudioApp.cs:line 347
    return new DefaultInterpreterSetter(
 at ReplWindowUITests.ReplWindowSendUITests.RunFromProject(TestUtilities.UI.Python.PythonVisualStudioApp app, System.String filename, SendToStep[] inputs) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\ReplWindowUITests\ReplWindowSendUITests.cs:line 211
    using (var defaultInterpreterSetter = app.SelectDefaultInterpreter(PythonPaths.Python27_x64)) {
 at ReplWindowUITests.ReplWindowSendUITests.SendToInteractiveSelection(TestUtilities.UI.Python.PythonVisualStudioApp app) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\ReplWindowUITests\ReplWindowSendUITests.cs:line 114
    RunFromProject(app, "Delayed.py",
Invalid cross-thread call from thread 41
 at Microsoft.VisualStudioTools.UIThreadExtensions.MustBeCalledFromUIThread(Microsoft.VisualStudioTools.UIThreadBase self, System.String message) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSCommon\Infrastructure\UIThreadBase.cs:line 182
    Debug.Fail(
 at Microsoft.PythonTools.Extensions.GetPythonToolsService(System.IServiceProvider serviceProvider) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Extensions.cs:line 535
    uiThread?.MustBeCalledFromUIThread();
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient..ctor(System.IServiceProvider site, System.String contentTypeName, Microsoft.VisualStudio.Workspace.VSIntegration.Contracts.IVsFolderWorkspaceService workspaceService, Microsoft.PythonTools.Interpreter.IInterpreterOptionsService optionsService, Microsoft.PythonTools.Interpreter.IInterpreterRegistryService registryService, Microsoft.VisualStudio.LanguageServer.Client.ILanguageClientBroker broker, Microsoft.PythonTools.Project.PythonProjectNode project, Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow replWindow) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\LanguageServerClient\PythonLanguageClient.cs:line 111
    MiddleLayer = new PythonLanguageClientMiddleLayer(site.GetPythonToolsService(), site.GetComponentModel().GetService<PythonSnippetManager>(), null);
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient+<EnsureLanguageClientAsync>d__15.MoveNext() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\LanguageServerClient\PythonLanguageClient.cs:line 224
    client = new PythonLanguageClient(site, contentTypeName, workspaceService, optionsService, registryService, broker, project, replWindow);
 at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start(TStateMachine& stateMachine) in <unknown>:line 0
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient.EnsureLanguageClientAsync(System.IServiceProvider site, Microsoft.VisualStudio.Workspace.VSIntegration.Contracts.IVsFolderWorkspaceService workspaceService, Microsoft.PythonTools.Interpreter.IInterpreterOptionsService optionsService, Microsoft.PythonTools.Interpreter.IInterpreterRegistryService registryService, Microsoft.VisualStudio.LanguageServer.Client.ILanguageClientBroker broker, System.String contentTypeName, Microsoft.PythonTools.Project.PythonProjectNode project, Microsoft.VisualStudio.InteractiveWindow.IInteractiveWindow replWindow) in <unknown>:line 0
 at Microsoft.PythonTools.LanguageServerClient.PythonLanguageClient.OnDefaultInterpreterChanged(System.Object sender, System.EventArgs e) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\PythonTools\PythonTools\LanguageServerClient\PythonLanguageClient.cs:line 474
    EnsureLanguageClientAsync(
 at System.EventHandler.Invoke(System.Object sender, System.EventArgs e) in <unknown>:line 0
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.EndSuppressDefaultInterpreterChangeEvent() in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSInterpreters\Interpreter\InterpreterOptionsService.cs:line 248
    _defaultInterpreterChanged?.Invoke(this, EventArgs.Empty);
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.SetDefaultInterpreter(System.String id, Microsoft.PythonTools.Interpreter.IPythonInterpreterFactory factory) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSInterpreters\Interpreter\InterpreterOptionsService.cs:line 191
    EndSuppressDefaultInterpreterChangeEvent();
 at Microsoft.PythonTools.Interpreter.InterpreterOptionsService.set_DefaultInterpreter(Microsoft.PythonTools.Interpreter.IPythonInterpreterFactory value) in C:\Projects\GitHub\huguesv\PTVS\Python\Product\VSInterpreters\Interpreter\InterpreterOptionsService.cs:line 237
    SetDefaultInterpreter(null, newDefault);
 at TestUtilities.UI.DefaultInterpreterSetter.Dispose() in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\Utilities.Python\DefaultInterpreterSetter.cs:line 59
    interpreterService.DefaultInterpreter = OriginalInterpreter;
 at ReplWindowUITests.ReplWindowSendUITests.RunFromProject(TestUtilities.UI.Python.PythonVisualStudioApp app, System.String filename, SendToStep[] inputs) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\ReplWindowUITests\ReplWindowSendUITests.cs:line 222
    }
 at ReplWindowUITests.ReplWindowSendUITests.SendToInteractiveSelection(TestUtilities.UI.Python.PythonVisualStudioApp app) in C:\Projects\GitHub\huguesv\PTVS\Python\Tests\ReplWindowUITests\ReplWindowSendUITests.cs:line 114
    RunFromProject(app, "Delayed.py",
Invalid cross-thread call from thread 41
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. Invalid cross-thread call from thread 41
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFailure(String assertionName, String message)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message)
   at TestUtilities.AssertListener.Fail(String message, String detailMessage) in C:\Projects\GitHub\huguesv\PTVS\Common\Tests\Utilities\AssertListener.cs:line 140
Microsoft.VisualStudio.TestTools.UnitTesting.AssertFailedException: Assert.Fail failed. Invalid cross-thread call from thread 41
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.HandleFailure(String assertionName, String message)
   at Microsoft.VisualStudio.TestTools.UnitTesting.Assert.Fail(String message)
   at TestUtilities.AssertListener.Fail(String message, String detailMessage) in C:\Projects\GitHub\huguesv\PTVS\Common\Tests\Utilities\AssertListener.cs:line 140


```

### PR DESCRIPTION
**Pull request by huguesv**
Fix #5939 

Pass IPythonWorkspaceContextProvider to language client rather than have it query for it in its constructor. Fixes invalid cross thread call in tests.

Remove unused middle layer.

image

The last three have a different issue that may be related to https://github.com/microsoft/PTVS/issues/5931

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs [hunk 1]
```diff
@@ -127,13 +128,15 @@ string contentTypeName
 
             var componentModel = serviceProvider.GetComponentModel();
             var workspaceService = componentModel.GetService<IVsFolderWorkspaceService>();
+            var pythonWorkspaceProvider = componentModel.GetService<IPythonWorkspaceContextProvider>();
```
Comment (bschnurr) [inline Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs]: So this one is always called from the ui thread?

Comment (huguesv) [reply Python/Product/PythonTools/PythonTools/LanguageServerClient/PythonLanguageClient.cs]: I'll add a call to switch to main thread to that one and the other one
