### PR TITLE
Fixes #1739 Analysis does not restart if Python is installed while VS is running

### LINKED ISSUE #1739: Analysis does not restart if Python is installed while VS is running
The analyzer process fails if it has no copies of Python available, and then does not start when you add one.

This also leads to unit tests not displaying, colorization not working correctly, and obviously no completions.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1739 Analysis does not restart if Python is installed while VS is running
Fixes notifications when going from "no interpreters" to "global default" interpreter
Fixes analyzer not starting when no interpreters are available
Fixes errors being swallowed by analyzer
Fixes thread safety issues when loading the default interpreter
Excludes some logged events from telemetry collection
Excludes (slow) Event Log data from diagnostics when Shift is held

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs [hunk 1]
```diff
@@ -276,11 +277,10 @@ internal class PythonProjectNode :
         }
 
         private void GlobalDefaultInterpreterChanged(object sender, EventArgs e) {
-            // This event is only raised when our active interpreter is the
-            // global default.
-            var evt = ActiveInterpreterChanged;
-            if (evt != null) {
-                evt(this, EventArgs.Empty);
+            if (_active == null) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs]: `_active` could use a better name at some point (I realize you didn't introduce it in this PR).

**Comment by huguesv** [comment]
👍
