### PR TITLE
Fix #411: Cannot attach debugger to interactive window

### LINKED ISSUE #411: Cannot attach debugger to interactive window
From AttachReplTest:

```
Traceback (most recent call last):
  File "...\visualstudio_py_repl.py", line 645, in run_one_command
    self.execute_item()
  File "...\visualstudio_py_repl.py", line 996, in execute_attach_process_work_item
    visualstudio_py_debugger.attach_process(port, debugger_id, report = True, block = True)
TypeError: attach_process() missing 1 required positional argument: 'debug_options'
```

### PR DESCRIPTION
**Pull request by int19h**
Propagate debug options (that make sense in that context) to the REPL, and then from the REPL to the main debugger script, when using $attach command.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs [hunk 1]
```diff
@@ -444,10 +444,18 @@ public DisconnectedException(string message)
                     return "Cannot attach to debugger when already attached.";
                 }
 
+                var pyService = _eval._serviceProvider.GetPythonToolsService();
+
+                // Only pass options that make sense for the REPL.
+                var debugOptions = PythonDebugOptions.None;
+                if (pyService.DebuggerOptions.DebugStdLib) {
+                    debugOptions |= PythonDebugOptions.DebugStdLib;
```
Comment (gilbertw) [inline Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs]: Could future options be interesting to pass.  If so add a comment to PythonDebugOptions letting developers know to update this location when they add a new option

**Comment by gilbertw** [comment]
:+1:

File: Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs (hunk 1 above)
Comment (int19h) [inline Python/Product/PythonTools/PythonTools/Repl/BasePythonReplEvaluator.cs]: I would assume that anyone adding things to PythonDebugOptions would do a Find All References on it to see all uses, at the minimum. So comments are for cases that are not covered by that (e.g. for stuff in .py files).

**Comment by zooba** [comment]
+1
