### PR TITLE
Fix #441: Crash debugging multithreaded project

### LINKED ISSUE #441: Crash debugging multithreaded project
Received this crash while debugging a multithreaded project using a thread pool. The dictionary in question (`_pendingExecutes`) is empty at this point.

```
An unhandled exception is about to terminate the process:
The given key was not present in the dictionary.
System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.PythonTools.Debugger.PythonProcess.HandleExecutionException(Stream stream) in C:\Source\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 673
   at Microsoft.PythonTools.Debugger.PythonProcess.DebugEventThread() in C:\Source\PTVS\Python\Product\Debugger\Debugger\PythonProcess.cs:line 454
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### PR DESCRIPTION
**Pull request by int19h**
Fix IdDispenser issuing the same ID over and over again in some circumstances.

Do not crash on error response with unknown request ID.

### CODE REVIEW

**Comment by zooba** [comment]
+1. Thanks for the crazy amount of work it took to track that down.

File: Python/Product/Debugger/Debugger/PythonProcess.cs [hunk 1]
```diff
@@ -667,10 +667,13 @@ public PythonProcess(PythonLanguageVersion languageVersion, string exe, string a
...
-                _pendingExecutes.Remove(execId);
+                if (_pendingExecutes.TryGetValue(execId, out completion)) {
+                    _pendingExecutes.Remove(execId);
+                    _ids.Free(execId);
+                } else {
+                    Debug.Fail("Received REPL execution result with unknown execution ID " + execId);
+                }
             }
 
             string exceptionText = stream.ReadString();
```
Comment (DinoV) [inline Python/Product/Debugger/Debugger/PythonProcess.cs]: if(completion != null) after we read the string, otherwise we still crash.

Comment (huguesv) [inline Python/Product/Debugger/Debugger/PythonProcess.cs]: HandleEnumChildren has similar code. Should it also do an `_ids.Free()'?

Comment (int19h) [inline Python/Product/Debugger/Debugger/PythonProcess.cs]: There shouldn't be any case where we can successfully retrieve a null completion from the dictionary, since we don't put any there in the first place.

Comment (int19h) [inline Python/Product/Debugger/Debugger/PythonProcess.cs]: Ah, nevermind, I see what you mean now.

**Comment by huguesv** [comment]
:+1:
