### PR TITLE
Fixes #1793 Analysis completed but looks incomplete

### LINKED ISSUE #1793: Analysis completed but looks incomplete
Dev 15 RC with Anaconda
I've started/restarted VS a few times during analysis.
Now it appears to be done, but it's not recognizing simple things such as `unittest` module (I've reloaded solution, then restarted VS but same result - not recognized)

image

Full diagnostics on our bug share `Diagnostic Info 2016-10-31T102711.txt`.

These errors appear several times:
```
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\PythonScraper.py", line 390, in generate_member
    return 'method', generate_builtin_function(obj, True)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\PythonScraper.py", line 275, in generate_builtin_function
    function_table['overloads'] = BuiltinScraper.get_overloads(function, is_method)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\BuiltinScraper.py", line 519, in get_overloads
    extra_args,
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\BuiltinScraper.py", line 476, in get_overloads_from_doc_string
    res = parse_doc_str(doc_str, mod, decl_mod, func_name, extra_args, obj_class)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\BuiltinScraper.py", line 267, in parse_doc_str
    ret_types = get_ret_type(ret_type, obj_class, mod)
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\BuiltinScraper.py", line 186, in get_ret_type
    return [type_name_to_typeref(ret_type, mod, RETURN_TYPE_OVERRIDES)]
  File "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Extensions\Microsoft\Python\Core\BuiltinScraper.py", line 144, in type_name_to_typeref
    for mod_name, mod in sys.modules.items():
RuntimeError: dictionary changed size during iteration
```

```
2016-10-31T10:22:33: [ERROR] Analysis failed
System.ArgumentNullException: Value cannot be null.
Parameter name: key
   at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at System.Collections.Generic.Dictionary`2.TryGetValue(TKey key, TValue& value)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetTypeName(String moduleName, String className)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(AnalysisValue baseClass, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.<>c__DisplayClass35_0.<GenerateTypeName>b__0(AnalysisValue ns)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<DistinctIterator>d__63`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateTypeName(IAnalysisSet name, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateParameter(Parameter param, IAnalysisSet typeInfo)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateArgInfo(FunctionInfo fi, IAnalysisSet[] parameters)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateOverloads(FunctionInfo fi)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateFunction(FunctionInfo fi)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValueInternal(AnalysisValue type, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GetMemberValue(IAnalysisSet types, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMember(VariableDef variableDef, ModuleInfo declModule, Boolean isRef)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.GenerateMembers(ModuleInfo moduleInfo, IEnumerable`1 children)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.SerializeModule(ModuleInfo moduleInfo)
   at Microsoft.PythonTools.Analysis.SaveAnalysis.Save(PythonAnalyzer state, String outDir)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Analyze()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<RunWorker>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.<Run>d__32.MoveNext()
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #1793 Analysis completed but looks incomplete
Prevents crash analyzing builtins
Avoids crashing during analysis save when a type is missing a name.
Improves error logging in analyzer

### CODE REVIEW

File: Python/Product/Analysis/SaveAnalysis.cs [hunk 1]
```diff
@@ -46,14 +53,23 @@ class SaveAnalysis {
...
-                    var info = SerializeModule(moduleInfo);
-                    WriteModule(outDir, name, info, moduleInfo.Scope.AllVariables.Keys());
+                    _errorStack.Clear();
+                    _errorStack.Push(modKeyValue.Key);
+                    try {
+                        var info = SerializeModule(moduleInfo);
+                        WriteModule(outDir, name, info, moduleInfo.Scope.AllVariables.Keys());
+                    } catch (Exception ex) {
+                        AddError(ex.ToString());
+                        _errorStack.Clear();
```
Comment (huguesv) [inline Python/Product/Analysis/SaveAnalysis.cs]: Seems unnecessary, since the next iteration of the loop will clear before it writes the module.

**Comment by huguesv** [comment]
👍
