### PR TITLE
Fix for an exception related to the collection changing while we are …

### LINKED ISSUE #5520: Installing/uninstalling a package should trigger test discovery
This is partially implemented but not working due to the reversal of the package manager single instance change. In summary, since everyone creates their own package manager instance, it is not possible to register for events to know something was installed. See #5517

### PR DESCRIPTION
**Pull request by bschnurr**
…iterating over testcontainers

System.InvalidOperationException: Collection was modified; enumeration operation may not execute.

Steps to repro.
1. Opening ptvsd in openfolder mode
2.  install/uninstall pytest multiple times
3. Test discovery eventually fails to trigger on pacakge update, due to exception in
_projectMap.Values.SelectMany(x => x.GetAllContainers());

This is fixed by updating the dictionary of testcontianers in ProjectInfo to be a concurrent dictionary.
- delay adding the new project's testcontainers into the projectMap until we are finished building it.
- new test that creates the exception when projectInfo used a regular dictionary

Installing/uninstalling a package should trigger test discovery Fix #5520

### CODE REVIEW

File: Python/Product/TestAdapter/ProjectInfo.cs [hunk 1]
```diff
@@ -56,7 +56,8 @@ internal class ProjectInfo : IDisposable {
         public bool IsWorkspace => _pythonWorkspace != null;
 
         public TestContainer[] GetAllContainers() {
-            return _containers.Select(x => x.Value).ToArray();
+            //ConcurrentDictionary.ToArray() locks before copying
+            return _containers.Values.ToArray();
```
Comment (bschnurr) [inline Python/Product/TestAdapter/ProjectInfo.cs]: Now ToArray() will lock the dictionary before it copies

Comment (bschnurr) [reply Python/Product/TestAdapter/ProjectInfo.cs]: https://referencesource.microsoft.com/#mscorlib/system/Collections/Concurrent/ConcurrentDictionary.cs,bc495056297a0851

File: Python/Product/TestAdapter/TestContainerDiscovererProject.cs [hunk 2]
```diff
@@ -153,11 +153,14 @@ class TestContainerDiscovererProject : ITestContainerDiscoverer, IDisposable {
...
-            foreach (var project in VsProjectExtensions.EnumerateLoadedProjects(solution)) {
-                LoadProject(project);
+            try {
+                // add all source files
+                var solution = (IVsSolution)_serviceProvider.GetService(typeof(SVsSolution));
+                foreach (var project in VsProjectExtensions.EnumerateLoadedProjects(solution)) {
+                    LoadProject(project);
+                }
+            } catch (Exception ex) when (!ex.IsCriticalException()) {
+                Trace.WriteLine("Exception : " + ex.Message);
```
Comment (bschnurr) [inline Python/Product/TestAdapter/TestContainerDiscovererProject.cs]: open project didn't have an issue ( probably because open folder as all source files under a single projectInfo, its more of a worst case)

added exception guard to make sure we set _setupComplete=true

File: Python/Product/TestAdapter/TestContainerDiscovererProject.cs [hunk 3]
```diff
@@ -238,9 +241,9 @@ class TestContainerDiscovererProject : ITestContainerDiscoverer, IDisposable {
             _packageManagerEventSink.WatchPackageManagers(pyProj.GetInterpreterFactory());
 
             var projInfo = new ProjectInfo(pyProj);
-            _projectMap[projInfo.ProjectHome] = projInfo;
             var files = FilteredTestOrSettingsFiles(vsProject);
             UpdateContainersAndListeners(files, projInfo, isAdd: true);
+            _projectMap[projInfo.ProjectHome] = projInfo;
```
Comment (bschnurr) [inline Python/Product/TestAdapter/TestContainerDiscovererProject.cs]: Delay adding the new projectInfo collection of testconatiners until we finish populating it.

File: Python/Product/TestAdapter/TestContainerDiscovererWorkspace.cs [hunk 4]
```diff
@@ -160,32 +160,33 @@ class TestContainerDiscovererWorkspace : ITestContainerDiscoverer, IDisposable {
...
                 foreach (var file in _workspaceContextProvider.Workspace.EnumerateUserFiles(testFileFilter)) {
                     projInfo.AddTestContainer(this, file);
                 }
 
-                workspace.ActiveInterpreterChanged -= OnActiveInterpreterChanged;
-                workspace.ActiveInterpreterChanged += OnActiveInterpreterChanged;
-                _packageManagerEventSink.WatchPackageManagers(workspace.CurrentFactory);
+                _projectMap[projInfo.ProjectHome] = projInfo;
+            } catch (Exception ex) when (!ex.IsCriticalException()) {
+                Trace.WriteLine("Exception : " + ex.Message);
```
Comment (bschnurr) [inline Python/Product/TestAdapter/TestContainerDiscovererWorkspace.cs]: adding try/catch, delay putting the project into the map.
make sure we always register for events afterwards

File: Python/Tests/TestAdapterTests/Mocks/MockPythonProject.cs [hunk 5]
```diff
@@ -0,0 +1,67 @@
...
+//
+// See the Apache Version 2.0 License for specific language governing
+// permissions and limitations under the License.
+
+using System;
+using System.Threading.Tasks;
+using Microsoft.PythonTools.Interpreter;
+using Microsoft.PythonTools.Projects;
+
+namespace TestAdapterTests.Mocks {
```
Comment (bschnurr) [inline Python/Tests/TestAdapterTests/Mocks/MockPythonProject.cs]: new mock for new testcase

File: Python/Tests/TestAdapterTests/ProjectInfoTests.cs [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+                        var items = projectMap.Values.SelectMany(p => p.GetAllContainers()).ToList();
+                        await Task.Delay(10);
+                    }
+                )
+            );
+
+            await Task.WhenAll(rebuildTasks.Concat(iterateTasks));
+        }
+    }
+}
```
Comment (bschnurr) [inline Python/Tests/TestAdapterTests/ProjectInfoTests.cs]: Double checking this still breaks in the old code

File: Python/Product/TestAdapter/ProjectInfo.cs (hunk 1 above)
Comment (onchuner) [reply Python/Product/TestAdapter/ProjectInfo.cs]: Values locks and copies values and ToArray copies again

File: Python/Tests/TestAdapterTests/ProjectInfoTests.cs [hunk 7]
```diff
@@ -0,0 +1,77 @@
...
+        /// </summary>
+        /// <returns></returns>
+        [TestMethod, Priority(0)]
+        public async Task TestBuildingAndClearingProjectMapConcurrently() {
+            ITestContainerDiscoverer dummyDiscoverer = null;
+            var projectMap = new ConcurrentDictionary<string, ProjectInfo>();
+            var projectName = "dummyName";
+            PythonProject dumpyProject = new MockPythonProject("dummyHome", projectName);
+
+            //Simualte rebuid workspace
```
Comment (huguesv) [inline Python/Tests/TestAdapterTests/ProjectInfoTests.cs]: typo: simulate

File: Python/Tests/TestAdapterTests/ProjectInfoTests.cs [hunk 8]
```diff
@@ -0,0 +1,77 @@
...
+        /// System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
+        /// Test shouldn't throw
+        /// </summary>
+        /// <returns></returns>
+        [TestMethod, Priority(0)]
+        public async Task TestBuildingAndClearingProjectMapConcurrently() {
+            ITestContainerDiscoverer dummyDiscoverer = null;
+            var projectMap = new ConcurrentDictionary<string, ProjectInfo>();
+            var projectName = "dummyName";
+            PythonProject dumpyProject = new MockPythonProject("dummyHome", projectName);
```
Comment (huguesv) [inline Python/Tests/TestAdapterTests/ProjectInfoTests.cs]: typo: dummyProject

Comment (bschnurr) [reply Python/Tests/TestAdapterTests/ProjectInfoTests.cs]: I'm 0 for 2
