### PR TITLE
Fixes breakpoints on first and last line

### LINKED ISSUE #3270: Breakpoint on first line is not hit
New Python application
```
print('hello world')
print('hello world')
```
Put breakpoint on line 1 and start debugging.
Result: no break

Put breakpoint on line 2 and start debugging.
Result: break on line 2

~9 tests in DebugProjectUITests are failing due to this.

### PR DESCRIPTION
**Pull request by huguesv**
Fix #3270 

Also fixes EnumModules test.

### CODE REVIEW

**Comment by huguesv** [comment]
image

File: Python/Product/Debugger/Debugger/PythonProcess.cs [hunk 1]
```diff
@@ -492,9 +492,14 @@ public PythonProcess(PythonLanguageVersion languageVersion, string exe, string a
...
             if (ast != null) {
-                int start = ast.LocationToIndex(new SourceLocation(line, 1));
-                int end = ast.LocationToIndex(new SourceLocation(line, int.MaxValue));
-                len = end - start;
+                try {
+                    int start = ast.LocationToIndex(new SourceLocation(line, 1));
+                    int end = ast.LocationToIndex(new SourceLocation(line, int.MaxValue));
+                    len = end - start;
+                } catch (OverflowException) {
+                    // This happens when we request the end of the last line
```
Comment (zooba) [inline Python/Product/Debugger/Debugger/PythonProcess.cs]: Can we handle this in `LocationToIndex` rather than here? I'd rather get a sensible return value for requesting the end of the line (I assume that's where the error is coming from - the `end - start` bit ought to be fine)

Comment (huguesv) [reply Python/Product/Debugger/Debugger/PythonProcess.cs]: What's a sensible value in that case? -1 ?

Comment (zooba) [reply Python/Product/Debugger/Debugger/PythonProcess.cs]: And to be clear, I'd rather detect it with comparisons before doing arithmetic than just doing it and catching the exception.

Comment (zooba) [reply Python/Product/Debugger/Debugger/PythonProcess.cs]: The very last index of the file.

**Comment by huguesv** [comment]
I ran most non-ui tests and although some are failing they don't appear to be regressions from my changes.
