### PR TITLE
Partial fix to the error message after program exit with VSC debugger

### LINKED ISSUE #3537: VS Code debugger error message when closing the console
Start debugging a small script that prints to the console, no need for breakpoints
Console stays up at the end leaving only option to close the window
When you do that you get:
```
---------------------------
Microsoft Visual Studio
---------------------------
The debug adapter exited unexpectedly.
---------------------------
OK   
---------------------------
```

or sometimes:
```
---------------------------
Microsoft Visual Studio
---------------------------
Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host.



An existing connection was forcibly closed by the remote host
---------------------------
OK   
---------------------------


```

### PR DESCRIPTION
**Pull request by karthiknadig**
Fixes #3537
This is partial fix because there is a change needed in VSC debugger where we fire `exitedEvent` with correct error code on program exit.

### CODE REVIEW

File: Python/Product/Debugger/DebugAdapterProcessStream.cs [hunk 1]
```diff
@@ -0,0 +1,63 @@
...
+// MERCHANTABLITY OR NON-INFRINGEMENT.
+//
+// See the Apache Version 2.0 License for specific language governing
+// permissions and limitations under the License.
+
+using System.IO;
+using System.Net.Sockets;
+
+namespace Microsoft.PythonTools.Debugger {
+    public sealed class DebugAdapterProcessStream : Stream {
```
Comment (zooba) [inline Python/Product/Debugger/DebugAdapterProcessStream.cs]: Does it need to be public?
