### PR TITLE
Respect the clear PYTHONPATH option when creating the REPL launch configuration

### LINKED ISSUE #3014: Use PYTHONPATH option does not work for REPL
(Reported at https://developercommunity.visualstudio.com/content/problem/90795/ignore-python-path.html)

In `PythonReplEvaluatorProvider.GetEnvironmentEvaluator` we need to factor in the option to (not) clear global PYTHONPATH when creating the launch configuration.

Elsewhere we split and add it as search paths, so we should be consistent here.

### PR DESCRIPTION
**Pull request by huguesv**
Fix #3014

### CODE REVIEW

File: Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs [hunk 1]
```diff
@@ -471,6 +471,28 @@ public abstract class ReplWindowAdvancedUITests {
         }
 
         #endregion
+
+        #region Advanced Launch Configuration Tests
+
+        [TestMethod, Priority(2)]
```
Comment (zooba) [inline Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs]: Are these already flaky? New tests should be Priority(0), and if they aren't reliable then invest the time to make them reliable.

Comment (huguesv) [reply Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs]: Yes, all REPL UI tests are flaky due to #2701 and #3099.

Comment (zooba) [reply Python/Tests/ReplWindowUITestsRunner/ReplWindowAdvancedUITests.cs]: Okay
