### PR TITLE
LSC: ArgumentOutOfRange exception while formatting document  Fix #5879

### LINKED ISSUE #5879: LSC: ArgumentOutOfRange exception while formatting document
See test `LspDiffTextEditFactoryTests.AddNewLineAtEndOfDoc`

Create a document that doesn't end with a newline like this one and format it with `black`.
```
1
2
3
four_hundred=4* 100
5

seven=[1,2, 3]

nine = ( 1,
2,
3,
4)
end = 13```

```

Error:
```
---------------------------
Visual Studio - Python support
---------------------------
Specified argument was out of the range of valid values.

Parameter name: lineNumber
---------------------------
OK   
---------------------------
```

Also affected test: `FormattingUITests.FormatBlack`

### PR DESCRIPTION
**Pull request by bschnurr**
Fix #5879

- new idea is to append changes to previous line.  This gets around the issue of outofRange exceptions when trying to add a new line to a document.

- this also solves the existing issue in VsCode's code, where additional blank lines were being added to end of file, due to adding newline characters to every diff before processing edits

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs [hunk 1]
```diff
@@ -22,10 +22,12 @@
 namespace Microsoft.PythonTools.LanguageServerClient {
     internal static class LspEditorUtilities {
         internal static SnapshotPoint GetSnapshotPositionFromProtocolPosition(this ITextSnapshot textSnapshot, Position position) {
-            var line = textSnapshot.GetLineNumberFromPosition(position.Line);
```
Comment (bschnurr) [inline Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs]: deleted unused ```line```

File: Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs [hunk 2]
```diff
@@ -22,10 +22,12 @@
...
-            var snapshotPosition = textSnapshot.GetLineFromLineNumber(position.Line).Start + position.Character;
+            if (position.Line < textSnapshot.LineCount) {
```
Comment (bschnurr) [inline Python/Product/PythonTools/PythonTools/LanguageServerClient/LspEditorUtilities.cs]: new code doesn't try to get the snapshot position if the line is out side of the snapshot.

now it will return the end position in this case

File: Python/Tests/Core.UI/FormattingUITests.cs [hunk 3]
```diff
@@ -66,7 +66,8 @@ public class FormattingUITests {
     pass
 
 
-def g(): return 5 ** 2
+def g():
+    return 5 ** 2
```
Comment (bschnurr) [inline Python/Tests/Core.UI/FormattingUITests.cs]: i was going to add another fix for black formatting but instead just updating the test case expected result

File: Python/Tests/Core/LspDiffTextEditFactoryTests.cs [hunk 4]
```diff
@@ -314,39 +312,39 @@ import bottle
...
-            //";
+            -nine = ( 1,
+            -2,
+            -3,
+            -4)
+            +nine = (1, 2, 3, 4)
+             end = 13
+            +
+            ",
+             new TextEdit[] { });
```
Comment (bschnurr) [inline Python/Tests/Core/LspDiffTextEditFactoryTests.cs]: will update results.
