### PR TITLE
Fixes #421 and #422

### LINKED ISSUE #421: Unhandled Python-not-runnable exception
Found in a test where it was not part of the test.

```
devenv.exe Error: 0 : Unhandled exception in Microsoft.PythonTools.Project.InterpretersNode.CheckPackages (c:\RollBuild\Python\Product\PythonTools\PythonTools\Project\InterpretersNode.cs:171)
System.IO.FileNotFoundException: C:\RollBuild\TestResults\2015-06-13 06_41_31\Out\Temp\DeleteVirtualEnv\env\Scripts\python.exe
   at Microsoft.PythonTools.PythonInterpreterFactoryRunnableExtensions.ThrowIfNotRunnable(IPythonInterpreterFactory factory, String parameterName)
   at Microsoft.PythonTools.Project.Pip.Run(IPythonInterpreterFactory factory, Redirector output, Boolean elevate, String[] cmd)
   at Microsoft.PythonTools.Project.Pip.<List>d__11.MoveNext()
```

### LINKED ISSUE #422: Unhandled exception in PythonProjectNode.RemoveInterpreter
From a test:

```
devenv.exe Error: 0 : Unhandled exception in Microsoft.PythonTools.Project.PythonProjectNode.RemoveInterpreter (c:\RollBuild\Python\Product\PythonTools\PythonTools\Project\PythonProjectNode.cs:2166)
System.IO.IOException: The directory is not empty.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.Directory.DeleteHelper(String fullPath, String userPath, Boolean recursive, Boolean throwOnTopLevelDirectoryNotFound)
   at System.IO.Directory.Delete(String fullPath, String userPath, Boolean recursive, Boolean checkHost)
   at Microsoft.PythonTools.Project.PythonProjectNode.<>c__DisplayClassb1.<RemoveInterpreter>b__af()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudioTools.VsTaskExtensions.<HandleAllExceptions>d__1`1.MoveNext()
```

### PR DESCRIPTION
**Pull request by zooba**
Fixes #421 Unhandled Python-not-runnable exception
Adds unhandled exception type to try/catch statement.

Fixes #422 Unhandled exception in PythonProjectNode.RemoveInterpreter
Suppresses extra message box for "normal" errors when deleting directories.

### CODE REVIEW

File: Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs [hunk 1]
```diff
@@ -2161,8 +2161,13 @@ bool addNew
             var path = factory.Configuration.PrefixPath;
             if (removeFromStorage && Directory.Exists(path)) {
                 var t = Task.Run(() => {
-                    Directory.Delete(path, true);
-                    return true;
+                    try {
+                        Directory.Delete(path, true);
```
Comment (int19h) [inline Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs]: I'm confused - why wouldn't we want to display a message box here if delete fails? Shouldn't the user know?

Comment (zooba) [inline Python/Product/PythonTools/PythonTools/Project/PythonProjectNode.cs]: The `return false` here is already used to trigger a friendly message rather than the generic "See ActivityLog.xml" message.

**Comment by int19h** [comment]
:+1:
