### PR TITLE
Fix #4563: Assert on project load: currently processing another request

### LINKED ISSUE #4563: Assert on project load: currently processing another request
image

```
 	System.dll!System.Diagnostics.AssertWrapper.ShowMessageBoxAssert(string stackTrace, string message, string detailMessage)	Unknown
 	System.dll!System.Diagnostics.DefaultTraceListener.Fail(string message, string detailMessage)	Unknown
 	System.dll!System.Diagnostics.DefaultTraceListener.Fail(string message)	Unknown
 	System.dll!System.Diagnostics.TraceInternal.Fail(string message)	Unknown
 	System.dll!System.Diagnostics.Debug.Fail(string message)	Unknown
>	Microsoft.PythonTools.Ipc.Json.dll!Microsoft.PythonTools.Ipc.Json.Connection.ProcessEvent(Newtonsoft.Json.Linq.JObject packet) Line 343	C#
 	Microsoft.PythonTools.Ipc.Json.dll!Microsoft.PythonTools.Ipc.Json.Connection.ProcessMessages() Line 279	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<Newtonsoft.Json.Linq.JObject>.SetResult(Newtonsoft.Json.Linq.JObject result)	Unknown
 	Microsoft.PythonTools.Ipc.Json.dll!Microsoft.PythonTools.Ipc.Json.Connection.ReadPacketAsJObject(Microsoft.PythonTools.Ipc.Json.ProtocolReader reader) Line 449	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<string>.SetResult(string result)	Unknown
 	Microsoft.PythonTools.Ipc.Json.dll!Microsoft.PythonTools.Ipc.Json.Connection.ReadPacket(Microsoft.PythonTools.Ipc.Json.ProtocolReader reader) Line 519	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<System.__Canon>.TrySetResult(System.__Canon result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<string>.SetResult(string result)	Unknown
 	Microsoft.PythonTools.Ipc.Json.dll!Microsoft.PythonTools.Ipc.Json.ProtocolReader.ReadHeaderLineAsync() Line 57	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncTaskMethodBuilder<int>.SetResult(int result)	Unknown
 	Microsoft.PythonTools.Ipc.Json.dll!Microsoft.PythonTools.Ipc.Json.ProtocolReader.ReadIntoBuffer() Line 115	C#
 	[Resuming Async Method]	
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(object stateMachine)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run()	Unknown
 	mscorlib.dll!System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(System.Action action, bool allowInlining, ref System.Threading.Tasks.Task currentTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task<int>.TrySetResult(int result)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskFactory<int>.FromAsyncTrimPromise<System.IO.Stream>.Complete(System.IO.Stream thisRef, System.Func<System.IO.Stream, System.IAsyncResult, int> endMethod, System.IAsyncResult asyncResult, bool requiresSynchronization)	Unknown
 	mscorlib.dll!System.Threading.Tasks.TaskFactory<int>.FromAsyncTrimPromise<System.IO.Stream>.CompleteFromAsyncResult(System.IAsyncResult asyncResult)	Unknown
 	mscorlib.dll!System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(object completedTask)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, object state, bool preserveSyncCtx)	Unknown
 	mscorlib.dll!System.IO.Stream.ReadWriteTask.System.Threading.Tasks.ITaskCompletionAction.Invoke(System.Threading.Tasks.Task completingTask)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishContinuations()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageThree()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.FinishStageTwo()	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.Finish(bool bUserDelegateExecuted)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteWithThreadLocal(ref System.Threading.Tasks.Task currentTaskSlot)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.ExecuteEntry(bool bPreventDoubleExecution)	Unknown
 	mscorlib.dll!System.Threading.Tasks.Task.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()	Unknown
 	mscorlib.dll!System.Threading.ThreadPoolWorkQueue.Dispatch()	Unknown
 	mscorlib.dll!System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()	Unknown
 	[Async Call Stack]	
 	[Async] Microsoft.PythonTools.Analyzer.exe!Microsoft.PythonTools.Analysis.PyLibAnalyzer.RunWorker() Line 191	C#
 	[Async] Microsoft.PythonTools.Analyzer.exe!Microsoft.PythonTools.Analysis.PyLibAnalyzer.Run() Line 163	C#
```

### PR DESCRIPTION
**Pull request by AlexanderSher**
`cancelRequest` isn't used by VS and is never invoked by `StreamJsonRpc`: 
https://github.com/Microsoft/vs-streamjsonrpc/blob/0276b4313556b7db875bc99f76a4fd133d9011fd/src/StreamJsonRpc/JsonRpc.cs#L29
https://github.com/Microsoft/vs-streamjsonrpc/blob/0276b4313556b7db875bc99f76a4fd133d9011fd/src/StreamJsonRpc/JsonRpc.cs#L1366

The right way to cancel requests is to get `CancellationToken` as a parameter in the protocol methods and then pass it further. 

`RequestLock` is deleted.

### CODE REVIEW

File: Python/Product/Analysis/LanguageServer/IServer.cs [hunk 1]
```diff
@@ -20,12 +20,11 @@
 
 namespace Microsoft.PythonTools.Analysis.LanguageServer {
     public interface IServer {
-        Task<InitializeResult> Initialize(InitializeParams @params);
+        Task<InitializeResult> Initialize(InitializeParams @params, CancellationToken cancellationToken = default(CancellationToken));
```
Comment (zooba) [inline Python/Product/Analysis/LanguageServer/IServer.cs]: FYI, these are not backwards compatible changes. To change function parameters in an interface we need to add a new interface and retain support for the old one as well.

File: Python/Product/Analysis/LanguageServer/ServerBase.cs [hunk 2]
```diff
@@ -20,57 +20,17 @@
...
-        /// <summary>
-        /// Get this token at the start of request processing and abort when it
-        /// is marked as cancelled.
-        /// </summary>
-        protected CancellationToken CancellationToken => Volatile.Read(ref _lock)?.Token ?? CancellationToken.None;
-
         #region Client Requests
 
-        public abstract Task<InitializeResult> Initialize(InitializeParams @params);
+        public abstract Task<InitializeResult> Initialize(InitializeParams @params, CancellationToken cancellationToken = default(CancellationToken));
```
Comment (zooba) [inline Python/Product/Analysis/LanguageServer/ServerBase.cs]: These are also not backwards compatible changes.

File: Python/Product/VSCode/AnalysisVsc/LanguageServer.cs [hunk 3]
```diff
@@ -137,14 +137,9 @@ private void OnUnregisterCapability(object sender, UnregisterCapabilityEventArgs
             => _rpc.NotifyWithParameterObjectAsync("client/unregisterCapability", e.@params).DoNotWait();
         #endregion
 
-        #region Cancellation
-        [JsonRpcMethod("cancelRequest")]
```
Comment (zooba) [inline Python/Product/VSCode/AnalysisVsc/LanguageServer.cs]: This method still exists - the IDE will send it to cancel whatever request is currently running. How do we cancel any of the requests without it?

Comment (zooba) [reply Python/Product/VSCode/AnalysisVsc/LanguageServer.cs]: Oh I see, this gets handled specially by StreamJsonRpc now. Fair enough.

File: Python/Product/Analysis/LanguageServer/IServer.cs (hunk 1 above)
Comment (AlexanderSher) [reply Python/Product/Analysis/LanguageServer/IServer.cs]: Have we published this interface already?

File: Python/Product/Analysis/LanguageServer/ServerBase.cs (hunk 2 above)
Comment (AlexanderSher) [reply Python/Product/Analysis/LanguageServer/ServerBase.cs]: Maybe I'll just add internal overloads to the `Server` and won't make any changes to public API?

**Comment by huguesv** [comment]
@AlexanderSher mentioned in the bug that this is a regression from https://github.com/Microsoft/PTVS/pull/4549 

If that's correct, then there is nothing to fix for 15.8 because that PR wasn't merged in that branch.

(I have never seen the assert on 15.8)

File: Python/Product/Analysis/LanguageServer/IServer.cs (hunk 1 above)
Comment (huguesv) [reply Python/Product/Analysis/LanguageServer/IServer.cs]: Wouldn't API changes be okay since we just bumped the assembly version to 16.0?

Comment (AlexanderSher) [reply Python/Product/Analysis/LanguageServer/IServer.cs]: This doesn't solve the problem with `ServerBase` which has to provide overloads which may break existing extension methods. For example:

```cs
public class C1 {
    public void M1(int i) => Console.WriteLine(i);
}

public static void M1(this C1 c1, int i, int j) => Console.WriteLine(i + j);
```

If for the new version you'll change it to
```cs
public class C1 {
    public void M1(int i) => Console.WriteLine(i);
    public void M1(int i, int j) => Console.WriteLine(i - j);
}
```

Class method will be called instead of extension one. This requires recompilation, but after that it will provide quiet semantics change.
