### PR TITLE
Relative import fails in Python 2.7

### LINKED ISSUE #4610: Relative import fails in Python 2.7
See https://github.com/Microsoft/vscode-python/issues/2320

image

Manually executing code in Python 2.7 console works. With Python 3.6 import works fine, no squiggly.

Execution in VS REPL fails. But from console running from the app folder, code works.

image

### PR DESCRIPTION
**Pull request by MikhailArkhipov**
Fixes #4610

The issue was that file watcher ctor throws when folder in search paths does not exist.

I was able to repro the issue in VS but it was much harder, the reason is different. Most probably adding 'hello.py' first leads to creation of unresolved 'imported' and later, when 'imported' is actually added the module table is not updated.

### CODE REVIEW

File: Python/Product/VSCode/AnalysisVsc/PathsWatcher.cs [hunk 1]
```diff
@@ -40,19 +43,26 @@ internal sealed class PathsWatcher : IDisposable {
             var list = new List<FileSystemWatcher>();
             var reduced = ReduceToCommonRoots(paths);
             foreach (var p in reduced) {
-                var fsw = new FileSystemWatcher(p);
-                fsw.IncludeSubdirectories = true;
-                fsw.EnableRaisingEvents = true;
+                if(!Directory.Exists(p)) {
```
Comment (AlexanderSher) [inline Python/Product/VSCode/AnalysisVsc/PathsWatcher.cs]: Let's just catch `IOException` here

Comment (MikhailArkhipov) [reply Python/Product/VSCode/AnalysisVsc/PathsWatcher.cs]: Ctor actually throws `ArgumentException`

Comment (AlexanderSher) [reply Python/Product/VSCode/AnalysisVsc/PathsWatcher.cs]: Ok. Do we care about `PathTooLongException`?

Comment (MikhailArkhipov) [reply Python/Product/VSCode/AnalysisVsc/PathsWatcher.cs]: Oh, I see
