### PR TITLE
Prevent crash on launch file

### LINKED ISSUE #4166: Crash running Sklearn demo
[Window Title]
devenv.exe

[Main Instruction]
An unexpected error occurred

[Content]
Please press Ctrl+C to copy the contents of this dialog and report this error to our issue tracker.

[^] Hide details  [Close]

[Expanded Information]
```
Build: 15.6.18072.2

Microsoft.PythonTools.Debugger.NoStartupFileException: The project cannot be launched because the startup file 'C:\Users\Charles\AppData\Local\Temp\~vs1969.py' was not found.
   at Microsoft.PythonTools.Debugger.DebugLaunchHelper.RequireStartupFile(LaunchConfiguration config)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.Launch(LaunchConfiguration config, Boolean debug)
   at Microsoft.PythonTools.Project.DefaultPythonLauncher.LaunchFile(String file, Boolean debug)
   at Microsoft.PythonTools.PythonToolsPackage.LaunchFile(IServiceProvider provider, String filename, Boolean debug, Boolean saveDirtyFiles)
   at Microsoft.PythonTools.Language.EditFilter.ExecWorker(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
   at Microsoft.PythonTools.Language.EditFilter.Exec(Guid& pguidCmdGroup, UInt32 nCmdID, UInt32 nCmdexecopt, IntPtr pvaIn, IntPtr pvaOut)
```

### PR DESCRIPTION
**Pull request by huguesv**
Fix #4166

### CODE REVIEW

File: Python/Product/PythonTools/PythonToolsPackage.cs [hunk 1]
```diff
@@ -299,14 +299,26 @@ internal sealed class PythonToolsPackage : CommonPackage, IVsComponentSelectorPr
 
                 if (saveDirtyFiles) {
                     var rdt = provider.GetService(typeof(SVsRunningDocumentTable)) as IVsRunningDocumentTable;
-                    if (rdt != null) {
+                    var rdt4 = provider.GetService(typeof(SVsRunningDocumentTable)) as IVsRunningDocumentTable4;
+                    if (rdt != null && rdt4 != null) {
```
Comment (MikhailArkhipov) [inline Python/Product/PythonTools/PythonToolsPackage.cs]: Wait, so `GetDocumentMoniker(GetDocumentCookie(fileName)) != fileName` ?

Comment (huguesv) [reply Python/Product/PythonTools/PythonToolsPackage.cs]: There's a save dirty documents in between, and that's what is changing the filename. In that bug, the filename is in %temp% folder, and after the save dirty, it's wherever the user saved it.
