### PR TITLE
Fix elevation check for conda package manager.

### LINKED ISSUE #3354: Correctly detect when we should elevate to install conda packages
The existing logic in the package manager ui doesn't work with conda.

I've described what we need to do in the comments of CondaPackageManager.ShouldElevate.

### PR DESCRIPTION
**Pull request by huguesv**
Fix #3354

### CODE REVIEW

File: Python/Product/VSInterpreters/CondaPackageManager.cs [hunk 1]
```diff
@@ -164,21 +165,41 @@ class CondaPackageManager : IPackageManager, IDisposable {
...
+                    using (var fileStream = new FileStream(filePath, FileMode.Append)) {
+                        result = Task.FromResult(false);
+                    }
+                }
+            } catch (ArgumentException) {
+            } catch (IOException) {
+            } catch (NotSupportedException) {
+            } catch (UnauthorizedAccessException) {
+                result = Task.FromResult(true);
+            } catch (SecurityException) {
```
Comment (int19h) [inline Python/Product/VSInterpreters/CondaPackageManager.cs]: This shouldn't be needed (or should count as inconclusive), since it's only raised for CAS, and doesn't have anything to do with filesystem permissions.

**Comment by huguesv** [comment]
I just realized that this doesn't respect the "always run pip as administrator" option (it only does when the check is inconclusive - ui.ShouldElevateAsync that checks it)

I'll change it to call that first, and only if that returns false then go with our check.

I guess I'll rename the option to "always run pip and conda as administrator".

**Comment by zooba** [comment]
Make it "always run package managers as Administrator"
