### PR TITLE
Fixes #2924 Assert, then unexpected error when using New Window

### LINKED ISSUE #2924: Assert, then unexpected error when using New Window
Open a Python file that has some code in it
From main menu, Window -> New Window
You'll get an assert because the text buffer was already initialized (from BufferParser.InitBuffer)
Close the new window
Move the cursor around in the original 'window' to trigger a tooltip, you'll get an activity log error
If you try to use IntelliSense, you'll get the unexpected error dialog instead

```
System.ArgumentException: Failed to get classifier from buffer
at Microsoft.PythonTools.Intellisense.ReverseExpressionParser..ctor(ITextSnapshot snapshot, ITextBuffer buffer, ITrackingSpan span) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Intellisense\ReverseExpressionParser.cs:line 53
at Microsoft.PythonTools.Language.TextViewFilter.GetDataTipText(TextSpan[] pSpan, String& pbstrText) in C:\Projects\huguesv\PTVS\Python\Product\PythonTools\PythonTools\Navigation\TextViewFilter.cs:line 119
at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.TryGetQuickInfoFromFilter(IQuickInfoSession session, TextSpan[] dataBufferTextSpan, String& tipText)
at Microsoft.VisualStudio.Editor.Implementation.ShimQuickInfoSource.AugmentQuickInfoSession(IQuickInfoSession session, IList`1 qiContent, ITrackingSpan& applicableToSpan)
at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Recalculate() at Microsoft.VisualStudio.Language.Intellisense.Implementation.QuickInfoSession.Start()
at Microsoft.VisualStudio.Language.Intellisense.Implementation.DefaultQuickInfoController.OnTextView_MouseHover(Object sender, MouseHoverEventArgs e)
at Microsoft.VisualStudio.Text.Editor.Implementation.WpfTextView.RaiseHoverEvents()
```

`IntellisenseController.DisconnectSubjectBuffer` is called when the view is closed, and it does a `PythonTextBufferInfo.TryDispose(subjectBuffer)` which removes the `PythonTextBufferInfo` property, and `ReverseExpressionParser` expects it to be there later on.

I've had the assert and the TryDispose calls commented out while I've been working on Peek Definition, which is also a new window on a shared text buffer. Not sure what the right fix is.

### PR DESCRIPTION
**Pull request by zooba**
Fixes #2924 Assert, then unexpected error when using New Window
Reorders the relationships between our various buffer using/wrapping classes.

Key points:
* nothing should keep `PythonTextBufferInfo` alive except the text buffer itself (circular references are okay)
 * (this is why we now have a sink interface instead of event handlers)
* all files are analyzed on disk, and then we add buffer info if/when we have it

Still some things to fix, tests to run, etc., but the core change that needs reviewing is here.

### CODE REVIEW

**Comment by zooba** [comment]
Many tests fail because `PythonEditorServices` requires `MockComponentModel.get_DefaultCompositionService()`, which is currently not implemented.

**Comment by zooba** [comment]
@huguesv Could you take a look at this? I suspect it's holding up your peek PR, and we're all running late for the next preview.

FWIW, the non-UI tests are mostly fine, and the UI tests are totally busted on the test machines (i.e. 0% success rate, instant failure for basically everything - not my fault :) )

File: Common/Tests/MockVsTests/MockClassifierAggregatorService.cs [hunk 1]
```diff
@@ -42,32 +42,31 @@ public class MockClassifierAggregatorService : IClassifierAggregatorService {
...
+                }
             }
 
-            public void Dispose() {
-                foreach (var c in _classifiers.OfType<IDisposable>()) {
-                    c.Dispose();
-                }
+            private void Subclassification_Changed(object sender, ClassificationChangedEventArgs e) {
+                var c = (IClassifier)sender;
+                var refreshSpans = c.GetClassificationSpans(e.ChangeSpan);
```
Comment (huguesv) [inline Common/Tests/MockVsTests/MockClassifierAggregatorService.cs]: >GetClassificationSpans [](start = 37, length = 22)

The result of this is thrown away. Is there a desired side effect that is achieved by calling this?

Comment (zooba) [reply Common/Tests/MockVsTests/MockClassifierAggregatorService.cs]: It ensures the token cache is filled for PythonClassifier. The sequence of events is strange, and probably some assumptions based on how VS works need to be fixed, but it goes roughly like this:

* create new text view with text already in it
* classifier attaches and we get classifications to fill the cache (implicit in VS, already explicit elsewhere in our tests)
* analysis entry gets assigned to the buffer, which resets the cache and raises the event (happens in both)
* in VS, and with this call here, the event triggers getting the new classifications, which refills the cache
* we delete the text from the buffer, which deletes the relevant part of the cache

At the last step, if the cache was not refilled then we throw an exception. This exception never seems to occur in actual use, because the aggregator gets the new classifications immediately. However, our test previously was not getting classifications immediately.

The token cache uses "highly optimized" array operations that rely on it being in a certain state. I don't want to touch it just yet, so I set up the mock tests to do the same steps as VS does (which arguably is the right way to do it - if there are problems in the classifier's assumptions, we want them to show up in both VS and mocks).

File: Python/Product/PythonTools/PythonTools/PythonClassifier.cs [hunk 2]
```diff
@@ -19,58 +19,46 @@
...
-            _buffer = buffer;
-
-            _buffer.OnNewAnalysisEntry += NewAnalysisEntry;
-
-            _version = _buffer.LanguageVersion;
         }
 
-        private void NewAnalysisEntry(object sender, EventArgs e) {
-            var analyzer = _buffer.AnalysisEntry?.Analyzer;
+        private Task OnNewAnalysisEntryAsync(PythonTextBufferInfo sender, AnalysisEntry entry) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/PythonClassifier.cs]: >OnNewAnalysisEntryAsync [](start = 21, length = 23)

Doesn't need to be async

File: Python/Product/PythonTools/PythonTools/PythonClassifier.cs [hunk 3]
```diff
@@ -19,58 +19,46 @@
...
         [ThreadStatic]
         private static Dictionary<PythonLanguageVersion, Tokenizer> _tokenizers;    // tokenizer for each version, shared between all buffers
 
-        internal PythonClassifier(PythonClassifierProvider provider, PythonTextBufferInfo buffer) {
-            buffer.OnChanged += BufferChanged;
-            buffer.OnContentTypeChanged += BufferContentTypeChanged;
-
+        internal PythonClassifier(PythonClassifierProvider provider) {
             _tokenCache = new TokenCache();
             _provider = provider;
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/PythonClassifier.cs]: >provider [](start = 24, length = 8)

You could check for null

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/PythonClassifier.cs]: It's an internal constructor that gets passed `this` - it'll never be null.

File: Python/Product/PythonTools/PythonTools/PythonClassifier.cs [hunk 4]
```diff
@@ -116,26 +106,17 @@ internal sealed class PythonClassifier : IClassifier {
 
         #region Private Members
 
-        private Dictionary<TokenCategory, IClassificationType> CategoryMap {
-            get {
-                return _provider.CategoryMap;
+        private Task OnTextContentChangedAsync(PythonTextBufferInfo sender, TextContentChangedEventArgs e) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/PythonClassifier.cs]: >OnTextContentChangedAsync [](start = 21, length = 25)

Doesn't need to be async

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs [hunk 5]
```diff
@@ -23,63 +27,90 @@
...
+                .Select(b => TryGetForBuffer(b))
+                .Where(b => b != null);
+        }
+
+        public static bool TryDisconnect(object owner, ITextBuffer buffer) {
             PythonTextBufferInfo bi;
             if (buffer.Properties.TryGetProperty(typeof(PythonTextBufferInfo), out bi)) {
                 buffer.Properties.RemoveProperty(typeof(PythonTextBufferInfo));
-                bi?.Dispose();
+                //bi?.Disconnect(owner);
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: >Disconnect [](start = 22, length = 10)

delete?

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: 👍

File: Python/Product/PythonTools/PythonTools/PythonClassifier.cs (hunk 2 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/PythonClassifier.cs]: Also doesn't hurt, and it saves changes later if we make it async (it's been refactored out of an async method).

File: Python/Product/PythonTools/PythonTools/PythonClassifier.cs (hunk 4 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/PythonClassifier.cs]: Same as the other one

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs [hunk 6]
```diff
@@ -23,63 +27,90 @@
...
 using Microsoft.VisualStudio.Text;
+using Microsoft.VisualStudio.Text.Editor;
 using Microsoft.VisualStudio.Utilities;
 
 namespace Microsoft.PythonTools.Editor {
-    sealed class PythonTextBufferInfo : IDisposable {
+    sealed class PythonTextBufferInfo {
         public static PythonTextBufferInfo ForBuffer(PythonEditorServices services, ITextBuffer buffer) {
-            return buffer.Properties.GetOrCreateSingletonProperty(
+            var bi = buffer.Properties.GetOrCreateSingletonProperty(
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: >buffer [](start = 21, length = 6)

The TryGetForBuffer checks for null param, so this one should probably throw ANE rather than NRE.

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: 👍

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs [hunk 7]
```diff
@@ -124,66 +173,89 @@ sealed class PythonTextBufferInfo : IDisposable {
...
-        public PythonAnalysisClassifier AnalysisClassifier => _analysisClassifier;
-        public PythonAnalysisClassifier GetOrCreateAnalysisClassifier(Func<PythonTextBufferInfo, PythonAnalysisClassifier> creator) => GetOrCreate(ref _analysisClassifier, creator);
+        public T GetOrCreateSink<T>(object key, Func<PythonTextBufferInfo, T> creator) where T : class, IPythonTextBufferInfoEventSink {
+            IPythonTextBufferInfoEventSink sink;
+            if (_eventSinks.TryGetValue(key, out sink)) {
+                return sink as T;
+            }
+            sink = creator(this);
+            if (!_eventSinks.TryAdd(key, sink)) {
+                sink = _eventSinks[key];
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: >_eventSinks [](start = 23, length = 11)

Not sure why this would find a sink when a few lines above it didn't find one. Unless the creator callback had code in it that called GetOrCreateSink?

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: No telling what could be going on in the creator callback. This is the best pattern for GetOrCreate with a concurrent dictionary (except maybe disposing of IDisposable sinks if we don't use them...)

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs [hunk 8]
```diff
@@ -249,31 +324,31 @@ sealed class PythonTextBufferInfo : IDisposable {
...
-                var result = bi.AnalysisEntry;
-                if (result != null) {
-                    bi.OnNewAnalysisEntry -= handler;
-                    tcs.TrySetResult(result);
-                }
-            };
-
-            return tcs.Task;
-        }
+        //public Task<AnalysisEntry> WaitForAnalysisEntryAsync(CancellationToken cancellationToken) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: >WaitForAnalysisEntryAsync [](start = 37, length = 25)

More code to delete?

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs (hunk 7 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: Except their Dispose probably removes them from the buffer, and in the context of this race it will likely succeed, so they shouldn't be disposed here. (A finalizer-triggered dispose just shouldn't do the remove, since it's only for unmanaged objects.)

File: Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs (hunk 8 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Editor/PythonTextBufferInfo.cs]: 👍

File: Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs [hunk 9]
```diff
@@ -303,31 +294,37 @@ sealed class BufferParser : IDisposable {
...
-            AnalysisEntry entry,
+            VsProjectAnalyzer analyzer,
             IEnumerable<ITextSnapshot> snapshots
         ) {
-            var updates = snapshots.Select(s => GetUpdateForSnapshot(services, s)).Where(u => u != null).ToList();
+            var updates = snapshots
+                .GroupBy(s => PythonTextBufferInfo.TryGetForBuffer(s.TextBuffer)?.AnalysisEntry.FileId ?? -1)
+                .Where(g => g.Key >= 0)
+                .Select(g => Tuple.Create(g.Key, g.Select(s => GetUpdateForSnapshot(services, s)).ToArray()))
+                .Where(u => u != null).ToList();
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs]: >Where(u => u != null) [](start = 17, length = 21)

I'm confused as to what 'u' is now. It used to be the update object. Is that still the case?

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs]: Great catch! This code is somewhat broken now (though I guess we can handle null updates). I'll fix

Comment (huguesv) [reply Python/Product/PythonTools/PythonTools/Intellisense/BufferParser.cs]: I mean it looks like it's the tuple now, which would never be null?

---
In reply to: [135308418](https://github.com/Microsoft/PTVS/pull/2936#discussion_r135308418) [](ancestors = 135308418)

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs [hunk 10]
```diff
@@ -706,39 +706,99 @@ string stdInClientHandle
...
-        /// Creates a new ProjectEntry for the collection of buffers.
-        /// </summary>
-        internal async void ReAnalyzeTextBuffers(BufferParser oldParser) {
-            ITextBuffer[] buffers = oldParser.Buffers;
-            if (buffers.Length > 0) {
-                if (!oldParser.AnalysisEntry.SuppressErrorList) {
-                    _services.ErrorTaskProvider?.ClearErrorSource(oldParser.AnalysisEntry, ParserTaskMoniker);
-                    _services.ErrorTaskProvider?.ClearErrorSource(oldParser.AnalysisEntry, UnresolvedImportMoniker);
-                    _services.CommentTaskProvider?.ClearErrorSource(oldParser.AnalysisEntry, ParserTaskMoniker);
+        internal void ReanalyzeEntry(AnalysisEntry entry) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: >ReanalyzeEntry [](start = 22, length = 14)

Is anyone calling this? And does this really reanalyze the entry?

Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: No, it's dead code now, replaced by the "Transfer[File]FromOldAnalyzer" functions (it used to be called when you renamed a source file).

And I also noticed the `OnModulesChanged` event handler is no longer called... need to figure out when we should trigger that.

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs [hunk 11]
```diff
@@ -706,39 +706,99 @@ string stdInClientHandle
...
+                if (e == null) {
+                    continue;
                 }
 
-                var monitoredResult = await MonitorTextBufferAsync(buffers[0]);
-                if (monitoredResult?.AnalysisEntry != null) {
-                    for (int i = 1; i < buffers.Length; i++) {
-                        monitoredResult.AddBuffer(buffers[i]);
+                ITextBuffer[] buffers;
+                if (oldBuffers.TryGetValue(e.Path, out buffers)) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: >TryGetValue [](start = 31, length = 11)

We could start using the inline out variable declaration like this:
if (oldBuffers.TryGetValue(e.Path, out ITextBuffer[] buffers))

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs (hunk 10 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: Heh, that's been unused for more than a few months now :)

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs [hunk 12]
```diff
@@ -774,42 +823,42 @@ string stdInClientHandle
...
-            var snapshot = (entry.AnalysisCookie as SnapshotCookie)?.Snapshot;
-            // File cannot be parsed from disk, so sync the code from the current buffer
-            // This should be rare in normal use, but very frequent in tests
-            if (snapshot != null && (isTemporaryFile || !File.Exists(entry.Path))) {
-                await BufferParser.ParseBuffersAsync(_services, entry, Enumerable.Repeat(snapshot, 1));
-            }
-
-            return bufferParser;
-        }
+        //internal async Task<BufferParser> MonitorTextBufferAsync(ITextBuffer textBuffer, bool isTemporaryFile = false, bool suppressErrorList = false) {
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: >MonitorTextBufferAsync [](start = 44, length = 22)

More commented out code here

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs (hunk 11 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: Sometimes I don't mind that, other times it's weird (mostly because the scope of the declaration is _outside_ the if block, not restricted to inside it, so you can reuse the variable later on - not a fan of that).

File: Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs (hunk 12 above)
Comment (zooba) [reply Python/Product/PythonTools/PythonTools/Intellisense/ProjectAnalyzer.cs]: 👍

File: Python/Product/PythonTools/PythonTools/Intellisense/XamlTextViewCreationListener.cs [hunk 13]
```diff
@@ -31,46 +33,40 @@ namespace Microsoft.PythonTools.Intellisense {
...
         }
 
         private void TextView_Closed(object sender, EventArgs e) {
             var textView = (ITextView)sender;
 
-            AnalysisEntry entry;
-            if (_entryService.TryGetAnalysisEntry(textView, textView.TextBuffer, out entry)) {
-                entry.Analyzer.BufferDetached(entry, textView.TextBuffer);
-            }
+            //AnalysisEntry entry;
```
Comment (huguesv) [inline Python/Product/PythonTools/PythonTools/Intellisense/XamlTextViewCreationListener.cs]: >AnalysisEntry [](start = 14, length = 13)

TODO?

File: Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs [hunk 14]
```diff
@@ -104,9 +106,29 @@ public static class PythonToolsTestUtilities {
...
-        private static PythonEditorServices CreatePythonEditorServices(IServiceContainer site) {
+        class LazyComponentGetter<T> : Lazy<T> {
+            public LazyComponentGetter(MockComponentModel model) : base(() => (T)model.GetService(typeof(T))) { }
+        }
+
+        private static PythonEditorServices CreatePythonEditorServices(IServiceContainer site, MockComponentModel model) {
             var services = new PythonEditorServices(site);
-            services.ComponentModel.DefaultCompositionService.SatisfyImportsOnce(services);
+
+            //services.ComponentModel.DefaultCompositionService.SatisfyImportsOnce(services);
```
Comment (huguesv) [inline Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs]: >services [](start = 14, length = 8)

delete?

**Comment by huguesv** [comment]
Nothing critical left, 👍 from me

File: Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs (hunk 14 above)
Comment (zooba) [reply Python/Tests/Utilities.Python/PythonToolsTestUtilities.cs]: I kind of like that it shows what we're emulating... maybe I'll add that to the comment too.

**Comment by zooba** [comment]
@huguesv One more change that is worth a second look - there were codepaths in AnalysisEntryService that would incorrectly return null when they shouldn't. I had to reshuffle some code and duplicate some of it.

This broke XAML support completely. It still seems to be broken after this part is fixed, but it's less related to the current set of changes, and importantly won't affect your work on Peek. So I want to get this much in and then look at XAML.

**Comment by huguesv** [comment]
New changes look ok
